### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mai1237** [robsontenorio/mary#1]
Great job
I wonder if it's in your  plans to add the dark mode in  your code.

**Comment by robsontenorio** [comment]
@mai1237 could you give me a sample ?

All components supports dark mode by default. It is just daisyUI/tailwind classes.

**Comment by mai1237** [comment]
First i have installed  Genesis
Ater that i have installed Mary UI
I tryed to test the Form example 
When i ckicked the dark/light toggle button the background collor was allways dark

**Comment by robsontenorio** [comment]
@mai1237 please, share your layout `app.blade.php`

**Comment by mai1237** [comment]
{{-- <div>
    <x-form wire:submit="save">
        <x-input label="Name" wire:model="name" class="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200"/>
        <x-input label="Amount" wire:model="amount" prefix="EUR" money hint="It submits an unmasked value" class="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200" />

        <x-datetime label="My date" wire:model="myDate" icon="o-calendar" class="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200"  />


<x-datetime label="Time" wire:model="myTime" icon="o-calendar" type="time" class="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200" />


<x-datetime label="Date + Time" wire:model="myDateTime" icon="o-calendar" type="datetime-local" class="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200" />
        <x-slot:actions>
            <x-button label="Cancel" />
            <x-button label="Click me!" class="btn-primary" type="submit" spinner="save" />
        </x-slot:actions>
    </x-form>
</div> --}}
<div>
    <x-form wire:submit="save">
        <x-input label="Name" wire:model="name" />
        <x-input label="Amount" wire:model="amount" prefix="EUR" money hint="It submits an unmasked value"   />

        <x-datetime label="My date" wire:model="myDate" icon="o-calendar"  />



<x-datetime label="Time" wire:model="myTime" icon="o-calendar" type="time" />


<x-datetime label="Date + Time" wire:model="myDateTime" icon="o-calendar" type="datetime-local"  />
        <x-slot:actions>
            <x-button label="Cancel" />
            <x-button label="Click me!" class="btn-primary" type="submit" spinner="save" />
        </x-slot:actions>
    </x-form>
</div>

**Comment by mai1237** [comment]
this is dark mode
![image](https://github.com/robsontenorio/mary/assets/2780148/e5d821d6-584b-43ae-bc02-845fea380b7e)

**Comment by robsontenorio** [comment]
I am afraid it has to do with **Genesis**. Once it is a starter kit and provides many default CSS classes that override stuffs.

If you try Mary o brand new project It just works as described here.
 https://mary-ui.com/docs/installation


On bottom of this video I am toggling my OS appearance on Mary docs site.

https://github.com/robsontenorio/mary/assets/118955/e641c601-4bfd-4327-969f-3c4c8fb33a2d

**Comment by mai1237** [comment]
Thanks for the explanation
Do you have any suggestions to overcome the problem with Genesis?

**Comment by robsontenorio** [comment]
@mai1237  I don't work with Genesis. 

But once you opt in for a "starter kit" like Genesis, JetStream and others  you are sticking to an opinionated boilerplate. They provide so many stuff that will conflict with other packages like Mary.  So, there is no easy solution, sorry.

For now you can try Mary on brand new project with to starter kits.

**Comment by mai1237** [comment]
Thank you
