### ISSUE TITLE
$uuid not always unique

### ISSUE THREAD

**Issue by KenKodz** [robsontenorio/mary#100]
In the case that you have an element that is identical to another element except for where it exists in the HTML (ex. different modal) the `$uuid` is not unique because the properties are all the same.

An easy change would be to edit 
```
$this->uuid = md5(serialize($this));
```
to 
```
$this->uuid = md5(serialize($this) . random_bytes(16));
```
to provide some randomness.

**Comment by robsontenorio** [comment]
@KenKodz Nice catch! It is on my todo #71

**Comment by robsontenorio** [comment]
@KenKodz  I need to understand better how Livewire parse this.

Because `wire:key` must be unique across components, but IDK how this rand bytes could affect component stage every time it do a re-render.

**Comment by KenKodz** [comment]
I think the use of this for the id of the element is actually superfluous. The id could be supplied by the user if it's needed. It's not needed by Livewire to my knowledge.

**Comment by KenKodz** [comment]
Submitted too early. 

The issue with having the uuid as the field id is that when there are multiple fields with their ids the same on render, the browser will while account multiple components using the same id. 

It's not a huge issue technically, but it's easy enough to fix. How it's fixed isn't important. I just supplied something without much thought on the efficiency of the function, to be honest.

**Comment by robsontenorio** [comment]
@KenKodz Thanks. I will wait for feedback from issues.
