### ISSUE TITLE
RFC - Choices

### ISSUE THREAD

**Issue by robsontenorio** [robsontenorio/mary#107]
**Hello !**

👋 Let me know in the comments if you had a chance to test it and everything is ok. 

<hr>
<br><br>

https://github.com/robsontenorio/mary/assets/118955/09a0df3b-5e25-43b8-864b-6f1b1f0dda10

<br><br>
<hr>

## Feedback

Choices is by far the **most complex and requested component**. There are still some tricky issues between Livewire/Alpine state sharing. 

🙏  Hope you all can help with some testing and feedback, while I am on it.

## Changes

**There are no breaking changes and API is exactly the same.** 

I have published this hidden docs route for reference.
https://mary-ui.com/docs/components/choices2

**Improvements:**

- Style:
  - Pill style with "x" mark to remove item
  - Border indicator on options list
  - Better "no results found" 

- New features
   - Icon
   - Clear all
   - Select all
  - Compact mode
  - Custom "height"
  - Debounce
  - Min Chars
  - Type ESC to close
  - Support for `readonly` and `required` (HTML properties)
  - Validation state (red color)

## Testing
 
I have temporarily named it as **`<x-choices2>`** for testing purpose , but it will stand as **`<x-choices>`** when released.

**Install**

```
composer require robsontenorio/mary:dev-choices-rework
```

**In case of weird cache issues after requiring this branch run** 

```
php artisan view:clear
```

Now, just swap **x-choices** with **x-choices2**. 

## Screenshots

<details>
  <summary>Click me</summary>

<br>
<hr>
<br>
<br>

<img width="797" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/24b069c8-08fc-4da0-9922-b0416abaf8e4">

<br>
<br>
<br>
<hr>
<br>
<br>
<br>

<img width="798" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/0e197a7e-82df-452b-99e1-3dd31cc0b9ff">

<br>
<br>
<br>
<hr>
<br>
<br>
<br>

<img width="811" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/be73330f-7ffe-44d8-a76d-c6fec3013190">

<br>
<br>
<br>
<hr>
<br>
<br>
<br>

<img width="810" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/47433d0c-a0c5-4892-aee1-f0367af3612b">

<br>
<br>
<br>
<hr>
<br>
<br>
<br>

<img width="844" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/70336004-c051-4e1c-a4b2-917d012e151e">

<br>
<br>
<br>
<hr>
<br>
<br>
<br>

<img width="828" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/9aa3e6ef-cd3b-4a75-92e5-096884ecf511">

</details>

**Comment by robsontenorio** [comment]
I am always pushing new improvements. 

Make sure you have required **latest commit hash**  by looking at `composer.lock` version hash, if not , require it again with. 

```
composer require robsontenorio/mary:dev-choices-rework
``` 

**Don't touch `composer.lock` manually!** 


See #108 .

**Comment by robsontenorio** [comment]
I will keep this open until **November 12**, before merging.

**Comment by bucari** [comment]
Hi @robsontenorio 

i'm testing x-choice2

When the component is focused, a line appears below it
![image](https://github.com/robsontenorio/mary/assets/97893337/a3506856-b8c8-471f-8669-afaa761101f9)

when i search something, no result text i displayed with the search result
![image](https://github.com/robsontenorio/mary/assets/97893337/d45f045b-3b91-4d17-b4a7-75517a5ce635)

Then, can you enable backspace to remove items?

Thanks

**Comment by robsontenorio** [comment]
@bucari 

Remove itens with backspace is on my backlog. 

“buca” was the first thing typed ? Or did you have any previous value selected ? If you could provided a video would be useful, showing the initial state of field until when issue happens. 

Do you confirm you have latest hash commit ? Confirm by requiring the branch again.

**Comment by bucari** [comment]
yes "buca" is the first thing typed. 
Sorry i can't provide a video now.

my search function is this 

```
    public function searchDirigente(string $value = '')
    {
        if (strlen($value) >= 3) {
            $request = Request::create(route('api-dirigenti-search', $value), 'GET');
            $response = Route::dispatch($request);
            // Fetch the response
            $option = json_decode($response->getContent());

            $this->dirigenti = collect($option);
        } else
            $this->dirigenti = collect();

        $preUser = null;
        if ($this->dirigente_id) {
            // Also load selected users, besides result search
            $preUser = User::find($this->dirigente_id);

            $this->dirigenti->add($preUser); // <--- make it appear on list
        }
    }
```

Yes i have latest hash commit

**Comment by bucari** [comment]
it's the same  using your approach, No result found is displayed on first search. Then if a select the option, it disappears.


https://github.com/robsontenorio/mary/assets/97893337/dbb4d903-c605-4ef0-b9e2-86bab12dfa6d

**Comment by robsontenorio** [comment]
@bucari could you share how looks like now your search method ?

**Comment by bucari** [comment]
```
    public function searchDirigente(string $value = '')
    {

        $selectedOption = User::where('id', $this->dirigente_id)->get();

        $this->dirigenti = collect();

        if (strlen($value) >= 3) {
            $request = Request::create(route('api-dirigenti-search', $value), 'GET');
            // $request->headers->set('Accept', 'application/json');
            // Dispatch your request instance with the router
            $response = Route::dispatch($request);
            // Fetch the response
            $option = json_decode($response->getContent());

            $this->dirigenti = collect($option);
        }

        $this->dirigenti = $this->dirigenti->merge($selectedOption); 
    }
```

**Comment by bucari** [comment]
@robsontenorio if x-choices is disabled the component is grayed but is still possible change selected option and search.

**Comment by robsontenorio** [comment]
@bucari 

**A thing to notice**: if you are constrained with **3 min chars** your initial list **always** will be empty.


Here is full working code. Are you sure the API response item has same structure of local user?


```php
new class extends Component {

   // Options list
   public Collection $users; 

   // Selected option
   public ?int $user_id = null;

   public function mount() 
  {
        // Fill options when component first renders
       $this->search();

  }

  public function search(string $value = '')
  {
        // Besides the search results, you must include on demand selected options
        $selectedOption = User::where('id', $this->user_id)->orderBy('name')->get();

        $this->users = collect();

        // This prevents inicial list rendering
        if (strlen($value) >= 3) {

           // API response here
           // Make sure API response is transformed to same structure of `$selectOption`
           // Because it will be merged at end of this method

            $this->users = User::query()
                ->where('name', 'like', "%$value%")
                ->take(5)
                ->orderBy('name')
                ->get();
        }

        $this->users = $this->users->merge($selectedOption);   // <-- Adds selected option
    }
}
```

**Comment by bucari** [comment]
@robsontenorio using attribute min-chars it's ok. No more "No result found" issue .

thanks
