### ISSUE TITLE
Renaming components

### ISSUE THREAD

**Issue by robsontenorio** [robsontenorio/mary#110]
@Sophist-UK @daemon-byte

Just released an option to rename components. Please, upgrade to latest version and let me know if everything works fine.

https://mary-ui.com/docs/installation#renaming-components

<img width="885" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/2e7abf52-48ac-4358-8c02-43a6702c234c">

**Comment by daemon-byte** [comment]
I'm wasn't planning on starting that project yet but what I'll do is try and test it in a demo system tonight so I can do some basic testing

**Comment by daemon-byte** [comment]
It works perfectly. Thanks again for getting it sorted so fast

**Comment by robsontenorio** [comment]
@daemon-byte thanks for sponsorship ❤️

**Comment by Sophist-UK** [comment]
For the record here is the PR for this: #109.
