### ISSUE TITLE
Display validation errors 

### ISSUE THREAD

**Issue by lucas-davi** [robsontenorio/mary#111]
Hello!

it's possible disable error messages in x-form or x-input? 

At times I find it interesting to display them in another way, for example:

![image](https://github.com/robsontenorio/mary/assets/60628727/0e2bcc88-b4a4-4cfd-a3ce-3665fb38e748)

thanks for support

**Comment by robsontenorio** [comment]
Hum…. maybe a new component  “x-errors” to display entire validation error bag.
