### ISSUE TITLE
Duplicate ID Attribute Issue in Livewire Component using :key

### ISSUE THREAD

**Issue by alexnogueirasilva** [robsontenorio/mary#114]
How would I use a `:key` to make my component unique in this way: `<livewire:admin.users.delete :$user wire:key="{{$user->key}}"/>` ? Doing so generates console errors like: Multiple form field elements in the same form have the same id attribute value. This might prevent the browser from correctly autofilling the form.

![image](https://github.com/robsontenorio/mary/assets/29835529/a2b63a2a-42cf-4091-805b-604876b7b2da)

![image](https://github.com/robsontenorio/mary/assets/29835529/0b2d3559-43b3-4721-a36e-e79700cd3cc4)

**Comment by robsontenorio** [comment]
@alexnogueirasilva 

For coincidence I was on it.

Are you able to test this branch ?

```
composer require robsontenorio/mary:dev-fix-listitem-wirekey
php artisan:view clear
```

**Comment by alexnogueirasilva** [comment]
yes I will test

**Comment by alexnogueirasilva** [comment]
Here are the screenshots with the complete code.

![image](https://github.com/robsontenorio/mary/assets/29835529/c0f0855e-2962-44ec-8b76-a80be9ab9d7f)


![image](https://github.com/robsontenorio/mary/assets/29835529/30bbb991-acf6-4dc1-8ab9-231f922614ba)

**Comment by robsontenorio** [comment]
You are complaining about INPUT FIELD, can I seed de source code of them?



<img width="277" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/61a17109-8684-4772-bfde-a800b423de31">

**Comment by alexnogueirasilva** [comment]
While inspecting, these are the codes in `wire:key`, but they repeat across other components, and in this way, it stops rendering the component on the screen.


![image](https://github.com/robsontenorio/mary/assets/29835529/e62bc50f-b939-43ff-9724-e405acfc8af5)


![image](https://github.com/robsontenorio/mary/assets/29835529/48747a3a-8adb-46ae-9b39-ea7356b19eba)

**Comment by alexnogueirasilva** [comment]
https://github.com/agency-devaction/dash-crm

**Comment by robsontenorio** [comment]
@alexnogueirasilva The issue you reported on browser console has nothing to do with tables. 

If you delete the table code block you gonna get same error.

**Comment by alexnogueirasilva** [comment]
@robsontenorio  Look what happens to the component with the wire:key


https://drive.google.com/file/d/18w0bMiwPWEigM6O3mBXvINe7mjEzHrDx/view?usp=sharing

**Comment by robsontenorio** [comment]
@alexnogueirasilva  There are some open issues at Livewire repo. That is not about Mary itself.

For now you can try this dirty `rand()` approach.


```blade
<x-table :headers="$headers" :rows="$posts">
     @scope('actions', $post)
        <livewire:posts.delelete :post="$post" wire:key="delete-{{ $post->id }}-{{ rand() }}" />
     @endscope
</x-table>
```

**Comment by alexnogueirasilva** [comment]
thank you
