### ISSUE TITLE
Error by changing  the prefix 

### ISSUE THREAD

**Issue by mai1237** [robsontenorio/mary#117]
By changing  the prefix  to 'prefix' => 'mary-'
in <x-mary-datetime /> i got the error below
Svg by name "o-calendar" from set "default" not found

**Comment by robsontenorio** [comment]
@mai1237 Fixed. Please, upgrade to latest release.

**Comment by andistywn** [comment]
Same with me, but a different symptom. I got error "Unable to locate a class or view for component [menu-item].".
Then i add "mary-" to couple of code at: vendor\robsontenorio\mary\src\View\Components\Main.php (line:70 ... )
```
 @if($sidebar->attributes['collapsible'])
    <x-mary-menu class="fixed bottom-0 hidden bg-inherit lg:block">
    <x-mary-menu-item
    @click="toggle"
    icon="o-bars-3-bottom-right"
    title="{{ $sidebar->attributes['collapse-text'] ?? $collapseText }}" />
    </x-mary-menu>
@endif
```
then my page have laoded prefectly

**Comment by robsontenorio** [comment]
@andistywn I should fix this. You shouldn’t touch manually on vendor/ files.

**Comment by andistywn** [comment]
Yes.  
It solve the problem :)

> @andistywn Are you able to test this branch ?
> 
> First, **revert** manual changes you have made at `vendor/` files. Then
> 
> ```
> composer require robsontenorio/mary:dev-fix-prefix
> php artisan view:clear
> ```

**Comment by robsontenorio** [comment]
@andistywn Merged. Upgrade to latest version (1.4.2)

```
composer require robsontenorio/mary
php artisan view:clear
```

**Comment by kiogo** [comment]
I am also having this issue but on the latest version of Mary 1.25.3. 
'prefix' => 'mary-',

Svg by name "o-square-3-stack-3d" from set "default" not found.

Fresh Laravel 11 install with Breeze.
