### ISSUE TITLE
Botão com ícone e tooltip

### ISSUE THREAD

**Issue by rodrigoaustincascao** [robsontenorio/mary#133]
Ao utilizar o botão com ícone e tooltip, o conteúdo do botão fica desalinhado.

![image](https://github.com/robsontenorio/mary/assets/4265701/5178f764-107e-4e2e-9e37-7597891a2359)

Acredito que seja algo com a barra de menu lateral:
![image](https://github.com/robsontenorio/mary/assets/4265701/df2fa155-1258-4070-9034-811e8103c8c3)

![image](https://github.com/robsontenorio/mary/assets/4265701/88e88fc7-4ee1-4df6-9a5a-907197ce175a)

O problema ocorre tanto no Chrome como no Firefox.

O código utilizado no exemplo foi:
```
 <x-slot:actions>
            <x-button label="xxxx" link="/customers/{{ $customer->id }}" tooltip="Back" icon="o-arrow-left-circle"
                spinner />
            <x-button icon="o-pencil-square" type="submit" spinner="save" />
</x-slot:actions>
```

**Comment by robsontenorio** [comment]
This issue happens when combines `tooltip` + `link` attributes.

**Comment by robsontenorio** [comment]
Available on latest release.
