### ISSUE TITLE
Modal open

### ISSUE THREAD

**Issue by kaue-f** [robsontenorio/mary#142]
Estou com problema quando eu tento abrir o modal usado o livewire ou o alpine.
![image](https://github.com/robsontenorio/mary/assets/90930907/68f1b2db-401e-4c98-9743-f0f0c3832507)
![image](https://github.com/robsontenorio/mary/assets/90930907/b87d0d0c-02f4-4cf8-82b7-088c03bbc742)

**Comment by robsontenorio** [comment]
@kaue-f please , share your modal code.

**Comment by kaue-f** [comment]
![image](https://github.com/robsontenorio/mary/assets/90930907/c8ede1ef-79f7-4668-a06b-f166a5af4233)
![image](https://github.com/robsontenorio/mary/assets/90930907/ce93af9f-fc22-4127-a659-57fa6e263e11)

**Comment by robsontenorio** [comment]
What is you MaryUI and daisyUI versions?

**Comment by robsontenorio** [comment]
Are you able to test this in another blank component? Just to make sure there is no extra noise on your current component page. Worked?


@iammuttaqi Could you, please, check if this issue has to do with recent changes on modal?


```php
public bool $myModalTest = false;
```

```html
<x-button label="Livewire" class="btn-primary" wire:click="$toggle('myModalTest')" />

    <x-modal wire:model="myModalTest" title="Hello" subtitle="Livewire example" separator>
        Press `ESC`, click outside or click `CANCEL` button to close.

        <x-slot:actions>
            <x-button label="Cancel" @click="$wire.myModalTest = false" />
            <x-button label="Confirm" class="btn-primary" />
        </x-slot:actions>
    </x-modal>
```

**Comment by kaue-f** [comment]
![image](https://github.com/robsontenorio/mary/assets/90930907/b3dc791e-e252-4f82-a002-78a52515ce05)
![image](https://github.com/robsontenorio/mary/assets/90930907/d0361a89-7829-425e-88f6-f2c63179652b)

**Comment by kaue-f** [comment]
![image](https://github.com/robsontenorio/mary/assets/90930907/a47f572a-05a8-4714-81a5-d79eb3f96230)
![image](https://github.com/robsontenorio/mary/assets/90930907/bcf073cf-a639-4a8e-b892-61520604747a)

**Comment by robsontenorio** [comment]
Livewire 3 has built in AlpineJS. So, remove it from `app.js` and restart server.
