### ISSUE TITLE
Maybe , this is related to server problem, not MaryUI.

### ISSUE THREAD

**Issue by andistywn** [robsontenorio/mary#147]
### MaryUI version

1.4.2

### daisyUI version

3.9.4

### Livewire version

3.1.0

### What browsers are affected?

Firefox, Chrome

### What happened?

First of all, I apologize for writing this issue as a bug on MaryUI. I don't have any idea where to ask for help.

I am not sure the source of the problem: from the javascript (livewire ) part or the server part.
Following are the problems that occurred when I use MaryUI.

When localhost server using: `php artisan serve` ,then i clicked the **Collapse** button, it just work as expected.

But when i use **Apache** from **laragon** as localhost server, the **Collapse** button did not work. Nothing happened when I clicked the button.

How to solve this issue?

**Comment by robsontenorio** [comment]
It has to do how Livewire expose its asset and how web servers interpret it. I don’t use Apache or Laragon, but with nginx you solve like this:

https://benjamincrozat.com/livewire-js-404-not-found

I am afraid you have to ask to Google fore more info 😅

**Comment by andistywn** [comment]
Ah, i see 😀
Anyway, thanks for your time @robsontenorio
