### ISSUE TITLE
[FEATURE] x-toast customization

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#148]
Hi @robsontenorio 
it would be nice if we can customize x-toast, for exeample adding icons, change background and test color, change text size and toast size, and use html tags in description.

And when redirecting, is it possibile to make it persistent on the screen? Now it disappears and showed again on the redirect page.

**Comment by robsontenorio** [comment]
@bucari  Right now the redirect option is persistent (for the amount of seconds you have set).

**Comment by robsontenorio** [comment]
@bucari  Available on latest release.
