### ISSUE TITLE
Add Toast option to show html instead of text

### ISSUE THREAD

**Issue by NazimNasser** [robsontenorio/mary#149]
https://github.com/robsontenorio/mary/blob/e1d4645e903e2b41951c0cc912a5acad8ea7dec3/src/View/Components/Toast.php#L38C1-L40C1

Toast `title` and `description` only allow text because of alpine `x-text`,

it would be nice to have html as an option as well so we can bold text for example.

**Comment by robsontenorio** [comment]
@NazimNasser yes, good one.

**Comment by robsontenorio** [comment]
@NazimNasser Available on latest release.
