### ISSUE TITLE
Tabs, double content

### ISSUE THREAD

**Issue by ShikamaruNaraHachidaime** [robsontenorio/mary#15]
Hi Robson,
Great job.
I did the example of the tabs and the content is shown repeated.

**Comment by robsontenorio** [comment]
@ShikamaruNaraHachidaime Please,  give more context and some code.

**Comment by ShikamaruNaraHachidaime** [comment]
Hi, thanks for answering.
I just replicated the example of the tabs from the official documentation so the content is displayed double and the template also appears double in the DOM.

**Comment by robsontenorio** [comment]
@ShikamaruNaraHachidaime 

I can't reproduce. Which  example have you tried? Please, share some code.

Make sure you have on your Livewire component 
```php
public string $selectedTab = 'tricks-tab';
```

**Comment by ShikamaruNaraHachidaime** [comment]
Hi Robson.
The problem is mine, I was using the Breeze authentication scaffolding and it seems to bring some conflict, I changed to Jetstream and so far so good. Sorry for any inconvenience. Keep up the good work, it's a very nice package.
