### ISSUE TITLE
Issue with Icon and Text Alignment After Recent Update

### ISSUE THREAD

**Issue by alexnogueirasilva** [robsontenorio/mary#156]
After the last update, the icons started to look like this, with a line break from the icon to the text, instead of being on the same line. Do you know the reason?

![image](https://github.com/robsontenorio/mary/assets/29835529/b5db1475-be8a-4b1c-8795-58ef2cf501b3)

![image](https://github.com/robsontenorio/mary/assets/29835529/e54b26f3-8569-422d-9639-98c98d404df7)

**Comment by robsontenorio** [comment]
@alexnogueirasilva Make sure you also have upgrade to latest Livewire version and clear view cache.

**Comment by robsontenorio** [comment]
Fixed on 1.5.1
