### ISSUE TITLE
Problem install using Win powershell

### ISSUE THREAD

**Issue by andistywn** [robsontenorio/mary#161]
This error happens when i install MaryUI using Windows powershell v.5.
But, when i use Debian, no problem.
Maybe i need to [upgrade to powershell  v.7](https://stackoverflow.com/questions/563600/can-i-get-or-and-to-work-in-powershell/564092#564092) 

![image](https://github.com/robsontenorio/mary/assets/115723066/22210f4e-f094-421d-b3b2-969a59677127)

Update: I've update to powershwl v.7 and try reinstall maryUI but it refused:
![image](https://github.com/robsontenorio/mary/assets/115723066/2998e10e-c36e-40a2-b21d-0b19c4bfaad9)

I tried to delete` tailwind.config.js` and `postcss.config.js`, but it gave same result. Then, i do manual install

**Comment by robsontenorio** [comment]
@andistywn 

Unfortunately I will need help from Windows users to fix it, because I don't know how to make all things compatible. Right now it works with Mac and Unix.  The installer uses [Laravel Prompts](https://laravel.com/docs/10.x/prompts).

For now, if you don't wanna get stuck you need to do manual install.

**Comment by tjhunkin-inhance** [comment]
+1 with the same issue. Each command runs successfully on its own, so I tried splitting it out to no avail. Will keep digging.

**Comment by robsontenorio** [comment]
@tjhunkin-inhance If a just simple replace it won’t work on another platforms. 

We need a more generic solution.

**Comment by robsontenorio** [comment]
@andistywn @tjhunkin-inhance  @Ma-Mo025 

If you can help to test, I just merged #214 


```sh
composer require robsontenorio/mary:dev-main
```

**Comment by tjhunkin-inhance** [comment]
It worked, thank you
