### ISSUE TITLE
[Bug]: Problem with content-width in card

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#165]
### MaryUI version

1.6.0

### daisyUI version

4.4.10

### Livewire version

3.2.1

### What browsers are affected?

Chrome

### What happened?

There is a problem with your Slot-Div inside card.php
at line 70 you have:
```php
<div>
   {{ $slot }}
</div>
```
and this has the problem that the content is NOT always 100% of the size it has.

i changed it to:
```php
<div class="w-full">
    {{ $slot }}
</div>
```

and now it works fine...

BEFORE the fix

![image](https://github.com/robsontenorio/mary/assets/1830557/2c121f36-d9c7-4f8e-a48b-9e35ffe4ccbf)

AFTER the fix

![image](https://github.com/robsontenorio/mary/assets/1830557/c01c0e40-bf91-401d-847b-7fcfe504ebe2)

**Comment by vogelor** [comment]
First of all - i want to help you - and you have done a great job!

For me to understand...

if it depends on the content - why not fixing it with class="w-full" instead of "hoping" the content is working fine? if i found out the problematic content (for example not enought text in it) what would you do then?

**Comment by vogelor** [comment]
O.K. found it out. Your "root" div (with no size defined) scales to the size of the TEXT and BUTTON in it. Critical is, that my input sizes to 100% of the parent - but the parent is your div and so it scales at 100% width of your div. Your div sizes only to its content - and this is the size of the text plus the size of the button. And this is why it is to small.
So i can't fix this with my content. ONly you can fix this with your "root" - div...

**Comment by robsontenorio** [comment]
Could you share that login screen code ?

**Comment by robsontenorio** [comment]
The issue is `items-center`, remove it and you are good. Because does not make sense to place it there.

```html
<x-card class="w-full sm:max-w-md mt-6 glass items-center bg-base-100/30">
```


https://github.com/robsontenorio/mary/assets/118955/6f17e487-99e0-4e97-87b7-80a7d6dd9b6d

**Comment by vogelor** [comment]
Yes - your right. that`s strange...
