### ISSUE TITLE
[Bug]: glass on card is not working

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#169]
### MaryUI version

1.6

### daisyUI version

4.4.10

### Livewire version

3.2

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

if you add the class "glass" to your card, it will NOT become transparent.
This is, because you use always 

```php
          {{
                        $attributes
                            ->merge(['wire:key' => $uuid ])
                            ->class(['card bg-base-100 rounded-lg p-5', 'shadow-sm' => $shadow])
                    }}
```
and bg-base-100 has no transparency.

At the moment i fixed this with calling your card component like so:
```blade
  <x-card class="glass bg-base-100/30">
```
but i think you should fix this (or add it to your documentation) ;-)

**Comment by robsontenorio** [comment]
@vogelor  

This is expected. By default, components provides some barebones style, and for any further style you should override it with desired classes.

Depending on case, some times you need to force override like `!text-red-500` due to tailwind class precedence engine.

**Comment by vogelor** [comment]
O.K. so this is the preferred behavior. Then i think it is great to add it to your documentation (a glass - card). Maybe others had the same "problem" than me...
