### ISSUE TITLE
[Bug]: Selectable Table doesn't work with default paginator

### ISSUE THREAD

**Issue by ash-dealerwebs** [robsontenorio/mary#171]
### MaryUI version

1.6.0

### daisyUI version

4.4.10

### Livewire version

3.2.1

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

When using the default Eloquent paginator, the select all button doesn't work (on the Table component), as it cannot pluck the keys correctly from the array, due to it being collect()'ed again and this causing a problem with the pluck not being able to access the correct "items" array.

A workaround I'm using for now is to pass pagination data separately from the headings, but having two variables for the same job isn't ideal.

My proposed change would be something like this:

```php

    // Get all ids for selectable and expandable features
    public function getAllIds(): array
    {
        return collect($this->rows)->pluck($this->selectableKey)->all();
    }
```

being changed to this:

```php

    // Get all ids for selectable and expandable features
    public function getAllIds(): array
    {
        // Don't collect the array again if it's a paginator response, as this will cause the "items" Collection inside it to be incorrect, and the keys wouldn't be plucked correctly
        if ($this->rows InstanceOf \Illuminate\Pagination\LengthAwarePaginator) {
            return $this->rows->pluck($this->selectableKey)->all();
        }
        return collect($this->rows)->pluck($this->selectableKey)->all();
    }
```

**Also a function similar to @row-click, but for headers, a lá @header-click would be awesome**

**Comment by robsontenorio** [comment]
@ash-dealerwebs Nice catch! If you can open these small PR when you find some useful improvement. I will appreciate.

**Comment by robsontenorio** [comment]
@ash-dealerwebs 

I have fixed this case for now.
But soon I will put some work on `<x-table>` to add full builtin support for pagination and column sort.
