### ISSUE TITLE
Disabling wire:navigate at the button

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#173]
if the button component is a link (and not external) you always add wire:navigate

```php
         @if($link && ! $external)
                        wire:navigate
                    @endif
```
but sometimes i don`t want this behavior.
Maybe you can add a flag (or a config) to disable this.

```php
         @if($link && ! $external && ! $disableNavigate)
                        wire:navigate
                    @endif
```

**Comment by robsontenorio** [comment]
Yes, this would be nice to have on buttons. I will add in next release. 

Right now this approach works for `<x-menu-item …. no-wire-navigate />`
