### ISSUE TITLE
[Bug]: Centering checkbox with long text (label)

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#174]
### MaryUI version

1.6

### daisyUI version

4.4.10

### Livewire version

3.2

### What browsers are affected?

Chrome

### What happened?

if you have a checkbox with a "long" label like so:
```blade
                    <x-checkbox>
                        <x-slot:label>
                            1<br>2<br>3<br>4
                        </x-slot:label>
                    </x-checkbox>
```
Then the checkbox get centered
![check-1](https://github.com/robsontenorio/mary/assets/1830557/1d702e9f-cbd4-456e-9a16-d0e24839dfe7)

this is because of the code inside your Checkbox.php line 22
```php
  <label class="flex items-center gap-3 cursor-pointer">                     
```

if you remove the items-center it works well.

![check-2](https://github.com/robsontenorio/mary/assets/1830557/ce9516ec-f770-4f8a-98c4-b8e841c4f3fe)

i think the second solution (checkbox at the top) is the expected solution - what do you think?

**Comment by robsontenorio** [comment]
I am not sure what is better position. I will research for some better UX best practices.

**Comment by vogelor** [comment]
Maybe you can allow both with an parameter (at-top for example)?

**Comment by robsontenorio** [comment]
It is make sense to be top aligned. I will fix it on next release.
