### ISSUE TITLE
Tabs Component Wrap on Mobile device

### ISSUE THREAD

**Issue by tjhunkin-inhance** [robsontenorio/mary#177]
For the tabs component to be responsive, especially for mobile, it can wrap to the next "line".

**Comment by robsontenorio** [comment]
Please , share the code as markdown and a print about how it looks like.

**Comment by robsontenorio** [comment]
If you are talking about horizontal overflow, it is expected on mobile. Just swipe your finger and tabs will scroll horizontally.

<img width="392" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/d23974ee-0a18-4a91-b6f7-34026d5020ad">
