### ISSUE TITLE
Adding components to resources dir rather than in vendor files 

### ISSUE THREAD

**Issue by Silomalo** [robsontenorio/mary#179]
Hi @robsontenorio 
Great work, but I would like to have full control over the components, is there a way you can make all the components to be loaded to resources files rather than the vendor dir?

More of shadcn style, this makes users more confident with the code and guarantees that the app developed will always run anytime in the future. Thanks

**Comment by robsontenorio** [comment]
@Silomalo 

The approach here is the opposite: if you publish components you have to maintain them by yourself. 

It happens now with Breeze or Jetstream, where you have a "copy" in each project. If you want to change a button feature you have manually to do it in all your projects.

If you want to maintain the components yourself there is no point in using a ready-made component library.
