### ISSUE TITLE
Radio "Attempt to read propery ID"

### ISSUE THREAD

**Issue by groxw** [robsontenorio/mary#18]
Hi @robsontenorio , I've found something error. It's because Attempt to read property "id" on array, 

Well. I am using livewire 3.0 and Mary with latest updated 

                                @php
                                    $genders = collect([
                                        [
                                            'id' => 1,
                                            'name' => 'Laki-laki',
                                        ],
                                        [
                                            'id' => 0,
                                            'name' => 'Perempuan',
                                        ]
                                    ]);
                                @endphp

                                <x-radio
                                label="Select one"
                                :options="$genders"
                                wire:model="jenis_gender"
                                hint="Gender kamu?"
                                />

I don't know what's the problem, because when I try to use Mary 3.4, it is working jus fine,

**Comment by robsontenorio** [comment]
@groxw I am on it.

**Comment by robsontenorio** [comment]
@groxw Just released `0.35.0`. Now it allows array syntax. Please, upgrade and let me know if it is ok.

**Comment by groxw** [comment]
Well great! I've updated and it's working, thanks @robsontenorio 🚀
