### ISSUE TITLE
tailwind merge classes

### ISSUE THREAD

**Issue by fabpl** [robsontenorio/mary#187]
Hi!

When using your components, you allow developer to add some tailwind classes.
This classes will only complete yours, not really "merge".

Exemple with :

```blade
<x-nav class="bg-neutral text-neutral-content">
    // ....
</x-nav>
```

It's produce :

```html
<div class="bg-base-100 border-gray-100 border-b bg-neutral text-neutral-content">
    // ....
</div>
```

You can see there's 2 "bg-*" classes.
With this order, there's no really a problem, but i suggest to use [Tailwind merge](https://github.com/gehrisandro/tailwind-merge-laravel) to correctly "merge" this classes.

**Comment by robsontenorio** [comment]
@fabpl 

I see. Maybe when this get merged I can take a look, because I use conditionals a lot. 

https://github.com/gehrisandro/tailwind-merge-laravel/pull/4
