### ISSUE TITLE
[Bug]: After installing Mary in my filament program, the style became disordered

### ISSUE THREAD

**Issue by LTaooo** [robsontenorio/mary#189]
### MaryUI version

1.7

### daisyUI version

4.4.19

### Livewire version

3.2.3

### What browsers are affected?

Chrome

### What happened?

![image](https://github.com/robsontenorio/mary/assets/28125259/482415a1-311d-4535-9273-d9daf4964177)

**Comment by LTaooo** [comment]
Before
![image](https://github.com/robsontenorio/mary/assets/28125259/91fc1feb-04ac-4c3f-9f14-7220d81f7bff)

**Comment by robsontenorio** [comment]
@LTaooo 

Manual or Automatic install?

Mary does not add any custom CSS.  If things get disordered maybe because you have changed something on **app.css**?

**Comment by robsontenorio** [comment]
In this case you have changed `tailwind.config.js`. I suggest you rollback all changes and add only the diff on target files.

As Filament is your  "main" component library some CSS from it can "leak" and affect Mary components.

So, as described on docs you need to solve this conflicts by yourself, once Mary is intended to be the main component library.

**Comment by LTaooo** [comment]
Ok, thank you very much for your help

**Comment by robsontenorio** [comment]
@LTaooo if you can let me know how you solved it , for future reference.

**Comment by LTaooo** [comment]
> @LTaooo if you can let me know how you solved it , for future reference.

ok

**Comment by tabarnouche** [comment]
I had a similar problem after installing Mary in an existing project.
In my case,
```js
"./vendor/robsontenorio/mary/src/View/Components/**/*.php"
```
was missing from the content array in tailwind.config.js.
