### ISSUE TITLE
HasClear attribute on x-input

### ISSUE THREAD

**Issue by nathan-dealerwebs** [robsontenorio/mary#198]
Would like the ability to be able clear inputs via an x-icon (X) in the right hand corner. Useful as currently using this as a search input using model.live and want to trigger a reset and clear the input and url. 

Passing hasClear attribute on the input  i.e. `<x-input hasClear='true' />` would then set the class variable and render the div wrapper around the main input, much like the `$money` attribute does. The `showClear()` function just checks to see the length of the model value and sets `this.clear` accordingly. The `reset()` function sets the clear variable to false which hides the icon, clears the input and triggers the event.

The only issue I could forsee is that `$iconRight` would be in the same place so some css will be needed to shift the clear across to the left or right of that.

Something like this:

```php
public function __construct(
    public ?bool $hasClear = false;
)
```

```php
public function render(): View|Closure|string
{
    <!-- CLEAR -->
    @if($hasClear)
        <div x-data="{
                clear: false,
                reset() {
                    this.clear = false;
                    $refs.myInput.value = '';
                    $refs.myInput.dispatchEvent(new Event('input'));
                },
                showClear() {
                    if( $wire.{{ $modelName() }}.length > 0 ) {
                        this.clear = true;
                    }else{
                        this.clear = false;
                    }
                }
            }"
            @input="showClear()"
            x-init="$nextTick(() => showClear())"
        >    
    @endif
    

     <!-- INPUT HERE -->

     
     <!-- CLEAR ICON  -->
     @if($hasClear)
         <x-mary-icon x-show="clear" @click="reset()"  name="o-x-mark" class="absolute top-1/2 right-8 -translate-y-1/2 cursor-pointer text-gray-400 hover:text-gray-600" />
     @endif
    
    <!-- END CLEAR -->
    @if($hasClear)
        </div>
    @endif

}

```

**Comment by robsontenorio** [comment]
@nathan-dealerwebs It would be a nice feature. Should add it on next release. Thanks :)

**Comment by robsontenorio** [comment]
@nathan-dealerwebs 



<img width="813" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/8c489e1d-0809-4384-9108-4bb61eca3de1">
