### ISSUE TITLE
Choices Component multiple selection close option on any selection

### ISSUE THREAD

**Issue by tjhunkin-inhance** [robsontenorio/mary#206]
Hi, amazing work btw!

For the choices multiple select, is there any way to have it close after a selection each time? I find that clicking away doesn't close it sometimes and on mobile it is a struggle to get it closed sometimes.

Like this: https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

EDIT: On mobile, if you click above the component, it doesn't close, but that is all the space you have. Only clicking on another input above the multi-select choices component does it close.

Thank you so much

**Comment by robsontenorio** [comment]
@tjhunkin-inhance 

On multiples libraries I see the default behavior is not to close the list, once it is expected some scroll to select another option.

VUETIFY https://vuetifyjs.com/en/components/selects/#usage
QUASAR https://quasar.dev/vue-components/select#the-model

To be honest, I don't know if I can beat Select2.

**Comment by tjhunkin-inhance** [comment]
I see, thanks for checking.

The only difference would be that they open upwards and that you have the space below them to close them.

Whereas your cool one opens downwards, but on mobile, if you tap directly above it in between an input element directly above it, it doesn't close, so you need to tap a couple of places to see where it closes.

It's not a huge problem at all, just an observation.

**Comment by robsontenorio** [comment]
Maybe if you attach a video I can understand better what you mean. Because on real mobile phone I can tap outside anywhere and it closes.
