### ISSUE TITLE
Mark Required

### ISSUE THREAD

**Issue by ducopro** [robsontenorio/mary#21]
Hi Robson,

For all types of input elements I am missing something to mark the field visually as **required**.

Is this by design? Did I miss something?

Grtz

**Comment by robsontenorio** [comment]
@ducopro It is by design. It does not have required mark. 

For now , can you use placeholders ?
```
placeholder=“Required”
```

Or label itself 
```
label=“Address (*)”
```

**Comment by ducopro** [comment]
@robsontenorio no problem for now. I will figure it out. That's what programmers are for ..
