### ISSUE TITLE
[Bug]: Update DaisyUI

### ISSUE THREAD

**Issue by alexnogueirasilva** [robsontenorio/mary#215]
### MaryUI version

1.12.0

### daisyUI version

4.4.20

### Livewire version

3.3.0

### What browsers are affected?

Chrome

### What happened?

✅ For sure you can paste screenshots.
![Screenshot from 2023-12-17 17-17-21](https://github.com/robsontenorio/mary/assets/29835529/b4178b2c-b7f0-4748-893b-214f851dcfc4)

After updating the daisyui library, these scroll bars started to appear, both on the right side and at the bottom. Can MaryUI use the new version of daisyui?

**Comment by robsontenorio** [comment]
@alexnogueirasilva 

Mary does not install daisyUI itself. Daisy is installed on your side package.json

Mary just uses css classes provided by daisy. 

Are you able to downgrade daisy and let me know what version scroll bars works as expected

**Comment by alexnogueirasilva** [comment]
@robsontenorio It works perfectly in the version 'daisyui': '^3.9.4'.

**Comment by robsontenorio** [comment]
Try 4.4.19

**Comment by alexnogueirasilva** [comment]
![image](https://github.com/robsontenorio/mary/assets/29835529/15ff4a49-13db-4a8e-8743-98c47f93718f)


https://github.com/robsontenorio/mary/assets/29835529/4a0b2513-1d24-4337-a3e6-bab12a723b11



Even with version '4.4.19', the scroll bar appears.

**Comment by robsontenorio** [comment]
@alexnogueirasilva Could you share this repo with me?

**Comment by alexnogueirasilva** [comment]
yep, this repo https://github.com/agency-devaction/agency

**Comment by robsontenorio** [comment]
@alexnogueirasilva 

I can't run this project because there is not a README.

Probably the issue this that bunch of extra CSS. Try to gradually remove some of them until you spot the problem.

<img width="463" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/9b80e41c-c13e-4677-8c37-39838c7f6a18">

**Comment by alexnogueirasilva** [comment]
@robsontenorio 

I'll do this to check the problem, I found it strange because in versions below 4 of DaisyUI it works normally, but I'll check it out.

**Comment by alexnogueirasilva** [comment]
I removed all the additional CSS and yet the bar still appears when updating to version 4 of DaisyUI, which is quite strange. I am testing it here.

https://github.com/robsontenorio/mary/assets/29835529/6c5f3345-b12a-4a89-a856-b3152b0f2af0

**Comment by alexnogueirasilva** [comment]
Test version by version, and up to this one works well.      ` "daisyui": "4.4.10",`

**Comment by robsontenorio** [comment]
I have uma project with same layout to yours and

**Comment by alexnogueirasilva** [comment]
@robsontenorio  I've updated the README, in case you want to take a look.

**Comment by robsontenorio** [comment]
I could not find any issue with scrollbars. I am on Mac.

Probably this is related to daisyUI + Windows.  I will close for now. 

If you find any solution, let me know.


<img width="1436" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/689d138b-e18e-4b80-9521-cde919eeb9fc">
