### ISSUE TITLE
x-toast with long text

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#218]
Using x-toast, if the message is very long, like an sql error message, the toast is longer than the screen size and the message is not readable.

If i set css attribute to w-96 like this

```
        catch (\Exception $e)
        {
             $this->error($e->getMessage(), position: 'toast-top toast-end', timeout: 30000, css: 'alert-error w-96');     
        } 
```
i would like that the toast grows vertically wrapping the text.

**Comment by robsontenorio** [comment]
I am afraid I can't help you with this, because toast are meant to be used for quick feedbacks for users.

Besides that, I would advice you to not throw internal errors to users, because that is a security issue.
