### ISSUE TITLE
[Bug]: x-menu activate-by-route not working 

### ISSUE THREAD

**Issue by aleex1848** [robsontenorio/mary#219]
### MaryUI version

1.12.0

### daisyUI version

4.4.20

### Livewire version

3.3.0

### What browsers are affected?

Firefox, Chrome, Microsoft Edge

### What happened?

Simply adding "activate-by-menu" attribute on a x-menu component does not seem to work. Am i missing something?

My code looks like this:

```
<x-slot:sidebar drawer="main-drawer" class="bg-base-200">
        <div class="mx-3">
            <x-menu activate-by-route>
                <x-menu-item title="Home" icon="o-home" />
                <x-menu-item title="Messages" icon="o-envelope" />
                <x-menu-sub title="Modules" icon="o-cube">
                    <x-menu-sub title="DSR" icon="o-cube">
                        <x-menu-item title="Start" icon="o-archive-box" link="/modules/dsr" />
                        <x-menu-item title="Tasks" icon="o-wifi" link="/modules/dsr/tasks" />
                    </x-menu-sub>
                </x-menu-sub>
            </x-menu>
        </div>
    </x-slot:sidebar>
```

![x-menu](https://github.com/robsontenorio/mary/assets/17452861/0f44e0a9-30b4-4227-9969-1aed49fecdba)

When i place "active" attribute manually it looks good:

```
<x-slot:sidebar drawer="main-drawer" class="bg-base-200">
        <div class="mx-3">
            <x-menu activate-by-route>
                <x-menu-item title="Home" icon="o-home" />
                <x-menu-item title="Messages" icon="o-envelope" />
                <x-menu-sub title="Modules" icon="o-cube">
                    <x-menu-sub title="DSR" icon="o-cube">
                        <x-menu-item active title="Start" icon="o-archive-box" link="/modules/dsr" />
                        <x-menu-item title="Tasks" icon="o-wifi" link="/modules/dsr/tasks" />
                    </x-menu-sub>
                </x-menu-sub>
            </x-menu>
        </div>
    </x-slot:sidebar>

```
![image](https://github.com/robsontenorio/mary/assets/17452861/8a543f26-1203-4c08-b463-7cb7ae1180ba)

**Comment by robsontenorio** [comment]
@aleex1848 

Hum.., i have never tried with 3 levels. 

Can you make it like this to test?

- link="/modules/dsr/start” <—- here
- link="/modules/dsr/tasks"


Then try to remove one level from menu. Just for test sake.

**Comment by aleex1848** [comment]
@robsontenorio thank you for reply.

for me it's not even working without any sub-menu. i changed code like this:

```
<x-slot:sidebar drawer="main-drawer" class="bg-base-200">
        <div class="mx-3">
            <x-menu activate-by-route>
                <x-menu-item title="Start" icon="o-archive-box" link="/modules/dsr" />
                <x-menu-item title="Tasks" icon="o-wifi" link="/modules/dsr/tasks" />
            </x-menu>
        </div>
    </x-slot:sidebar>
```

and it's not working

![x-menu-2](https://github.com/robsontenorio/mary/assets/17452861/b97aaef3-0ee4-44b2-a3da-264433fc67a1)

**Comment by robsontenorio** [comment]
@aleex1848 

I think the default active menu background color is very similar to your default background. Try to change it

```html
<x-menu active-bg-color="bg-blue-50" ...>
```

And other issue is about route collision. The active route works with "base route". So you have to work like this:

```html
<x-menu-item .... link="/modules/dsr/start" /> <-- Here!
<x-menu-item .... link="/modules/dsr/tasks" />
```

**From docs:**

<img width="603" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/502af455-8a3a-489b-8fa8-6e287b6b98b6">

**Comment by aleex1848** [comment]
@robsontenorio thanks for reply

I'm sorry, but it doesn't work. Setting the active attribute manually works, activating by route does not work.
I'm using Livewire Volt & Laravel Folio, maybe one of these is disrupting your functionality?

My updated code without route-collision and better visible active-bg-color:

```
<x-menu active-bg-color="bg-red-50" activate-by-route>
                <x-menu-item
                    title="Start"
                    icon="o-archive-box"
                    link="/modules/dsr/start" />
                <x-menu-item
                    title="Tasks"
                    icon="o-wifi"
                    link="/modules/dsr/tasks" />
            </x-menu>
```

![x-menu-3](https://github.com/robsontenorio/mary/assets/17452861/a7d5058d-be9b-4db4-968a-5ea9409189f3)

**Comment by robsontenorio** [comment]
@aleex1848  Could share your full `app.blade template`  and `web.php` ?

**Comment by aleex1848** [comment]
@robsontenorio 
as i'm using[ laravel folio](https://laravel.com/docs/10.x/folio) i do not have routes in my web.php

i just took a look in your MenuItem class and added log like this:
```
public function routeMatches(): bool
    {
...
        $link = url($this->link ?? '');
        $route = url(Route::current()->uri());
        Log::info('link vs route',['link' => $link,'route' => $route]);
  ...
    }
```

and in the log you can see the problem:
```
[2023-12-19 19:27:08] local.INFO: link vs route {"link":"http://admin-local.traefik.me:88/modules/dsr/start","route":"http://admin-local.traefik.me:88/{fallbackPlaceholder}"} 
[2023-12-19 19:27:08] local.INFO: link vs route {"link":"http://admin-local.traefik.me:88/modules/dsr/tasks","route":"http://admin-local.traefik.me:88/{fallbackPlaceholder}"}
```

in my current route there is only /{fallbackPlaceholder} instead of the correct path, i guess this is done by using this: https://laravel.com/docs/10.x/routing#fallback-routes

which obviously seems to be the way how folio works.

when i change $route in your MenuItem from
`        $route = url(Route::current()->uri());`
to
`        $route = url(request()->url());
`

it works perfectly fine! do you see any chance to make this change?

Thank you for your support!

![x-menu-4](https://github.com/robsontenorio/mary/assets/17452861/1b60df7c-7946-418c-859c-fe92f9b764bf)

**Comment by robsontenorio** [comment]
@aleex1848 

Yes. Will include it on next release. Thanks!

**Comment by aleex1848** [comment]
Another hint regarding this topic. After moving my project to production server i noticed that activate-by-route stopped working again.

  Checking log like [described here](https://github.com/robsontenorio/mary/issues/219#:~:text=MenuItem%20class%20and-,added%20log,-like%20this%3A) shows: 
` production.INFO: link vs route {"link":"https://admin.swarm.x.com/modules/dsr/shared_parameters","route":"http://admin.swarm.x.com/modules/dsr/start"}`

My laravel-app now is sitting behind reverse-proxy which does the ssl part. so laravel itself "thinks" it is using http what causes this problem. So i ended up setting request object to https in my AppServiceProvider boot() method:
```
public function boot(): void
    {
        if(!$this->app->environment('local')) {
            \URL::forceScheme('https');
            $this->app['request']->server->set('HTTPS', true);
        }
    }
```
This works fine.

**Comment by robsontenorio** [comment]
Some providers in fact requires you force that HTTPS stuff. MaryUI docs site is a Laravel app and has this stuff in place. 

But it is not related to menu component itself.

**Comment by aleex1848** [comment]
Your're totally right. Usually you only have to add `\URL::forceScheme('https');` and that's so routine that it's not worth mentioning.

But because of the change [did here ](https://github.com/robsontenorio/mary/pull/222) for making it folio-compatible now you have to add `$this->app['request']->server->set('HTTPS', true);`  to make things working. This is a very specific config, i never had to use it before. So i guessed it would be good to have it written done somewhere e.g. in an issue comment :)
