### ISSUE TITLE
x-choices inside DaisyUI collapse 

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#22]
Hi,
using x-choices inside a DaisyUI collapse result this behavior

![image](https://github.com/robsontenorio/mary/assets/97893337/852e9524-c52b-4921-9cbb-3318b479fa14)

the items list is hidden inside the collapse-content div. 
How should i set the z-index?

**Comment by robsontenorio** [comment]
https://tailwindcss.com/docs/z-index

Choices result has `z-10`. You can set a lower index on daisy Collapse element or wrap Choices on a `div` a higher index.

**Comment by bucari** [comment]
I tried but nothing changes

**Comment by robsontenorio** [comment]
This is stuff has to do with Tailwind not Mary itself.

```html
<div class="collapse bg-base-200 overflow-visible"> //  <---- overflow-visible
        <input type="checkbox" /> 
        <div class="collapse-title text-xl font-medium">
            Click me to show/hide content
        </div>
        <div class="collapse-content"> 
             CHOICES HERE
        </div>
    </div>
```
