### ISSUE TITLE
Horizontal Timeline

### ISSUE THREAD

**Issue by basst85** [robsontenorio/mary#224]
Support for a horizontal version of the Timeline component would be a nice addition.

**Comment by robsontenorio** [comment]
@basst85 could you share some examples with prints ?

**Comment by basst85** [comment]
@robsontenorio Like this one from daisyUI: https://daisyui.com/components/steps/#horizontal

**Comment by robsontenorio** [comment]
Actually , that sounds like a stepper. Will add it to backlog.

**Comment by basst85** [comment]
You're right. A timeline looks a bit like a stepper 😅

**Comment by robsontenorio** [comment]
👀 WIP


https://github.com/robsontenorio/mary/assets/118955/5ccf9668-41a0-4a5a-a191-963825c6ee2c
