### ISSUE TITLE
RFC - HTML editor

### ISSUE THREAD

**Issue by robsontenorio** [robsontenorio/mary#226]
I am willing to add third party integration for HTML editor. 

I know most of editors allows ordinary actions (bold, alignment, font size, table, etc...). Most of them provide a **simple image uploader**.

But, the main requirement I am looking for is a **powerful image upload management**, where you can browser on cloud system to choose previous uploaded images, through folders.

The most featured editor I know is **TinyMCE**, but requires **an extra** Laravel package to make this image folder management work.

What is the best alternative nowadays? Let me know with links on comments.

**Comment by mehdiyaq** [comment]
TinyMCE is great, I use Froala, and consider having RTL support too. Thank you.
