### ISSUE TITLE
<x-table> combine sort+pagination & nested sorting 

### ISSUE THREAD

**Issue by aleex1848** [robsontenorio/mary#231]
I'm currently trying out your table component and here are my experiences so far:

For combination of Pagination + Sorting you have to setup your $sortBy array as an Livewire property. The paginated data itself including the orderBy-query must not be declared as livewire property instead you have to use computed property, see [this discussion](https://github.com/livewire/livewire/discussions/6655)  

For sorting nested columns you have to use [withAggregate()](https://laravel.com/api/10.x/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.html#method_withAggregate) function instead of eager-loading the relationship.
By using [withAggregate](https://laravel.com/api/10.x/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.html#method_withAggregate) you get a new column in your collection named relation_column. So in my case i need the "task"-relations's "name" property so im doing:
`->withAggregate('task','name')
`
which provides a new column "task_name" in my collection. Now you can use this key in your headers array to make nested columns sortable. 

if you follow the docs you would use dot.notation in headers-array which would lead to SQL Error like this when trying to sort:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'task.name' in 'order clause'
`

Using Livewire Volt functional API it looks like this:  
```
use function Livewire\Volt\{state,usesPagination,computed};

usesPagination();

state([
    'sortBy' => ['column' => 'id', 'direction' => 'asc'],
    'headers' => [
                ['key' => 'id', 'label' => 'ID#'],
                ['key' => 'start', 'label' => 'Start'],
                ['key' => 'task_name', 'label' => 'Task'],
                ['key' => 'type', 'label' => 'Typ'],
                ['key' => 'log_successful', 'label' => 'Erfolg']
        ]
]);

$myRuns = computed(function () {
    return Run::withAggregate('task','name')->withAggregate('log','successful')->orderBy(...array_values($this->sortBy))->paginate(2);
});

```

the actual x-table looks like this: 
```
<x-table :headers="$this->headers" :rows="$this->myRuns" striped with-pagination link="/modules/dsr/runs/{id}" :sort-by="$sortBy">
                @scope('cell_log_successful', $run)
                    @if($run->log_successful)
                        <x-badge class="badge-success" value="Ja"/>
                    @else
                        <x-badge class="badge-error" value="Nein"/>
                    @endif
                @endscope

                @scope('cell_start', $run)
                    {{$run->start->format('d.m.Y h:i')}} Uhr
                @endscope

            </x-table>
```
even the scoped cell_slots are sorting fine because the colum names equal the actual table columns names.

![x-table-2](https://github.com/robsontenorio/mary/assets/17452861/d3b5ee4c-4cb8-49af-89b2-1add5d0a4ace)

@robsontenorio 
Maybe this is interesting enough to be mentioned in the docs?

**Comment by robsontenorio** [comment]
@aleex1848 

That is a nice approach , I will place a note on docs. Isn’t a bug right ?

**Comment by aleex1848** [comment]
Nope, no bugs here. I just wanted to tell my experience for the next guy who wants to achieve this.

**Comment by robsontenorio** [comment]
<img width="838" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/4224a5af-01c2-452f-91a5-cd8cf1e7049a">

**Comment by robsontenorio** [comment]
And another useful custom sortBy per column, for complex cases.

<img width="728" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/adb9b44f-ad53-4f1d-ab84-deec6c13a582">
