### ISSUE TITLE
using tabler icons instead of heroicons

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#238]
Tabler icons have more than 4900 Icons.

Why not using them (configurable: heroicons or tabler)

if you add

`secondnetwork/blade-tabler-icons` to your composer-dependencies you have them, but mary didn't use them.

So maybe you can make it configurable, which icon-set to use?

i know, not all icons have the same names, so we need also a mapping inside the configuration...

Just a idea...

**Comment by robsontenorio** [comment]
@vogelor 

https://mary-ui.com/docs/components/icon#alternative-iconset

**Comment by vogelor** [comment]
Yes, i know - and i am using tabler.xxxxx
BUT mary uses the hero icons internally. So the "internal" Icons are different from the icons, my app is using.

**Comment by robsontenorio** [comment]
I don’t get your point. Please , give me a sample code where you want to use tabler icons and you can’t.

**Comment by vogelor** [comment]
i am sorry, my fault. i thought about your timepicker. but - my fault - i see i can set up my own icons.
SORRY for that. i am closing this issue...
