### ISSUE TITLE
Support @entangle().live for the Tags Component

### ISSUE THREAD

**Issue by dirtbikr** [robsontenorio/mary#239]
I don't currently see a standardized way to pass @entangle() the live property. I found myself needing this for the Tags component, but did not see a way to enable it.

![Export-1703790373257](https://github.com/robsontenorio/mary/assets/6034702/584b3115-6cfd-4462-846a-f7aa71082189)

Added in Tags.php:
PHP      
        
```php
    public function live(): bool
    {
        return $this->attributes->has('live');
    }
```
        
HTML/Blade
        
```blade
        @if($live())
            tags: @entangle($attributes->wire('model')).live,
        @else
            tags: @entangle($attributes->wire('model')),
        @endif
```

I'm not sure if you want this in another format or some other way to trigger it. I would be happy to open a PR with the changes after I know what style you'd like / we discuss the best way to enable this.

**Comment by robsontenorio** [comment]
@dirtbikr What's is your current app code? And what you are trying to achieve ?

**Comment by dirtbikr** [comment]
Very strange, I included a gif in the original post but it doesn't show. Here's the link to it: [https://github.com/robsontenorio/mary/assets/6034702/584b3115-6cfd-4462-846a-f7aa71082189](https://github.com/robsontenorio/mary/assets/6034702/584b3115-6cfd-4462-846a-f7aa71082189)

I figure that should show what I'm trying to accomplish.

Since the Tags component is spun up with `tags: @entangle($attributes->wire('model'))` and not `tags: @entangle($attributes->wire('model')).live`, changes are not reflected until the next network request (new Livewire 3 behavior compared to Livewire 2). I have an `updatedTags()` method in my component, but it doesn't fire when tags are added or removed unless `.live` is added to entangle.

**Comment by robsontenorio** [comment]
Have you tried this? 

```html
<x-tags wire:model.live="myTags" />
```

This is a Livewire itself approach for models that must be `live`

The `@entangle`  is smart enough to handle the `live` case.

**Comment by dirtbikr** [comment]
Yes, I have tried that. It is not compatible with the Tags component. See gif below:
![Export-1703808527318](https://github.com/robsontenorio/mary/assets/6034702/52ee97de-0d97-4448-9477-cc254d2e209e)


[https://github.com/robsontenorio/mary/assets/6034702/52ee97de-0d97-4448-9477-cc254d2e209e](https://github.com/robsontenorio/mary/assets/6034702/52ee97de-0d97-4448-9477-cc254d2e209e)

**Comment by robsontenorio** [comment]
@iammuttaqi  Could you give a hand here?

**Comment by robsontenorio** [comment]
@dirtbikr  

Could you try this branch?

```
composer require robsontenorio/mary:dev-tags-fix-live
php artisan view:cache
```

**Comment by dirtbikr** [comment]
@robsontenorio that branch seems to fix the issue 👍 Really appreciate the help!

**Comment by robsontenorio** [comment]
@dirtbikr Nice! Will release soon.
