### ISSUE TITLE
[Bug]: Non-unique id console warning

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#242]
### MaryUI version

1.14.3

### daisyUI version

4.4.20

### Livewire version

3.3.4

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

Hi @robsontenorio,

if i use x-input in a foreach loop like this

```
@foreach ($users as $user)
    <div class="mb-2">
        <x-input label="Data profilazione" type="date" wire:model="users.{{$loop->index}}.profiled_at" required />
    </div>   
@endforeach
```
i have warnings in console for non unique id

[DOM] Found 2 elements with non-unique id #mary754157e57bbf8d1bbd52f75175be1838: (More info: https://goo.gl/9p2vKq) <input id=​"mary754157e57bbf8d1bbd52f75175be1838" placeholder=​" " class=​"input input-primary w-full peer" type=​"date" wire:model=​"users.0.profiled_at" required=​"required">​flex 
<input id=​"mary754157e57bbf8d1bbd52f75175be1838" placeholder=​" " class=​"input input-primary w-full peer" type=​"date" wire:model=​"users.1.profiled_at" required=​"required">​flex

**Comment by robsontenorio** [comment]
@fratsloos 

That MR shouldn’t solve this use case ?

**Comment by fratsloos** [comment]
@robsontenorio No, I'm afraid not. The changes to #230 only ensure that the ID always starts with a letter. Because the rest of the string is generated by serializing the object, it will always remain the same.

I think #213 would have prevented this, but that wasn't possible because of the `wire:key`.

**Comment by robsontenorio** [comment]
Got it. I should check this in next few days.

**Comment by robsontenorio** [comment]
@bucari What browser gives you that warning? I cant reproduce it.  Tried on Safari, Chrome e Firefox.

**Comment by bucari** [comment]
I tried Chrome and Firefox

**Comment by robsontenorio** [comment]
@bucari @fratsloos  Can you point me where I can activate this "duplicated warnings" settings on console? Mine does not show that and I cant see where do it.

**Comment by robsontenorio** [comment]
@bucari 

Could you please test this branch? Let me know if everything is ok.

```zsh
composer require robsontenorio/mary:dev-fix-input
php artisan view:clear
```

**Comment by bucari** [comment]
@robsontenorio it's ok for x-input but not for x-select
