### ISSUE TITLE
Update @uvarov.frontend/vanilla-calendar to vanilla-calendar-pro

### ISSUE THREAD

**Issue by uvarov-frontend** [robsontenorio/mary#244]
Hi, thanks for embedding my calendar into your wonderful library.
I worked on improving the code and did a complete refactoring. In the new version, the calendar has become even faster and takes up less space.
In addition, I renamed the calendar from [@uvarov.frontend/vanilla-calendar ](https://www.npmjs.com/package/@uvarov.frontend/vanilla-calendar) to  [vanilla-calendar-pro](https://www.npmjs.com/package/vanilla-calendar-pro), please, if possible, update the calendar to the current  [vanilla-calendar-pro](https://www.npmjs.com/package/vanilla-calendar-pro) version. Thank you!

**Comment by robsontenorio** [comment]
@uvarov-frontend Thanks for notifying me. Will take a look.
