### ISSUE TITLE
Only have ONE submenu open

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#245]
In your menu-component it is possible to open a submenu. this is fine.
But it is only possible, to open every submenu separate.
So if you have 6 sub-menus, you can open all 6. 
This results in very large menus.
Maybe it is possible to add a flag "unique" to the menu, so that it is only possible to open ONE submenu.

Means, if you open Submenu #2, then submenu #1 is closed and #2 is opened.

hope it is clear, what i mean...

**Comment by robsontenorio** [comment]
@vogelor 

Are you talking about this?
https://daisyui.com/components/menu/#collapsible-submenu

By default all submenus are independent from each other. I am afraid I cant change this.

**Comment by vogelor** [comment]
i am talking about this
https://mary-ui.com/docs/components/menu
and i see, you are using alpine. so can't you "catch" the actual opened menu and close it before you open the next one

like (pseudo)
```php
if (open) { 
open.toggle();
open = this;
)
this.toggle();
```

**Comment by vogelor** [comment]
this means, you have to add a (pseudo)
```php
<x-data = "open = null">
```
to the menu "root" component (the parent of each item)

**Comment by robsontenorio** [comment]
@vogelor 

I am focusing for now on some upcoming features. If you can please, send a PR about it.

**Comment by vogelor** [comment]
This has no priority (and i don't have it). it was only a idea - and i wrote it down to not forget it.

**Comment by robsontenorio** [comment]
Ok, closing for now.
