### ISSUE TITLE
Use NPM instead

### ISSUE THREAD

**Issue by hipoagencia** [robsontenorio/mary#247]
Hey! 

First of all, awesome job.
I'm trying to install using NPM, its possible?

Alrady tryed a few things, but withou success.

**Comment by robsontenorio** [comment]
@hipoagencia 

Mary does not ship any JS. Then does not matter what you use.

The NPM/Yarn stuff is for Tailwind/Daisy stuff.

Would be more helpful if you share what have you tried and the error itself.

**Comment by hipoagencia** [comment]
Let me explain all the path that i've done

My project already have Livewire instaled, so, i started with:

`composer require robsontenorio/mary`

And then i've instaled the Daisy like this:

`npm i daisyui`

Now, i inserted this in tailwind.config

`plugins: [require("daisyui")]`

The component style is woriking just fine.

Now i'm trying to make the component to work:

![image](https://github.com/robsontenorio/mary/assets/79876130/50424f96-6dfc-4825-ab2b-ecbef4df3df4)

**Comment by hipoagencia** [comment]
![image](https://github.com/robsontenorio/mary/assets/79876130/313b1f35-43d0-46cf-90f2-fab65e1f4cbd)


Found this error in console!
ps.: vi que é brasileiro. Não sei se prefere falar em português

**Comment by robsontenorio** [comment]
Keep in English to reach more people with same problem. 

I will add a note on Forms  docs. 

You need add Currency library like this. 
https://mary-ui.com/docs/components/input#currency

**Comment by hipoagencia** [comment]
Oh, you're right!

I didn't see that note.
Thanks for your help!
