### ISSUE TITLE
[Bug]: Table component

### ISSUE THREAD

**Issue by delacroix1983** [robsontenorio/mary#258]
### MaryUI version

1.17

### daisyUI version

4.5.0

### Livewire version

3.3

### What browsers are affected?

Safari

### What happened?

Hi,
Simple Table component is not working with the example. If the highlighted row deleted, then it is working fine.
Error: Undefined variable $__livewire
```
....
<div x-data="{
                    selection: @entangle($attributes->wire('model')),
```

```
@php
$keywords = App\Model\Keyword::where('user_id','=', $request->user()->id)->get();
    $headers = [
        ['key' => 'id', 'label' => '#'],
        ['key' => 'keyword', 'label' => 'Nice Name'],
    ];
@endphp
<x-table :headers="$headers" :rows="$keywords" striped @row-click="alert($event.detail.name)" />
```

Thank you

**Comment by robsontenorio** [comment]
It is not clear on your issue what is the problem.

Make sure to remove some surround noise code to try to spot the problem. There is no `wire:model` usage on simple table example.

**Comment by delacroix1983** [comment]
Thank you for the fast response.
Tried out the example with my own model and it gives me this error. It is a fresh Laravel install with only Mary-UI.
What surround noise code should I remove?

**Controller:**
`<?php
namespace App\Http\Controllers;

use App\Models\Keyword;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;
use DB;

class KeywordController extends Controller
{
    /**
     * Display the user's keyword list
     */
    public function list(Request $request)
    {
        return view('keywords.list');
    }

}`

**Blade file:**
`@php
$keywords = App\Models\Keyword::where('user_id','=', 1)->get();
    $headers = [
        ['key' => 'id', 'label' => '#'],
        ['key' => 'keyword', 'label' => 'Nice Name'],
    ];
@endphp

<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <x-table :headers="$headers" :rows="$keywords" striped />
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
`

<img width="1400" alt="image" src="https://github.com/robsontenorio/mary/assets/104434446/9e6f735b-9946-4ea2-8eba-66eb8633fcaf">

**Comment by robsontenorio** [comment]
@delacroix1983 

MaryUI requires Livewire 3 and its components approach. It does not work with pure Laravel.

**Comment by delacroix1983** [comment]
Apology, fresh laravel install with the required components. Did I missed any component?

package.json
```
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "autoprefixer": "^10.4.16",
        "axios": "^1.6.1",
        "daisyui": "^4.5.0",
        "laravel-vite-plugin": "^1.0.0",
        "postcss": "^8.4.33",
        "tailwindcss": "^3.4.1",
        "vite": "^5.0.0"
    }
}

```

composer.json
  ```
  "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "^3.3",
        "livewire/volt": "^1.6",
        "robsontenorio/mary": "^1.17"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
```

**Comment by robsontenorio** [comment]
I mean maryUI only works inside Livewire components. Not inside pure blade files.

If you are a new comer on Livewire world I recommend to check Livewire docs, to get started.

```
// Table will work inside this component 
php artisan make:livewire test1
```

**Comment by delacroix1983** [comment]
Thank you.
