### ISSUE TITLE
[Bug]: sidebar menu item links active class set incorrectly

### ISSUE THREAD

**Issue by gottaloveit** [robsontenorio/mary#262]
### MaryUI version

1.17

### daisyUI version

4.5.0

### Livewire version

3.3

### What browsers are affected?

Firefox, Chrome, Microsoft Edge

### What happened?

In the sidebar, I have 2 test links:
 
/owner
/owner/listings

Everything ok when I am on /owner however on /owner/listings, both have active class set

![Screenshot 2024-01-10 140637](https://github.com/robsontenorio/mary/assets/316801/07311942-9889-4ca3-a9ed-cfebabf9e9f1)

**Comment by robsontenorio** [comment]
@gottaloveit 

Can I see the code for this menu? Specially the link `property`

**Comment by gottaloveit** [comment]
I think the startsWith function is causing the issue

```php
                <x-menu-item title="Home" icon="o-home" link="{{ route('owner.dashboard') }}" />
                <x-menu-item title="Messages" icon="o-envelope" link="###" />
                <x-menu-item title="My RVs" icon="mdi.rv-truck" link="{{ route('owner.listing.index') }}" />
```

routes
```php
   Route::prefix('owner')->group(function() {
        Route::name('owner.')->group(function() {

            Route::get('/', function () {
                return view('pages.owner.dashboard');
            })->name('dashboard');

            Route::prefix('listings')->group(function () {
                Route::name('listing.')->group(function () {

                    Route::get('/', function () {
                        return view('pages.owner.listing-index');
                    })->name('index');

                    Route::get('/create', function () {
                        return view('pages.owner.listing-create');
                    })->name('create');

                    Route::get('/update/{listing}', function (Listing $listing) {
                        return view('pages.owner.listing-update', ['listing' => $listing]);
                    })->name('update');
                });
            });

        });
    });
```

so the code produces links like:
/owner
/owner/listings

**Comment by gottaloveit** [comment]
shouldn't the check below be enough to set active class?  I mean, you want definite match on url and link right?  why have a fallback if it does not match completely, to in this case, match it on prefix ?

```php
if ($link == $route) {
            return true;
        }
```

**Comment by robsontenorio** [comment]
@gottaloveit 



I suggest to use different base name for each menu. 

- `/owners`
-  `/listings` or `/owners-listings` ...
 

**Your PR will break current behavior.** 

<hr />
<hr />
<hr />

<img width="885" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/c8ea5dcc-e356-4648-bcb0-2d746988b6c1">

**Comment by gottaloveit** [comment]
I get what you are saying, back in the day of us having to route every single request.  But this library is written especially for Livewire, right?  Wouldn't those links you mentioned be handled by wire.click and stuff?  This is what my approach is, so the main group of functionality in this case /owner/listings brings up a page that has a bunch of links to livewire components, routing doesn't touch them, so the active link won't change.

**Comment by gottaloveit** [comment]
but no worries if you dont want to change it, ill just manually add a check on each one and add classes

**Comment by robsontenorio** [comment]
It can be added if it does not break current features described on docs. Could you check it?

**Comment by gottaloveit** [comment]
Here's in essence what my use case would look like, if I am creating a "listing" using a url like /owner/listings/create

![Screenshot 2024-01-10 145718](https://github.com/robsontenorio/mary/assets/316801/4306cece-e62d-49dd-83b3-3de2c69c76d1)

breaking the urls into a structure of dashes instead of forward slashes, to me, means more chance of coding typos considering I couldn't take advantage of Laravel Routing prefix groups, which is nice to use..  I don't know the right answer, because this seems to be mixing the old and the new in terms of URL paths and Livewire not even using url paths to an extent.  

What about maybe then changing the comparison to using the route name properties?  Those would never change, even if you add variables to the path using the correct syntax.

**Comment by robsontenorio** [comment]
@gottaloveit  I mean could you check if your PR will not break another use cases?

Your PR solves this case

```
/owner
/owner/listings
```

But, on same PR,  if you enter on `/owner/listings` and click on some item on page to navigate to `/owner/listings/24` ... I think it will not hilight the `/owner/listings` menu anymore .


The original implementation cover that cases were you navigate on sub routes and **keep base menu hilighted**. If you manage this PR to get this working I am good to merge.

**Comment by gottaloveit** [comment]
I updated the PR .. adding check by routeName .. in order to use, the menuitems would be like:

```php
                <x-menu-item title="Home" icon="o-home" route="owner.dashboard" />
                <x-menu-item title="Messages" icon="o-envelope" link="###" />
                <x-menu-item title="My RVs" icon="mdi.rv-truck" route="owner.listing.index" />
                <x-menu-item title="Create Listing" icon="mdi.rv-truck" route="owner.listing.create" />
```

this keeps existing functionality by using link property if desired or route property for routeName check

**Comment by robsontenorio** [comment]
Thanks ! Will try it soon.

**Comment by robsontenorio** [comment]
@gottaloveit 

I have tried it. 

- ✅  **Current:** It does not break current behavior for "link approach" on root level and sub levels.
- ✅  **New:**  It works for "route name approach" on root level.
- ☑️  **New:** But, it **won't** work for "route name approach" for sub levels as "link approach".

<img width="258" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/8a2d3f9f-384f-4525-8727-2195df8a8b0a">

**Comment by robsontenorio** [comment]
Hey, for now I am closing this, as I can't realize for now how to have equivalent feature for "route approach".
For now just do as you suggested "manually add a check on each one and add classes".
