### ISSUE TITLE
Possibility to set an extra error-key

### ISSUE THREAD

**Issue by vogelor** [robsontenorio/mary#266]
In your components (for example input) you set:

```php
    public function modelName(): ?string
    {
        return $this->attributes->whereStartsWith('wire:model')->first();
    }
```

and then you wrote:

```php
                <!-- ERROR -->
                @if(!$omitError && $modelName())
                    @error($modelName())
                        <div class="text-red-500 label-text-alt p-1">{{ $message }}</div>
                    @enderror
                @endif

```

This means, you show a error only, when the key of the error corresponds to the name of the wire:model.

Jetstream for example has some livewire-Components. there you can see:
```php
    public $state = [
        'current_password' => '',
        'password' => '',
        'password_confirmation' => '',
    ];
```
means, the wire:model is (for example) `state.current_password` but - and this is the problem, the error has the key `current_password`.
this means the error message is not rendered, because you are looking for `state.current_password` and the jetstream livewire component sets `current_passwort`.

Maybe you can add a additional parameter called `error-key` and then do (pseudo)

```php
$errorkey = $errorKey ?? modelName;
```

**Comment by robsontenorio** [comment]
@vogelor 

The current implementation just works exactly the same Jetstream.


<img width="782" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/5caa2ee0-ad94-44fb-80b6-ec739c135af9">


<hr />

<br>

```blade
<?php

use Livewire\Attributes\Rule;
use Livewire\Volt\Component;

new class extends Component {

    #[Rule('required|current_password:web')]
    public string $current_password = '';

    #[Rule('required|confirmed')]
    public string $password = '';

    #[Rule('required')]
    public string $password_confirmation = '';

    public function save()
    {
        $this->validate();
    }
}

?>

<div>
  <x-errors />
  <x-form wire:submit="save">
      <x-input label="Current password" wire:model="current_password" />
      <x-input label="New password" wire:model="password" />
      <x-input label="New password confirm" wire:model="password_confirmation" />

      <x-button type="submit" label="Save" spinner="save" />
  </x-form>
</div>
```
