### ISSUE TITLE
Timeline customization

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#274]
hi @robsontenorio 
it would be nice if the timeline could be more customizable, like bullet/title color and size

Thank you

**Comment by robsontenorio** [comment]
@bucari 

We don't know exactly what devs wants to customize, once we can rely on one single `class=""` attribute. It will become complex if we start to add extra attributes to customize each of these styles.

So, I suggest you to simple hack CSS for your use case.

**Comment by bucari** [comment]
@robsontenorio I agree, but I can't customize it even with the class attribute

**Comment by robsontenorio** [comment]
I mean deeper customization must be done on `app.css`.

![image](https://github.com/robsontenorio/mary/assets/118955/24770b1c-1d81-4eb0-b671-c26b9a0f1195)


To make sure things will be consistent, name the target elements.

```css
#my-timeline div.font-bold.mb-1 {
    @apply text-red-500
}
css

**Comment by bucari** [comment]
this way i can't customize dinamically, for example a green bullet when a that point is passed

**Comment by robsontenorio** [comment]
I will figure out a way to add these new params.
