### ISSUE TITLE
[Bug]:  Rich Text

### ISSUE THREAD

**Issue by alexnogueirasilva** [robsontenorio/mary#278]
### MaryUI version

1.20

### daisyUI version

4.4.10

### Livewire version

3.4.1

### What browsers are affected?

Chrome

### What happened?

"Can't get it to work, I already made the account, replaced it with my API key, and downloaded the library, but it still stays on this screen and with this error in the console."

![image](https://github.com/robsontenorio/mary/assets/29835529/fe747ff6-1ded-4d88-bd5a-5e49247aecb5)

**Comment by robsontenorio** [comment]
@alexnogueirasilva 

First make sure it works with cloud setup as described on maryUI docs. 

Also make sure it works on normal page, and not in a drawer. 

After this we can further investigate it.

**Comment by alexnogueirasilva** [comment]
I used it in this way and outside of the Drawer, but it still doesn't load the library.



![image](https://github.com/robsontenorio/mary/assets/29835529/3e7ebca1-c700-4348-a920-407109b24605)
![image](https://github.com/robsontenorio/mary/assets/29835529/935cf08e-e9eb-4c70-b1f5-1163dd3f9196)

**Comment by robsontenorio** [comment]
Have you authorized your local domain name on tinyMCE dashboard?

**Comment by alexnogueirasilva** [comment]
@robsontenorio yes, localhost is approved in Approved Domains, localhost is by default approved

![image](https://github.com/robsontenorio/mary/assets/29835529/106688db-4fe5-4d61-812f-284a6131a269)

**Comment by robsontenorio** [comment]
Are you able to make vanilla tinyMCE work ? Not maryUI component.

https://www.tiny.cloud/docs/tinymce/latest/cloud-quick-start/

**Comment by alexnogueirasilva** [comment]
I will check

**Comment by alexnogueirasilva** [comment]
@robsontenorio With Vanila it works normally

![image](https://github.com/robsontenorio/mary/assets/29835529/081f1c42-7bbf-4324-9f8b-521a60dd35ff)

**Comment by robsontenorio** [comment]
Share the code you are using for x-editor

**Comment by alexnogueirasilva** [comment]
```blade

<div>
    {{-- The best athlete wants his opponent at his best. --}}
    Hello World

    <textarea id="mytextarea">Hello, World!</textarea>
    <x-editor label="Description" hint="The full product description"/>
</div>


```

**Comment by alexnogueirasilva** [comment]
After analyzing the situation, @robsontenorio  realized that the `wire:model` was missing.

**Comment by alexnogueirasilva** [comment]
Complementing the property, the `wire:model` cannot receive `null` by default as this will generate an error in the component.

Instead of 
```php
    public ?string $content = null; 
```

use this 

```php
    public ?string $content = '';
```
