### ISSUE TITLE
x-choices scrollbar

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#28]
Can i suggest to use overflow-y-auto instead of overflow-y-scroll here

```
                        <!-- OPTIONS -->
                        @if(count($options) || $noResultText)
                            <div class="absolute w-full bg-base-100 mt-2 z-10 pb-0.5 border border-base-300 shadow-xl cursor-pointer rounded-lg overflow-y-scroll max-h-64">
```
with overflow-y-scroll scrollbar appears even if there is no need

**Comment by robsontenorio** [comment]
Agree. Will take look on next release.

**Comment by bucari** [comment]
@robsontenorio i have customized DaisyUI input component  height adding 

```
.input {
    @apply h-10;
}
.select {
    @apply h-10;
}
```

in app.css but it doesn't affect x-choices, how can i change its height?
