### ISSUE TITLE
[Bug]:  Button with download link will open file in browser, instead download it.

### ISSUE THREAD

**Issue by andistywn** [robsontenorio/mary#282]
### MaryUI version

1.20

### daisyUI version

4.6.0

### Livewire version

3.0

### What browsers are affected?

Firefox, Chrome

### What happened?

Hi, I hope you're doing well

I have problem with button. There is my code:
When i click the button, it will open the file in browser.
```blade
<x-button label="Download Formulir" class="btn-info" link="{{ route('docx-download') }}" />
```
preview:
![image](https://github.com/robsontenorio/mary/assets/115723066/39ec1d56-3674-41a2-937f-1dc6cff5a6d6)

But, it done as expected when use link or direct acces to url
```blade
<a href="{{ route('docx-download') }}" class="btn btn-info">Download formulir</a>
```
preview:
![image](https://github.com/robsontenorio/mary/assets/115723066/02fc5dbf-d154-4820-84eb-39cd010f9a2d)

When i add `wire:click="download"`, then it will do both: download and open.
```blade
<x-button label="Download Formulir" class="btn-info" link="{{ route('docx-download') }}" wire:click="download" />
```

Thank you.

**Comment by robsontenorio** [comment]
- Try to add the `external` property. 
- Or `no-wire-navigate ` property


```html
<x-button label="Download Formulir" class="btn-info" link="{{ route('docx-download') }}"  external />
<x-button label="Download Formulir" class="btn-info" link="{{ route('docx-download') }}"  no-wire-navigate />
