### ISSUE TITLE
Mary Table - Create option for controlling cell class

### ISSUE THREAD

**Issue by joaoclobocar** [robsontenorio/mary#286]
It would be valuable if Table component give the programmer the ability of controling cell class.

It will be useful in the case of screen size controlling the visibility of a column.

For example, if we have this headers.

```php
    public $headers = [
        ['key' => 'name', 'label' => 'Name', 'class' => ''],
        ['key' => 'city', 'label' => 'City', 'class' => 'hidden sm:table-cell'],
        ['key' => 'address', 'label' => 'Address', 'class' => 'hidden lg:table-cell'],
    ];
```
Currently, by existence of 'hidden' string on header class, the corresponding cell will be hidden, even if the title is displayed.

My suggestion is to create a key on $headers array to give full control to the cell visibily and properties:

```php
    public $headers = [
        ['key' => 'name', 'label' => 'Name', 'class' => ''],
        ['key' => 'city', 'label' => 'City', 'class' => 'hidden sm:table-cell', 'cell_class' => 'hidden sm:table-cell', ],
        ['key' => 'address', 'label' => 'Address', 'class' => 'hidden lg:table-cell', 'cell_class' => 'hidden sm:table-cell'],
    ];
```

**Comment by robsontenorio** [comment]
It is a good idea. I will work on this and solve #285 also.

**Comment by joaoclobocar** [comment]
For controlling visibility, I think keeping the header class in cell class would be enough ('same_cell_class' => true, 'keep_header_class' => true).

May be an array of classes for cell decoration could be switched by the key name plus some suffix (address_class, address_switch, etc) and merged to final class. It could help to avoid some scoping.

```PHP
    public $headers = [
        ['key' => 'name', 'label' => 'Name', 'class' => ''],
        ['key' => 'city', 'label' => 'City', 'class' => 'hidden sm:table-cell', 'cell_class' => 'hidden sm:table-cell', ],
        ['key' => 'address', 'label' => 'Address', 'class' => 'hidden lg:table-cell', 'same_cell_class' => true,
          'cell_decoration' => ['font-bold text-red-500', 'italic text-green-500']
        ],
    ];

    public $users = [
        ['name' => 'Joao', 'city' => 'Sao Paulo', 'address' => 'Av. Um, 249', 'address_class' => 0], // address in bold, red
        ['name' => 'Renata', 'city' => 'Campinas', 'address' => 'Avenida Dois, 249', 'address_class' => 1], // address in italic, green
    ];
```

Something like that.

**Comment by robsontenorio** [comment]
Hey @joaoclobocar ,

Follow and comment https://github.com/robsontenorio/mary/pull/300


Appreciate if you could test that branch.
