### ISSUE TITLE
[Bug]: Toggle wire:model does not trigger updated

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#287]
### MaryUI version

1.20.1

### daisyUI version

4.6.1

### Livewire version

3.4.4

### What browsers are affected?

Chrome

### What happened?

Heya, I'm using the Toggle component (https://mary-ui.com/docs/components/toggle) like this

```php
class ArticleShop extends Component
{
    public $article;

    public $status;

    public function mount(Article $article)
    {
        $this->article = $article;

        $this->status = $article->is_shop_enabled;
    }

    public function render()
    {
        return view('livewire.articles.article-shop');
    }

    public function updatedStatus($status)
    {
        dd($status);
        $this->article->is_shop_enabled = $this->status;
        $this->article->save();
    }
}
```

```html
{{ $status }}
<x-toggle :label="__('Synchronisation mit Online Shop')" wire:model="status" right tight />
```

Toggling the switch doesn't do anything, not even triggers `updatedStatus()` - any ideas?

<img width="375" alt="Screenshot 2024-02-05 at 19 58 41" src="https://github.com/robsontenorio/mary/assets/13555377/30de05e6-34b8-4d15-829f-aec5d4f58ffc">

<img width="343" alt="Screenshot 2024-02-05 at 19 58 44" src="https://github.com/robsontenorio/mary/assets/13555377/f0d959c2-1590-4dff-b266-ffb5773d6477">

Thank you!

**Comment by lucas-davi** [comment]
Hello @pboese!

try this:

`<x-toggle :label="__('Synchronisation mit Online Shop')" wire:model.live="status" right tight />`

add to **.live** modifier for **wire:model**

**Comment by pboese** [comment]
@lucas-davi @robsontenorio thanks a lot! `.change` and `.live` both work as expected. Cheers!
