### ISSUE TITLE
Handle validation error for array model.

### ISSUE THREAD

**Issue by lucas-davi** [robsontenorio/mary#288]
### MaryUI version

1.20.1

### daisyUI version

3.9.3

### Livewire version

3.4.4

### What browsers are affected?

Chrome

### What happened?

Not showing validation error in x-tags input.

```php
public function rules()
{
    return [
        'tags.*' => 'max:255'
    ];
}
```
The same validate is shown in the error bag.
![image](https://github.com/robsontenorio/mary/assets/60628727/16ee798b-8d50-48cf-a3be-49d63e6c885a)

**Comment by robsontenorio** [comment]
@lucas-davi 

On real world tags should be short words, right? But, I will add this extra validation error check when using '*' notation.

**Comment by robsontenorio** [comment]
@lucas-davi 

It will be fixed on next release.
