### ISSUE TITLE
 Error when installing maryui in a project that has "laravel/breeze"

### ISSUE THREAD

**Issue by jjanampa** [robsontenorio/mary#289]
### MaryUI version

1.20.1

### daisyUI version

4.6.2

### Livewire version

3.4.4

### What browsers are affected?

Chrome

### What happened?

Error when installing maryui in a project that has "laravel/breeze".

In the files "resources/views/livewire/welcome.blade.php" and "resources/views/components/layouts/app.blade.php", components are called without the "mary-" prefix.

![image](https://github.com/robsontenorio/mary/assets/1957176/7c819d68-dece-484f-8de8-9d2fc50a03aa)

I have renamed all the component calls but I get another error:

![image](https://github.com/robsontenorio/mary/assets/1957176/9c20d3ca-0b7d-48c0-881c-20c57cffb59b)

**Comment by dormammuuuuu** [comment]
When using a starter kit, it's much better to have a prefix in the Mary config.

**Comment by robsontenorio** [comment]
@jjanampa All the examples on docs does not have prefix. 

So , if you copy examples from docs you have to add a component prefix, according to your “config/mary.php”

On breeze and Jetstream By default is “x-mary-“

**Comment by holiq** [comment]
@robsontenorio you right, I found the prefix marry on the config, thanks

**Comment by jjanampa** [comment]
Thank you very much for the response @robsontenorio, congratulations for the good work, I am testing maryui in Laravel 11.

**Comment by robsontenorio** [comment]
This is expected. 

As breeze/jetstream has their own boilerplate/components/templates, the installer won’t copy maryUI starter template. Because maryUI is not the main part on your project, but breeze/jetstream. 

And officially maryUI was not tested on L11, because it was not released.
