### ISSUE TITLE
LOG.warning on string

### ISSUE THREAD

**Issue by andistywn** [robsontenorio/mary#291]
### MaryUI version

1.20.1

### daisyUI version

4.6.2

### Livewire version

3.4

### What browsers are affected?

Firefox

### What happened?

Hi, I hope you well.

I got two types warning message like this in my current project

```php
LOG.warning: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in D:\TestMary\storage\framework\views\cb062ddd128f1013fd17eeb4ff5fcd4b.php on line 1
```
and
```php
LOG.warning: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in D:\TestMary\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 268
```
Then, i try to create new project fresh laravel+maryUI
The warning appears like this:

![mui1](https://github.com/robsontenorio/mary/assets/115723066/bcf07662-d10f-4449-93d6-0a58b9c8bde6)

I try figure out what makes such as warning. I fix a little in:
```php
vendor\robsontenorio\mary\src\View\Components\Button.php
and
vendor\robsontenorio\mary\src\View\Components\Icon.php
```
like this

![mui3](https://github.com/robsontenorio/mary/assets/115723066/262daedd-2cfe-4726-9f2a-fb267b1a6fed)

Result: the first warning messages gone:

![mui2](https://github.com/robsontenorio/mary/assets/115723066/56747420-65e8-4346-8c6b-5a4f01eafa1b)

There still remain second warning message. 
I try to find out what does trigger the second warning by isolate (commenting)  the components one by one on `app.blade` and `welcome.blade`. Yes, it has something to do with components (e.g `<x-menu-item>` on app.blade, or `<x-table>` on welcome.blade) but I still don't know how to fix it.

Thank you..

p.s.
I have tried editing (even though it's not the right solution ) file `vendor\laravel\framework\src\Illuminate\Support\Str.php` by adding a line to check whether `$haystack/$needle = null` or not. The result: all remaining messages are gone. 😄 

```php
public static function contains($haystack, $needles, $ignoreCase = false)
{
    //here
    if ($haystack === null) {
        return false;
    }
    
        if ($ignoreCase) {
        $haystack = mb_strtolower($haystack);
    }    
    
    if (!is_iterable($needles)) {
    $needles = (array)$needles;
    }
    
    foreach ($needles as $needle) {
//and here
    if ($needle === null) {
            continue;
        }

        if ($ignoreCase) {
        $needle = mb_strtolower($needle);
            }

        if ($needle !== '' && str_contains($haystack, $needle)) {
        return true;
        }
    }
    return false;
   }
```

**Comment by robsontenorio** [comment]
Thanks @andistywn 

We should replace “strlen” , because it is deprecated. I will give a try later.
