### ISSUE TITLE
Access the $loop variable in the Table component

### ISSUE THREAD

**Issue by aztekrw** [robsontenorio/mary#292]
Want to be able to identify the first and last table rows so I can change the buttons in the actions for these etc.

Thank You

**Comment by aztekrw** [comment]
get: Undefined variable $loop if I pass it without quotations, which is understandable because the variable does not exist outside the component and now we are trying to pass it into the component.

get: syntax error, unexpected double-quote mark, expecting amp or "&" or variable _if I pass it as a quoted string.

What I hacked in was adding a new public variable $myloop to the Table class and then setting that variable to the $loop where I needed it in Table.php. Then accessing it with " @if ($this->myloop->first) "

**Comment by robsontenorio** [comment]
Hey @aztekrw  ,

Follow and comment https://github.com/robsontenorio/mary/pull/300


Appreciate if you could test that branch.

**Comment by aztekrw** [comment]
Thank you very much.

It is 100% for me
