### ISSUE TITLE
Horizontal menu ?

### ISSUE THREAD

**Issue by davidcabcab** [robsontenorio/mary#296]
Hi,
any chance to get the vertical menu(https://mary-ui.com/docs/components/menu) 
![list](https://github.com/robsontenorio/mary/assets/153238958/8c2856f0-3e22-4c68-a942-b29c17843e44)

become 
![inline](https://github.com/robsontenorio/mary/assets/153238958/3fde40b2-fba9-48cf-87e1-6f686fef9ca8)

?

I tried to edit the Menu.php component and eventually got a few hundreds errors 🥲

**Comment by robsontenorio** [comment]
Menu is supposed to be vertical. Do you want a suspended menu or a just a app navbar?

**Comment by robsontenorio** [comment]
Here is the contribution guided.

https://mary-ui.com/docs/contributing

If you are building the main app navbar like this ...

<hr />

<img width="1424" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/840dfee4-e84f-42bf-a49c-b9854ce1cdce">

<hr />


... just use Tailwind flex classes and place some buttons.

```html
<div class="flex gap-3">
    <x-button ... class="btn-host btn-sm" />
    <x-button ... class="btn-host btn-sm" />
    <x-button ... class="btn-host btn-sm" />
</div>

**Comment by davidcabcab** [comment]
Thank you !

Le mer. 14 févr. 2024 à 19:02, Robson Tenório ***@***.***> a
écrit :
