### ISSUE TITLE
[Bug]: Table component headers not theme compatible

### ISSUE THREAD

**Issue by IamSAB** [robsontenorio/mary#302]
### MaryUI version

1.18

### daisyUI version

4.6

### Livewire version

3.3

### What browsers are affected?

Firefox

### What happened?

![grafik](https://github.com/robsontenorio/mary/assets/8931240/dc32e9bf-72f7-4e43-bf34-9d367a025a2e)
![grafik](https://github.com/robsontenorio/mary/assets/8931240/ac0ddfcb-8d5a-4cff-b2ab-921781826a8a)

The table component uses a fixed text color for table headers `text-black dark:text-gray-200` .
However, daisyUI is using CSS variables for themes not `dark:`, what allows for multiple themes.
[Theming with DaisyUI](
https://github.com/saadeghi/daisyui/discussions/640)

Overall, I would propose to not use any Tailwind colors (which are not themed) in components (e.g. text-gray-200) but classes used in DaisyUI (e.g bg-neutral, text-primary, text-content etc). If you do that consisten, all components are themed.
Whoever does not used DaisyUI and only Tailwind could then also style them using @apply.
This is for most components the case, but for some not, mainly defining text colors.

What do you think?

**Comment by robsontenorio** [comment]
@IamSAB 

Are you able to send a PR to this specific use case ?

**Comment by KozSuper** [comment]
Using this can be applied to multiple dark themes.
```js
darkMode: ['variant', [
      '@media (prefers-color-scheme: dark) { &:not(.light *) }',
      '&:is(.dark *)',
    ]]
```

**Comment by robsontenorio** [comment]
That is solved on latest versions ...

**Comment by DE-dylan-lauzon** [comment]
This isn't fixed with the custom themes from DaisyUI, the bug is visible when using the aqua theme that is used by the custom theme changer in the docs:

https://github.com/user-attachments/assets/d586b9fc-c2b9-4073-bacf-abc6c1ebca2d

Only with the default light and dark themes does the table header respect the theme, from what I can tell.
