### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by IamSAB** [robsontenorio/mary#303]
I prefer markdown editor for their simplicity over rich text editors. 

Would be great if mary could add the [easy markdown editor](https://github.com/Ionaru/easy-markdown-editor) as available editor.

**Comment by robsontenorio** [comment]
A markdown editor is a good candidate. Are you able to send a draft PR ?

**Comment by IamSAB** [comment]
Currently not, but probably try first on my own and post then some code samples here.

**Comment by robsontenorio** [comment]
Released. Enjoy it !
