### ISSUE TITLE
Conditionally disabled attribute for x-input

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#305]
Heya, it's me again ;-) 

I'd love to have a way to conditionally enable/disable `<x-input>` elements. 

In standard blade components it is quite easy, e.g.

```html
<input type="text" @if($something) disabled @endif />
```

But with the component it sadly doesn't work this way. My idea would be to allow a value for the attribute, e.g.

```html
<x-input :disabled="$something" />
```

**Comment by robsontenorio** [comment]
Hi,

This should work. Make sure “$somenthing” returns a Boolean. 

```
<x-input :disabled="$something" />
```

**Comment by pboese** [comment]
Oh... awesome, thanks!
