### ISSUE TITLE
disabled attribute on x-input should also include prefix and suffix

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#306]
Heya, I've got another. It would be amazing if the `disabled` attribute would also render a `prefix` and `suffix` as disabled. Currently a disabled `x-input` looks a bit odd because the *fix still has a border:

<img width="568" alt="Screenshot 2024-02-20 at 16 17 35" src="https://github.com/robsontenorio/mary/assets/13555377/d032320d-493d-4563-902d-cb0ff3ed565e">

**Comment by robsontenorio** [comment]
It is fixed on latest release.
