### ISSUE TITLE
More fine-grained control of text style on choices component (and possibly others)

### ISSUE THREAD

**Issue by hamannjames** [robsontenorio/mary#308]
I am finding I want more control of the text size, color, etcetera, with the choices component, specifically the selection options. I am finding on certain themes the color is way too light. The styling seems set at `text-primary` when ideally a `class` attribute could be passed to the component or something similar, like `textClass` that is spread into the default classes. Is this something you are up for a PR on, or something already in the works?

**Comment by robsontenorio** [comment]
Have you tried Choices slots ? It is available on docs.

**Comment by hamannjames** [comment]
That does the trick. thanks!
