### ISSUE TITLE
[Bug]: <x-tabs wire:model="selectedTab"> not binded to backend ?

### ISSUE THREAD

**Issue by davidcabcab** [robsontenorio/mary#309]
### MaryUI version

1.21

### daisyUI version

4.7.2

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

`<x-tabs wire:model="selectedTab">
`

doesn't update the backend $selectedTab variable, even if declared publicly in the livewire class (public $selectedTab;)

I can't see any XHR request when changing tab, nor can't get the $selectedTab value in the backend with 

```
public function updatedSelectedTab($value){
     Log:debug($value);
}
```

**Comment by robsontenorio** [comment]
@davidcabcab 

This is about Livewire, not maryUI.

With you wanna live change try `wire:model.live`

**Comment by davidcabcab** [comment]
Ok thanks ! 

But still, I can't get how to properly call a livewire function on tab change. 

And indeed I'm not clear if it's a livewire  or Mary concern, sorry about that =/

**Comment by robsontenorio** [comment]
This code works:

```php
public function updatedSelectedTab($value)
{
     dd($value);
}
```

Notice `.live` here.

```html
<x-tabs wire:model.live="selectedTab">
```
