### ISSUE TITLE
[Bug]: x-choice strangely duplicates item before being removed

### ISSUE THREAD

**Issue by davidcabcab** [robsontenorio/mary#316]
### MaryUI version

1.21

### daisyUI version

4.7.2

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

When I click on the "x" to delete a tag, it's duplicated first, then when I re-click the "x" both are removed.

No console error.

https://github.com/robsontenorio/mary/assets/153238958/545884b9-81af-4a8b-97cd-e4c8bc04f971

```
class Test extends Component
{
    public $selectedTags = [1,2];
    public $options = [];

    public function mount()
    {
        $this->options = [
            ['id' => '1', 'name' => 'first'],
            ['id' => '2', 'name' => 'sec'],
            ['id' => '3', 'name' => 'third']
        ];
    }

    public function render() {

        return view('livewire.batch')
            ->layout('layouts.layoutMainApp');

    }
}
```

```
<div>
    <x-choices-offline label="Tags" wire:model="selectedTags" :options="$options" searchable />
</div>
```

**Comment by robsontenorio** [comment]
Your `$options` keys  must have the same type you have on `public $selectedTags = [1,2]`.

This case is a INTEGER.


**Before**

```
['id' => '1', 'name' => 'first'],
```


**After**
```
['id' => 1, 'name' => 'first'],
```

**Comment by davidcabcab** [comment]
Awesome, this was the fix indeed.

Thank you !

(at some point I'll find a real bug, not a mistake on my side... )
