### ISSUE TITLE
Adding a new tag inside x-choice (like x-tags) ?

### ISSUE THREAD

**Issue by davidcabcab** [robsontenorio/mary#317]
This feature is very cool on the x-tags component, it could be great in x-choices as well.

It's just an idea

<img width="791" alt=" addtag" src="https://github.com/robsontenorio/mary/assets/153238958/4584e4fe-c202-4268-a300-1b6d3949d321">

**Comment by robsontenorio** [comment]
The components serves to different purposes.

- **Tags**: there is no table or keys, the things are bonded to a flat array in memory.
- **Choices**: there is a table and business rules, so we can not infer how to add a new item on the fly.
