### ISSUE TITLE
is there any option for <textarea> in Mary UI?

### ISSUE THREAD

**Issue by groxw** [robsontenorio/mary#32]
I would like to use textarea, in docs, there's no textarea, how we can fix it?

**Comment by robsontenorio** [comment]
@groxw If you are able I would accept a MR

**Comment by groxw** [comment]
sorry I can't do that yet, because I've only used livewire this year, I am still learning about livewire hehe

**Comment by robsontenorio** [comment]
@groxw see https://mary-ui.com/docs/components/textarea#textarea

thanks @essamamdani
