### ISSUE TITLE
Hide offline choices on load

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#320]
Hi Rob!

We're having an "issue" with all offline choices: On page load all choices are visible which leads to an annoying flicker. Would it be possible to get rid of this behaviour (or is there an easy hack)? It happens in all projects. Code to reproduce below.

https://github.com/robsontenorio/mary/assets/13555377/6185cbc0-e55c-493f-8652-613609874dde

**Example**

```blade
@php
    $q = null;

    $choices = [];

    for ($i = 0; $i < 1000; $i++) {
        $choices[] = [
            'id' => $i,
            'name' => "Choice $i",
        ];
    }
@endphp

<x-mary-choices-offline label="Choices" wire:model="q" :options="$choices" single />
```

**Comment by robsontenorio** [comment]
Is this a brand new project ? Can you reproduce this issue on online Mary docs site ?

It seems there is some extra CSS on your side. Because the input border should be hidden. 

This “flash” issue is commonly caused by some “x-cloak” CSS placed somewhere on your code.

**Comment by pboese** [comment]
@robsontenorio it happens if I insert the code above into a brand new laravel project with only mary installed and setup (I added it to `resources/views/livewire/users/index.blade.php`). Same behaviour. The more items are in your array, the longer the list is visible on load. The element in this video has 5000 items to make it more visible:


https://github.com/robsontenorio/mary/assets/13555377/7cdb317e-6ca9-4511-8ca9-d9b49ed570a2

**Comment by robsontenorio** [comment]
Please, give a try on https://github.com/robsontenorio/mary/pull/323

**Comment by pboese** [comment]
@robsontenorio thanks so much, this fixes it!
