### ISSUE TITLE
[Bug]: Disabled Choices are still usable

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#321]
### MaryUI version

1.23

### daisyUI version

4.7.2

### Livewire version

3.4

### What browsers are affected?

Firefox, Chrome

### What happened?

In all our projects we can still use disabled choices. Example code below.

https://github.com/robsontenorio/mary/assets/13555377/bad474e5-1d31-47ac-b0f4-abcfa7ea56ba

**Example**

```blade
@php
    $q = null;

    $choices = [
        [
            'name' => 'Choice 1',
            'id' => 'choice1',
        ],
        [
            'name' => 'Choice 2',
            'id' => 'choice2',
        ],
        [
            'name' => 'Choice 3',
            'id' => 'choice3',
        ],
    ];
@endphp
<x-mary-choices-offline label="Choices" wire:model="q" :options="$choices" single disabled />
```

**Comment by robsontenorio** [comment]
Please, give a try on https://github.com/robsontenorio/mary/pull/323

**Comment by pboese** [comment]
@robsontenorio thanks so much, this fixes it!
