### ISSUE TITLE
Closing modal doesn't trigger Livewire updated()

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#325]
Heya, it's probably a rookie issue but when using the modal component and I close a modal using the ESC key or clicking the backdrop, there is no Livewire request to change the bound variable (e.g. `$showModal`) in the background. So I seem to have no way of performing actions in Livewire on close.

Example:

```html
<div>
    <x-modal wire:model="showModal" class="modal">
        TEST
    </x-modal>
</div>
```

```php
use Livewire\Component;

class TestModal extends Component
{
    public bool $showModal = false;

    public function render()
    {
        return view('livewire.modal');
    }

    public function updatedShowModal()
    {
        dd('updated');
    }
}
```

Is there a way that I'm missing to handle the event in the backend?

**Comment by robsontenorio** [comment]
The “updated()” is only triggered when variables  are synced “on server side”. When you press ESC the variable is changing only on “frontend side”. 

When you use “wire:model” the state exists on “frontend side only”, until you submit a form or call any component method. 

So , try “wire:model.live” and the state is synced right away. 

This is a Livewire stuff, not Mary.

**Comment by robsontenorio** [comment]
In this case the only way is to use “persistent” attribute to avoid close modal with ESC. 

`<x-modal … persistent >`

Then, on CANCEL button you can set 

`wire:click=“$toggle('showModal')” `

It forces sync variable state o server side.
