### ISSUE TITLE
The File and ImageLibrary components are using x-button, instead x-mary-button.

### ISSUE THREAD

**Issue by joaoclobocar** [robsontenorio/mary#326]
### maryUI version

1.2.0

### daisyUI version

4.6.0

### Livewire version

3.4

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

The File and ImageLibrary components are using x-button, instead x-mary-button.

![image](https://github.com/robsontenorio/mary/assets/8374406/3160d0b3-96f6-4c75-8885-e94a51ce7874)

**Comment by robsontenorio** [comment]
Hi, upgrade to the latest  version. Currently 1.24

**Comment by joaoclobocar** [comment]
Sorry. It is already fixed. Thanks.
