### ISSUE TITLE
Unable to locate a class or view for component [collapse].

### ISSUE THREAD

**Issue by davidcabcab** [robsontenorio/mary#332]
### maryUI version

1.21

### daisyUI version

4.7.2

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

Even after upgrading all librairies, it's like there is no  < x-collapse > component available.

<img width="198" alt="Capture d’écran 2024-03-03 à 20 28 08" src="https://github.com/robsontenorio/mary/assets/153238958/3d7c5f12-0577-44f1-b171-d70fe5551d9e">
<img width="194" alt="Capture d’écran 2024-03-03 à 20 27 55" src="https://github.com/robsontenorio/mary/assets/153238958/95ea28c0-5276-4b40-a1d4-4550af457b4d">

**Comment by robsontenorio** [comment]
You are on `1.21` that is an old version.

In case of trouble to upgrade versions:

- Remove `composer.lock`
- Remove `/vendor`
- Remove `robsontenorio/mary` entry from `composer.json`
- Then `composer require robsontenorio/mary`

**Comment by davidcabcab** [comment]
Ok thanks, I'll give a try
