### ISSUE TITLE
Tags component

### ISSUE THREAD

**Issue by LancemDev** [robsontenorio/mary#334]
### maryUI version

1

### daisyUI version

4.7.2

### Livewire version

3

### What browsers are affected?

Firefox

### What happened?

I traced the error to the tags tag. Every component typically freezes when I add it. The error however is an alphine js error therefore I can't really change anything because I have not written alphine js code.

✅ Screenshot of error

![image](https://github.com/robsontenorio/mary/assets/74910038/d693c501-4acb-4de3-99da-790767eec0fc)

❌ Please, don't paste code as screenshot. Paste as formatted markdown code.

PHP

```php
namespace App\Livewire\Forms;

use App\Models\Video;
use Livewire\Attributes\Validate;
use Livewire\Form;
use Livewire\Attributes\Rule;

class UploadVideoForm extends Form
{
    public $photo;
    public $file;
    public $title;

    public $description;
    public array $tags = ['tech', 'gaming', 'art'];


    public function submit()
    {
        dd($this->title, $this->description, $this->file, $this->photo, $this->tags);
    }

}




namespace App\Livewire;

use Livewire\Component;
use Livewire\WithFileUploads;
use App\Livewire\Forms\UploadVideoForm;

class UploadVideo extends Component
{
    use WithFileUploads;
    public UploadVideoForm $form;
    public function mount()
    {
        // $this->form = new UploadVideoForm(w,r);
    }
    public function render()
    {
        return view('livewire.upload-video');
    }
}
```

HTML/Blade

```blade
<div>
    <x-mary-modal id="modal17">
        <x-mary-form id="uploadForm" wire:submit="submitForm">
            <x-mary-file wire:model="form.photo" accept="image/png" crop-after-change>
                <img src="{{ $user->avatar ?? asset('thumbnails/placeholder.jpg') }}" class="h-40 rounded-lg" />
            </x-mary-file>

            <x-mary-file wire:model="form.file" label="Receipt" hint="Click to upload video" />

            <x-mary-input wiire:model="form.title" label="Title" placeholder="Title" />
            <br />
            <x-mary-input wire:model="form.description" label="Description" placeholder="Description" />
            <br />
            <x-mary-tags wire:model="form.tags" label="Tags" placeholder="Tags" />
            <br />
        </x-mary-form>
        <x-slot:actions>
            <x-mary-button label="Cancel" onclick="modal17.close()" class="btn-ghost" />
            <x-mary-button type="submit" label="Upload" class="btn-success" />
        </x-slot:actions>
    </x-mary-modal>
</div>
```

**Comment by robsontenorio** [comment]
Please, report full version (x.y.z) of maryUI and Livewire. 

The form actions must me placed inside the form component it self. 

```
<x-form>
    <x-slot:actions>
         ….
    </x-slot:actions>
</x-form>
```

Maybe you are get confused because the Modal components also has the same actions slots. But they are different things.

**Comment by LancemDev** [comment]
Apologies for not specifying the version

livewire version - 3.4.6
maryui version - 1.24.0

I made the change still same error

'''blade

<div>
    <x-mary-modal id="modal17">
        <x-mary-form id="uploadForm" wire:submit="submitForm">
            <x-mary-file wire:model="form.photo" accept="image/png" crop-after-change>
                <img src="{{ $user->avatar ?? asset('thumbnails/placeholder.jpg') }}" class="h-40 rounded-lg" />
            </x-mary-file>

            <x-mary-file wire:model="form.file" label="Receipt" hint="Click to upload video" />

            <x-mary-input wiire:model="form.title" label="Title" placeholder="Title" />
            <br />
            <x-mary-input wire:model="form.description" label="Description" placeholder="Description" />
            <br />
            <x-mary-tags wire:model="form.tags" label="Tags" placeholder="Tags" />
         
            <x-slot:actions>
                <x-mary-button label="Cancel" onclick="modal17.close()" class="btn-ghost" />
                <x-mary-button type="submit" label="Upload" class="btn-success" />
            </x-slot:actions>
        </x-mary-form>
    </x-mary-modal>
</div>

'''

The error ->

![image](https://github.com/robsontenorio/mary/assets/74910038/59a6af13-4900-4776-95f9-4daae2451e78)

**Comment by LancemDev** [comment]
Isolating the tags component only

'''blade



'''

The error ->

**Comment by robsontenorio** [comment]
There are some <strong>typos</strong> and <strong>missing parts</strong> on your code.

But the following code works. There is no issue on `<x-tags />` component

<hr />

https://github.com/robsontenorio/mary/assets/118955/4bb53084-43c7-4341-a9ed-725be25813e5

<hr />


```php
<?php

namespace App\Livewire\Forms;

use Livewire\Form;

class UploadVideoForm extends Form
{
    public $title;
    public $description;
    public array $tags = ['tech', 'gaming', 'art'];

    public function save()
    {
        dd($this->title, $this->description, $this->tags);
    }
}

```


```php
use App\Livewire\Forms\UploadVideoForm;
use Livewire\Volt\Component;

new class extends Component {

    public UploadVideoForm $form;

    public bool $showModal = false;

    public function save()
    {
        $this->form->save();
    }
}
```

```html
<div>
    <x-button label="Open" @click="$wire.showModal = true" />
    <x-modal wire:model="showModal">
        <x-form wire:submit="save">
            <x-input wire:model="form.title" label="Title" placeholder="Title" />
            <x-input wire:model="form.description" label="Description" placeholder="Description" />
            <x-tags wire:model="form.tags" label="Tags" placeholder="Tags" />
            <x-slot:actions>
                <x-button label="Cancel" @click="$wire.showModal = false" class="btn-ghost" />
                <x-button type="submit" label="Upload" class="btn-success" />
            </x-slot:actions>
        </x-form>
    </x-modal>
</div>
```

**Comment by LancemDev** [comment]
I have done and I'm still getting the same error. I have even created a new livewire component like so
```blade

<div>
    <x-mary-button label="Open" @click="$wire.showModal = true" />
    <x-mary-modal wire:model="showModal">
        <x-mary-form wire:submit="save">
            <x-mary-input wire:model="title" label="Title" placeholder="Title" />
            <x-mary-input wire:model="description" label="Description" placeholder="Description" />
            <x-mary-tags wire:model="tags" label="Tags" placeholder="Tags" />
            <x-slot:actions>
                <x-mary-button label="Cancel" @click="$wire.showModal = false" class="btn-ghost" />
                <x-mary-button type="submit" label="Upload" class="btn-success" />
            </x-slot:actions>
        </x-mary-form>
    </x-mary-modal>
</div>

```

```php

<?php

namespace App\Livewire;

use Livewire\Component;

class UploadArea extends Component
{

    public $title;
    public $description;
    public array $tags = ['tech', 'gaming', 'art'];

    public function save()
    {
        dd($this->title, $this->description, $this->tags);
    }

    public function render()
    {
        return view('livewire.upload-area');
    }
}


```

The error is still the same

![image](https://github.com/robsontenorio/mary/assets/74910038/315ed4e6-e5b2-45a0-a6ed-ecb6350cd271)

**Comment by robsontenorio** [comment]
Is this a full page component ?

you still have missing parts on your sample. I can’t see “showModal” property. 

If you use my example it will work.

**Comment by LancemDev** [comment]
I have created a new laravel project and it worked.
Let me see just try and find where the issue in my project is

I really appreciate you taking your time to help me.

**Comment by robsontenorio** [comment]
Glad it worked , Let us know when you spot the problem on your current app.

**Comment by LancemDev** [comment]
I changed from using Breeze to using Jetstream with the same code and it worked. Still haven't found the bug in Breeze

**Comment by robsontenorio** [comment]
Maybe something in `app.js`.

Remember that on Livewire 3 , you must not  start Alpine on `app.js`

**Comment by LancemDev** [comment]
Yes yes, I have confirmed this. I could've just read the docs keenly 🤦

I really appreciate your help❤️. Hopefully I'll support your projects when I get a job
