### ISSUE TITLE
$this->loop->index does not work inside a Livewire 3 component inside a mary table.

### ISSUE THREAD

**Issue by Ravenna** [robsontenorio/mary#335]
### maryUI version

1.20

### daisyUI version

4.7.1

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

I have a livewire component that has an array of objects.  I use that array to create the table: 
```
    <x-table :headers="$headers" :rows="$ratings">

``` 
This works great.  Then in the table rows I need to do something like:
```
@scope('cell_rated_as', $qr)
            <x-input name="rated_as" class="input-sm" wire:model="ratings[{{$this->loop->index}}].rated_as"/>
@endscope
```
This is where we throw an error: "Property [$loop] not found on component: [quote-rating-view]". quote-rating-view is my livewire component. 

This is an image of what I am trying to sort out:

![Screenshot 2024-03-04 at 4 31 37 PM](https://github.com/robsontenorio/mary/assets/72239/6d77f933-679c-4292-b57d-46d56fa4b4d5)

Any ideas?

**Comment by robsontenorio** [comment]
This is not related to $loop variable, but the Livewire syntax for wire:model arrays. It is hard to spot some example on its docs. 

Try this 

```
wire:model="ratings.{{$this->loop->index}}.rated_as”
```

I advice to test edge cases with simple “foreach” and raw Livewire before going deep with marUI components.
