### ISSUE TITLE
Show/Hide column

### ISSUE THREAD

**Issue by tranhuungan1990** [robsontenorio/mary#338]
It's fantastic. Thank you for creating MaryUI. I'm using the <x-table> component. I have a list of checkboxes representing hidden columns, and when clicked, the table should reveal those hidden columns. Could you guide me on how to achieve this? Thank you very much.

**Comment by robsontenorio** [comment]
You can control columns visibility through the “headers” object using it “class” key. 

See the responsive example. 
https://mary-ui.com/docs/components/table#header-classes

So all you need is to bind that checkbox’s models to switch that classes to control the visibility.
