### ISSUE TITLE
Dynamic Dependent Choices

### ISSUE THREAD

**Issue by tranhuungan1990** [robsontenorio/mary#340]
![image](https://github.com/robsontenorio/mary/assets/42708336/0c42836e-b259-467d-9ec4-355942fe0cb5)

Has anyone done Dynamic Dependent Selection like this?

**Comment by robsontenorio** [comment]
Cc @roberto-proj

**Comment by roberto-proj** [comment]
Hello, Mr. @tranhuungan1990. I wrote an example of how you can do that. Since I didn't create a table for `countries` and `cities`, because I don't know anything about your tables structure, consider `$countriesTable` and `$citiesTable` as some _hardcoded_ way of representing such information.

```php
<?php

use Livewire\Attributes\Computed;
use Livewire\Volt\Component;

new class extends Component {

    public array $countriesTable = [
        ['id' => 1, 'name' => 'USA'],
        ['id' => 2, 'name' => 'Brazil'],
        ['id' => 3, 'name' => 'Germany']
    ];

    public array $citiesTable = [
        ['id' => 1, 'name' => 'New York', 'country_id' => 1],
        ['id' => 2, 'name' => 'San Diego', 'country_id' => 1],
        ['id' => 3, 'name' => 'Chicago', 'country_id' => 1],
        ['id' => 4, 'name' => 'Rio de Janeiro', 'country_id' => 2],
        ['id' => 5, 'name' => 'São Paulo', 'country_id' => 2],
        ['id' => 6, 'name' => 'Brasília', 'country_id' => 2],
        ['id' => 7, 'name' => 'Berlin', 'country_id' => 3],
        ['id' => 8, 'name' => 'Hamburg', 'country_id' => 3],
        ['id' => 9, 'name' => 'Frankfurt', 'country_id' => 3],
    ];

    public string $selectedCountry = '';
    public string $selectedCity = '';

    public function getCountries(): array
    {
        return $this->countriesTable;
    }

    public function getCities(): array
    {
        return collect($this->citiesTable)->where('country_id', $this->selectedCountry)->toArray();
    }

    public function with(): array
    {
        return [
            'countries' => $this->getCountries(),
            'cities' => $this->getCities()
        ];
    }


}; ?>

<div>
    <x-select label="Pick a country" icon="o-user" :options="$countries" wire:model.live="selectedCountry"
              placeholder="Select a country"
              placeholder-value="0"/>
    <x-select label="Pick a city" icon="o-user" :options="$cities" wire:model="selectedCity"/>

</div>
```

**Comment by tranhuungan1990** [comment]
Thank you @roberto-proj ! ❤️

**Comment by DeRaja** [comment]
Hello!

I tried to use the dependent dropdown - instead of hard coding - by following:

        $this->countries = Country::all();
        $this->states = collect();
        $this->cities = collect();
        $this->selectedCity = $selectedCity;

I was not able to get it from the DB.

Does someone have any code snippet for me? Seems like I am missing something.

IN fact, it would be of imense help to have this example inside the default because if someone wants to use country/state/city model, then it is likely they may want to use it from the DB instead of hardcoding.
