### ISSUE TITLE
Optionally want to show badge with tabs component

### ISSUE THREAD

**Issue by palpalani** [robsontenorio/mary#342]
I want to display count with tab title using badge component, right now it is not possible.

**Comment by robsontenorio** [comment]
Hey @roberto-proj , this is good first issue, if you are willing to contribute.

You can use the same approach we have on `x-list-item` in order to expose `$label` property as a `<x-slot:label>`  slot.

**Comment by hamannjames** [comment]
@robsontenorio I am taking a try at this and cannot seem to get slots to work for tabs. It looks like you only need to expose a variable for it in the constructor and then use it in the template if it exists, at least according to the way "input" uses prepend and append. However I cannot get tabs to recognize any slot passed in via x-slot, even when exposing a matching variable name. What am I missing?

**Comment by robsontenorio** [comment]
Solved by #377
