### ISSUE TITLE
 None of the File upload are working

### ISSUE THREAD

**Issue by ronnieparalejas** [robsontenorio/mary#346]
If we go to this link [https://mary-ui.com/docs/components/file]( https://mary-ui.com/docs/components/file) none of it are working. 

Same goes to my project.

**Comment by robsontenorio** [comment]
Please, provide more context. 

What errors do you get on maryUI file docs ? What browsers?

**Comment by ronnieparalejas** [comment]
@robsontenorio It works now after updating the chrome to latest version. Thanks!!
