### ISSUE TITLE
component <x-file> image preview not working when use <x-modal>

### ISSUE THREAD

**Issue by amrikarisma** [robsontenorio/mary#354]
### maryUI version

1.25.3

### daisyUI version

4.7.2

### Livewire version

3.4

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

Cannot read image value from image variable

![image](https://github.com/robsontenorio/mary/assets/4257664/e5196e38-461c-46d9-b279-0d2fadbe4a6e)

PHP

```php
<?php

namespace App\Livewire\Admin\Projects;

use App\Models\Category;
use App\Models\Project;
use Livewire\Attributes\On;
use Livewire\Component;
use Livewire\WithFileUploads;
use Mary\Traits\Toast;

class ProjectsUpdate extends Component
{
    use WithFileUploads, Toast;

    public $project, $name, $description, $link, $image, $category_id, $categories;
    public bool $myModal2 = false;

    public function mount()
    {
        $this->categories = Category::all();
    }

    #[On('update-projects')] 
    public function showModal($id)
    {
        $this->project = Project::find($id);
        $this->name = $this->project->name;
        $this->description = $this->project->description;
        $this->link = $this->project->link;
        $this->image = $this->project->image;
        $this->category_id = $this->project->category_id;
        $this->resetValidation();

        $this->myModal2 = !$this->myModal2;
        // $this->dispatch('refresh-data');

    }

    public function rules()
    {
        return [
            'name' => 'required',
            'description' => 'required|string',
            'link' => 'nullable|url',
            'image' => 'image|max:1024|nullable',
            'category_id' => 'required',
        ];
    }

    public function attributes()
    {
        return [
            'category_id' => 'Category',
        ];
    }

    public function submit()
    {
        $data = $this->validate($this->rules(), [], $this->attributes());
        // save image on my project

        if (isset($data['image']) && !empty($data['image'])) {
            $imageName = time() . '.' . $this->image->getClientOriginalExtension();
            $this->image->storeAs('images', $imageName, 'public');
            $data['image'] = 'images/' . $imageName;
        } else {
            unset($data['image']);
        }

        $this->project->update($data);
        $this->dispatch('refresh-data')->to(ProjectsIndex::class);

    }
    // #[On('refresh-data')] 
    public function render()
    {
        return view('admin.projects.projects-update');
    }
}

```

HTML/Blade

```blade
<x-modal wire:model="myModal2" title="Edit Projects">
    <x-form wire:submit.prevent="submit">
        @if (session()->has('message'))
            <div class="alert alert-primary my-success-alert">
                {{ session('message') }}
            </div>
        @endif
        <div class="grid grid-cols-1 gap-3">
            <x-input label="Name" wire:model="name" />
            <x-input label="Description" wire:model="description" />
            <x-input label="Link" wire:model="link" />
            <x-select label="Category" :options="$categories" wire:model="category_id" />

            <x-file wire:model="image" label="Images" accept="image/png, image/jpeg">
                @dump($image)
                <img src="{{ !empty($image) ? $image : 'https://www.pakarbot.com/wp-content/uploads/2019/04/placeholder.png' }}"
                    class="h-40 rounded-lg" />
            </x-file>
        </div>

        <x-slot:actions>
            <x-button label="Cancel" @click="$wire.myModal2 = false" />
            <x-button label="Confirm" class="btn-primary" type="submit" spinner="submit" />
        </x-slot:actions>
    </x-form>
</x-modal>

```

**Comment by robsontenorio** [comment]
Maybe you are mixing the tings.

This holds the binary file while uploading. And it has 
```
<x-file wire:model="image" ... />
```

But, you need another property that holds the file image url itself that comes from related thing you are editing.

See this example. There are two properties.

<img width="1041" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/123b776f-95bb-41e5-9838-7d7b37b7d5ed">

**Comment by amrikarisma** [comment]
> It has nothing todo with modals. Maybe you are mixing the tings.
> 
> This holds the binary file while uploading.
> 
> ```
> <x-file wire:model="image" ... />
> ```
> 
> But, you need another property, to be displayed on `img`, that holds the previous image url itself that comes from related thing you are editing.
> 
> See this example that edits the user's avatar. There are two properties.
> 
> * `wire:model="avatar_file"` handles the file upload
> * `$user->avatar` has the current user avatar image (otherwise we display a placeholder)
> 
> <img alt="image" width="1041" src="https://private-user-images.githubusercontent.com/118955/316856554-123b776f-95bb-41e5-9838-7d7b37b7d5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTAwMzMsIm5iZiI6MTcxMTUwOTczMywicGF0aCI6Ii8xMTg5NTUvMzE2ODU2NTU0LTEyM2I3NzZmLTk1YmItNDFlNS05ODM4LTdkN2IzN2I3ZDVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwMzIyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTBlMzk3NzIyZjFlODJiNmZkNTdjODg0MGIxY2VjOGE1ZDAzMDZhYzVjOWQyODFmNjM5NThmYmY2ZjM3OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FkfP9MfbCv5Hui3bZegTwLaMBtjHY1prEITOJGVF908">


I have tried @dump inside the x-file component all the variables are null, no data can be returned.

But, if I load the x-file component on a new page the variables in the x-file component will be read. I feel that when on mount the empty variable then trigger the "showModal" function does not re-render so that $image or any variable whose value is set in the "showModal" function is still null.

```blade
<x-file wire:model="image" label="Images" accept="image/png, image/jpeg">
                @dump($image)
                <img src="{{ !empty($image) ? $image : 'https://www.pakarbot.com/wp-content/uploads/2019/04/placeholder.png' }}"
                    class="h-40 rounded-lg" />
            </x-file>
```

**Comment by robsontenorio** [comment]
Please , read carefully my previous comment and example . 

You are using the same variable “image” at two places on same component , and it is not supposed to work. Use two different variables as suggested on maryUI docs and on my example.
