### ISSUE TITLE
customize modal size

### ISSUE THREAD

**Issue by T3mmyKay** [robsontenorio/mary#358]
There should be a feature for customizing modal size

**Comment by igoralentyev** [comment]
I know only one way to do this - style with your own normal css, not a tailwind. Cause classes we can assign in mary component only applies to dialog element itself, not to the div.box-modal which is controlling modal's layout in daisyui.

**Comment by robsontenorio** [comment]
That is correct. The PR #359 it is no good because CSS would be inject in two parts of the component.

**Comment by robsontenorio** [comment]
Release.
