### ISSUE TITLE
Quick question 

### ISSUE THREAD

**Issue by abq0** [robsontenorio/mary#360]
Firstly thanks for the amazing library , secondly I want to know is there anyway to use the toasts alert from **front-end** ? cause it's shows in the docs how to dispatch it from Livewire **back-end**
https://mary-ui.com/docs/components/toast
e.g. 
```
<button onclick="maryuiToast('hi','warning',4000)">Whew!</button>
```
anyway or workaround ? no problem for me :)

**Comment by robsontenorio** [comment]
It was not designed to be used like that. But there is a global “toast” object you can try, by using a full payload. 

https://github.com/robsontenorio/mary/blob/601842de253f447fc58799bb5e5b1f0a69c13cc1/src/View/Components/Toast.php#L48
