### ISSUE TITLE
Reusable form components generate the same ID for form fields

### ISSUE THREAD

**Issue by hdptrck** [robsontenorio/mary#361]
### maryUI version

^1.25

### daisyUI version

^4.9.0

### Livewire version

^3.4

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

First of all I would like to thank you for the gorgeous component library!

I am facing the following problem when I use a reusable form component several times on the same page. Tere are duplicates in the ID of the form fields. I use a reusable form component in my project when listing films in a table, which I can then edit. The expandable table component is truly amazing for that!

```blade
<x-mary-table :headers="$headers" :rows="$movies" wire:model="expanded" expandable>
  @scope('expansion', $movie)
    <livewire:components.movie-form :$movie />
  @endscope
</x-mary-table>
```

But now I have the problem that in the form the inputs with the same label are rendered exactly the same several times. The generated uuid with the md5-hash which is set as html id is therefore the same everywhere and when I click on a label I jump to the input in the very first form.

The cause lies in the file [Input.php](https://github.com/robsontenorio/mary/blob/main/src/View/Components/Input.php) when generating the uuid. I would have the suggestion to change this to a random uuid to avoid the problem:

```php
$this->uuid = "mary" . Illuminate\Support\Str::uuid();
```

Thank you for your efforts.

**Comment by robsontenorio** [comment]
I think you should set `wire:key`, because anything inside a table it is submitted to a foreach.


```blade
  @scope('expansion', $movie)
    <livewire:components.movie-form :$movie wire:key="movie-{{ $id }}" />
  @endscope
```

**Comment by hdptrck** [comment]
I tried it, but it doesn't solve my problem. When I write a form component, I use something like this:
```blade
<x-mary-form wire:submit="save">
    <x-mary-input label="Title" wire:model="form.title" />
    {{-- ... --}}
</x-mary-form>
```
As already mentioned, this form component ```<livewire:components.movie-form>``` is rendered several times. And each time ```<x-mary-input>``` will generate a ```<label>``` and ```<input>``` with the same HTML ID. So far, so good, but the problem is that the same ID is set in every form component because the ID is created based on the props passed in. I always pass the ```label="title"``` to the ```<x-mary-input>```. 
So the following is rendered each time:
```html
<form wire:submit="save" class="grid grid-flow-row auto-rows-min gap-3">
    <div>
        <label for="maryce5331466cbcfa3d0b9e91d7178bfb98form.title" class="pt-0 label label-text font-semibold">
            <span>
                Title
            </span>
        </label>
        <div class="flex-1 relative">
            <input id="maryce5331466cbcfa3d0b9e91d7178bfb98form.title" placeholder=" "
                class="input input-primary w-full peer" type="text" wire:model="form.title">
        </div>
    </div>
</form>
```
When you click on a ```<label>```, you automatically jump to the referenced input. If I do this for the last input field, I jump to the very first rendered title-```<input>``` because it is the first one found by the browser with this ID.

In the maryUI input component, I have seen that the uuid is generated as follows:
```php
class Input extends Component
{

    public string $uuid;

    public function __construct(
        public ?string $label = null,
        public ?string $icon = null,
        public ?string $iconRight = null,
        public ?string $hint = null,
        public ?string $prefix = null,
        public ?string $suffix = null,
        public ?bool $inline = false,
        public ?bool $clearable = false,
        public ?bool $money = false,
        public ?string $locale = 'en-US',

        // Slots
        public mixed $prepend = null,
        public mixed $append = null,
        // Validations
        public ?string $errorField = null,
        public ?string $errorClass = 'text-red-500 label-text-alt p-1',
        public ?bool $omitError = false,
        public ?bool $firstErrorOnly = false,
    )
    {
        $this->uuid = "mary" . md5(serialize($this));
    }
    // ...
}
```

And now my suggestion is to change the content of the constructor to avoid the described problem when looping over a form component.
```php
$this->uuid = "mary" . Illuminate\Support\Str::uuid();
```

**Comment by robsontenorio** [comment]
Unfortunately we can't use `Illuminate\Support\Str::uuid()`  because it generates a random string for the same component if you render it again, and Livewire does not like it.

We need a better solution.

**Comment by robsontenorio** [comment]
I was not able to reproduce that. The following code does not show errors on console.

**MAIN COMPONENT** 

```php
<?php

use App\Models\User;
use Livewire\Volt\Component;

new class extends Component {

    public array $expanded = [];

    public function headers(): array
    {
        return [
            ['key' => 'id', 'label' => '#'],
            ['key' => 'name', 'label' => 'Name'],
        ];
    }

    public function with(): array
    {
        return [
            'users' => User::take(5)->get(),
            'headers' => $this->headers(),
        ];
    }
}; ?>

<div>
    <x-table :headers="$headers" :rows="$users" wire:model="expanded" expandable>
        @scope('expansion', $user)
            <livewire:form :$user />
        @endscope
    </x-table>
</div>
```

**FORM COMPONENT**


```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    public mixed $user;

    public string $name = '';

    public function save()
    {
        dump($this->name);
    }
}; ?>

<div>
    <x-form wire:submit="save">
        <x-input label="name" wire:model="name" />
    </x-form>
</div>
```
