### ISSUE TITLE
Spotlight does not appear on Microsoft Edge and Chrome with keyboard buttons

### ISSUE THREAD

**Issue by akhmads** [robsontenorio/mary#367]
### maryUI version

1.26

### daisyUI version

4.9.0

### Livewire version

3.4

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

Hello Sir Robson,

First of all, I want to say thank you very much for the wonderful library.

I found that the "Spotlight" popup does not appear in my application if using the keyboard keys (CTR + G), in Microsoft Edge (Version 123.0) and Chrome on window 11.
But If use the button ($dispatch('mary-search-open')) it works.
Is there something I missed or is it a bug? Thank You

**Comment by robsontenorio** [comment]
Try META + G

**Comment by akhmads** [comment]
Hello Sir,

Still not work, I think maybe this is a problem with my laptop.

Thanks Sir.
