### ISSUE TITLE
After selecting the item in the choice (multi) "No Result Found" appears.

### ISSUE THREAD

**Issue by akhmads** [robsontenorio/mary#368]
### maryUI version

1.26

### daisyUI version

4.9.0

### Livewire version

3.4

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

Hello Sir,
After selecting an item in the choice (multi) "No Result Found" appears. This event repeats itself when I select an item then continue typing to search for the next item.

Screenshot
![image](https://github.com/robsontenorio/mary/assets/13780840/1ef60c84-c103-46a9-a7f8-b329bf635dcb)

My Class
```php
#[Rule('sometimes')]
public array $tags = [];
public Collection $tagsSearchable;

public function mount(): void
{
    $this->searchTags();
}

public function searchTags(string $value = ''): void
{
    $selectedOption = Tag::whereIn('id', $this->tags)->get();
    $this->tagsSearchable = Tag::query()
       ->where('name', 'like', "%$value%")
       ->take(5)
       ->orderBy('name')
       ->get()
       ->merge($selectedOption);
}
```

HTML/Blade

```blade
<x-choices label="Tags" wire:model="tags" :options="$tagsSearchable" debounce="300ms" search-function="searchTags" searchable />
```
Thank you very much sir

**Comment by robsontenorio** [comment]
Could you please attach a video showing when it happens?

**Comment by akhmads** [comment]
This is the video sir

https://github.com/robsontenorio/mary/assets/13780840/589c6994-397f-471b-ad55-d386d5b3fbc4

**Comment by robsontenorio** [comment]
Do you have exactly two items on Tags table ? Or more ?

**Comment by robsontenorio** [comment]
Just opened a discussion on Livewire repository. 

https://github.com/livewire/livewire/discussions/8329

**Comment by akhmads** [comment]
Thank you sir
