### ISSUE TITLE
sidemenu  double scrolling 

### ISSUE THREAD

**Issue by kitadesega** [robsontenorio/mary#369]
### maryUI version

1.26

### daisyUI version

4

### Livewire version

3

### What browsers are affected?

Chrome

### What happened?

Is there a solution to prevent double scrolling from occurring?

The phenomenon shown in this image also occurs in my development environment.
help...me

This problem also occurs in the official documentation

![image](https://github.com/robsontenorio/mary/assets/44725054/2c8aee59-2c2c-499a-9492-4b1a3550d77e)

**Comment by robsontenorio** [comment]
Try to update your browser.

**Comment by kitadesega** [comment]
> Try to upgrade your browser.

Chrome is up to date.....

**Comment by kitadesega** [comment]
> Try to upgrade your browser.
@robsontenorio 
Chrome is up to date.....

**Comment by robsontenorio** [comment]
I can’t reproduce it. 

The maryUI logo is not that shown on your print. Are you browsing mary-ui.com or have you cloned it ?

**Comment by robsontenorio** [comment]
Solved by #364
