### ISSUE TITLE
If the `lg:w-1/3` class is assigned, the font will appear blurred.

### ISSUE THREAD

**Issue by s-kitade** [robsontenorio/mary#371]
### maryUI version

1.26

### daisyUI version

4

### Livewire version

3

### What browsers are affected?

Chrome

### What happened?

```html
<x-mary-drawer wire:model="drawer" title="フィルター" right separator with-close-button class="lg:w-1/3">
```
If the `lg:w-1/3` class is assigned, the font will appear blurred.

There was no problem in safari

![image](https://github.com/robsontenorio/mary/assets/107913515/6a67be27-79f3-41dc-b8b6-536b3786444d)

![image](https://github.com/robsontenorio/mary/assets/107913515/b144b5ab-9aa9-4abd-a4a0-14dc5ed2b594)

**Comment by robsontenorio** [comment]
Actually this css classes are just Tailwind, you can use any. 

So, maryUI does not rule here.

**Comment by s-kitade** [comment]
@robsontenorio 
thnak you ..

Does this mean that the behavior of tailwind is the problem?

I can't think of a solution...

**Comment by s-kitade** [comment]
https://www.windowslatest.com/2024/03/25/microsoft-is-improving-chromes-font-rendering-on-windows-11-windows-10/


I hope this is the solution

**Comment by s-kitade** [comment]
I solved it this way.

```css
<style>
    .drawer-side > *:not(.drawer-overlay) {
        will-change: unset!important;
    }
</style>
```

**Comment by robsontenorio** [comment]
Yes. It is tailwind and maybe related to specific browser version I think so.
