### ISSUE TITLE
Table labels unreadable with dark themes

### ISSUE THREAD

**Issue by bestmomo** [robsontenorio/mary#373]
### maryUI version

1.26

### daisyUI version

4.10.1

### Livewire version

3.4

### What browsers are affected?

Firefox

### What happened?

![Capture d'écran 2024-04-11 181805](https://github.com/robsontenorio/mary/assets/2959682/e013989e-5221-49ad-9678-df6a2dbbdcbd)

**Comment by robsontenorio** [comment]
What is your OS ? This issue also happens on Chrome ?

**Comment by willcastillo** [comment]
I can confirm it also happens in Chrome (Version 123.0.6312.106 (Official Build) (64-bit) / Win11)

**Comment by bestmomo** [comment]
Also happens on Brave and Edge

**Comment by robsontenorio** [comment]
Could you guys please check this?

- Bootstrap a brand new project at  http://phpsandbox.io

- Then, open a terminal on (+) icon

<img width="568" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/a18ff670-aa5b-440c-8090-ceb9683c852f">

<br /><br />

- Install mary + yarn build

```
 composer require robsontenorio/mary && php  artisan mary:install && yarn build
```
<br />

- Then , refresh the page
<br />
<img width="607" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/966dd61d-e2a6-4ffa-bdc8-1442b12a1877">

**Comment by bestmomo** [comment]
Hello, I have an issue to access to [http://phpsandbox.io/](http://phpsandbox.io/) : PR_CONNECT_RESET_ERROR

**Comment by bestmomo** [comment]
Still getting message PR_CONNECT_RESET_ERROR

**Comment by willcastillo** [comment]
For what it's worth,

**Comment by willcastillo** [comment]
For what it's worth, I see my table (specifically the THEAD elem) is missing this style that is present in the [first example in the mary-ui docs for table](https://mary-ui.com/docs/components/table#simple). Not sure what is causing that.

![mary-ui-table-missing-style](https://github.com/robsontenorio/mary/assets/1260357/9982db5b-fa3c-4808-9d2e-be0cf9f9642d)

**Comment by bestmomo** [comment]
I solved it temporarily in src/Views/Components/Table.php on line 182 :
```
<!-- <thead @class(["text-black dark:text-gray-200", "hidden" => $noHeaders])> -->
<thead @class(["hidden" => $noHeaders])>
```

**Comment by robsontenorio** [comment]
I really could not reproduce this ...  I am sorry.

Here is the output and the CSS class is present.

![image](https://github.com/robsontenorio/mary/assets/118955/d358569b-befc-42b7-95d9-373cbf7bb9b1)

Also tried a simple HTML hardcoded from daisyUI site.

![image](https://github.com/robsontenorio/mary/assets/118955/9f29617c-9736-4627-a511-bbfa6edc0646)


Maybe this is issue on Windows + Tailwind. As workaround you can force any override you want on `app.css`

**Comment by robsontenorio** [comment]
Good news! The #374 will solve it.

**Comment by bestmomo** [comment]
Still a total mystery to me as it works fine on your web site, I even used your css file on mine but still buggy...

**Comment by bestmomo** [comment]
> Good news! The #374 will solve it.

Not sure I understand why it does...

**Comment by robsontenorio** [comment]
@bestmomo @willcastillo 

I got a Windows 11 machine.

- Updated Chrome to latest stable 124 version.
- Updated JS to latest stable  (daisyui, tailwind, prefixes, postcss)
- Switched Windows theme color to dark

And I can't see this issue anymore.

Could you guys confirm?


```js
"devDependencies": {
        "autoprefixer": "^10.4.19",        
        "daisyui": "^4.10.2",
        "postcss": "^8.4.38",
        "tailwindcss": "^3.4.3",
        ....
    }
```

**Comment by bestmomo** [comment]
Hello!

That is what I do:

- new fresh Laravel 11
- composer require robsontenorio/mary
- php artisan mary:install
- Yes for Volt installation
- npm install --save-dev
- adding this in tailwind.config.js:
```
    daisyui: {
        themes: ["light", "dark", "cupcake"],
    },
```

- npm run dev
- In layout:
`<html data-theme="dark" lang="{{ str_replace('_', '-', app()->getLocale()) }}">`

- my devdependencies:
```
"devDependencies": {
    "autoprefixer": "^10.4.19",
    "axios": "^1.6.4",
    "daisyui": "^4.10.2",
    "laravel-vite-plugin": "^1.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "vite": "^5.0"
}
```

Using Chrome Version 124.0.6367.61 (Build officiel) (64 bits)


![Capture d’écran 2024-04-20 220814](https://github.com/robsontenorio/mary/assets/2959682/036cee77-1b4e-4853-9545-c563d0c80d7b)

When I load Mary website for table component all is fine:

![Capture d'écran 2024-04-20 221245](https://github.com/robsontenorio/mary/assets/2959682/d91f0660-8972-43f9-baf1-89f05d9905fa)

**Comment by bestmomo** [comment]
> Ok, here is the problem. You should not do this. If you remove it , it should work fine.
> 
> ```
> <html data-theme="dark" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
> ```
> 
> You should make use of this in case of theme switching.
> 
> https://mary-ui.com/docs/components/theme-toggle
> 
> And here is the new feature , not documented yet. #387

Thank you!

**Comment by AtefR** [comment]
TailwindCSS by default uses `prefers-color-scheme ` to toggle between dark and light modes.

change it to use `selector` strategy and this will be fixed.

https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
