### ISSUE TITLE
Unable to locate a class or view for component [input].

### ISSUE THREAD

**Issue by rabol** [robsontenorio/mary#376]
### maryUI version

1.26.1

### daisyUI version

4.10.1

### Livewire version

3.4.10

### What browsers are affected?

Chrome

### What happened?

New installation:

laravel new myapp

Select Breeze with Volt class api
support dark mode

then check the new app and observer all is working

then
composer require robsontenorio/mary
php artisan mary:install

then go to the app an you will see:

Unable to locate a class or view for component [input].

**Comment by rabol** [comment]
One have to rename all the <x-* in the blade filed
A note in the docs would help

also, for some reason, the o-square-3-stack-3d icon is not found in the AppBrand component

**Comment by robsontenorio** [comment]
How looks like your `config/mary.php` ?

**Comment by rabol** [comment]
it have the mary- prefix, which means that all blade files from the mary::install needs to be manually modified

I think that a not where the command
```laravel new myapp```
is shown, it should be mentioned that one should not select a starter kit as that will make following the bootcamp much more difficult

**Comment by robsontenorio** [comment]
Got it 👍
