### ISSUE TITLE
Sizing Choises component

### ISSUE THREAD

**Issue by derrok** [robsontenorio/mary#386]
It would be nice to have the ability to change the size of the choices components as a regular select, because it stands out from the style if the other components are input-sm or select-sm.

**Comment by robsontenorio** [comment]
You can customize it with custom slots, as described on Choices docs.

**Comment by derrok** [comment]
![image](https://github.com/robsontenorio/mary/assets/6154701/81a6c82d-2ddd-4d0d-977a-ef9660919538)

How can I achieve the same size using custom slots?

**Comment by robsontenorio** [comment]
The way is to use custom CSS to override all the Choices styles through “app.css”.  

Because there is no easy way to offer fine grained tuning through component attributes.

**Comment by derrok** [comment]
> Actually I see you have some custom CSS in place, because that is not default height for input fields (ex: search, name, price) and buttons.
No, i dont use custom CSS. This is my code:
```php
    <x-form wire:submit="save">
            <x-input label="Name" class="input-sm" wire:model="form.name" clearable icon="o-user"/>
            <x-input label="Price" class="input-sm" wire:model="form.amount" prefix="USD"/>
            <x-choices-offline label="Country" wire:model="country" :options="$countries" class="select-sm" single searchable />
        <x-slot:actions>
            <x-button label="Cancel" class="btn-sm" x-on:click="userTheme == 'dark' ? userTheme = 'light' : userTheme = 'dark'"/>
            <x-button label="Save" class="btn-primary btn-sm" type="submit" spinner="save"/>
        </x-slot:actions>
    </x-form>
```
