### ISSUE TITLE
Month Selection in Datepicker Component

### ISSUE THREAD

**Issue by aachiary** [robsontenorio/mary#394]
Hi how are you??
I'm new at livewire and MaryUI and need some help.
I wanted to know if it was possible to use the plugin called "monthSelectPlugin" from the datepicker "flatpickr".
I read the docs of flatpickr but I didn´t get how can I use config it in the component. Tried a parameter ":plugins" but didn't work. I've also tried with the altFormat and other options but the selection is still a date and not a month.
Thanks for the help,
Andres

Plugins doc page from flatpickr: https://flatpickr.js.org/plugins/#monthselectplugin

**Comment by robsontenorio** [comment]
This is a trick one. Because, flatpickr docs are not clear about how to install plugins.

**Here is how to install a plugin**

```html
<script src="https://unpkg.com/flatpickr/dist/plugins/monthSelect/index.js"></script>
<link href="https://unpkg.com/flatpickr/dist/plugins/monthSelect/style.css" rel="stylesheet">
```

**And here is how to use it (without maryUI).**

```html
<input type="text" id="myID" class="input input-primary" />
    <script>
        flatpickr("#myID", {
            plugins: [
                new monthSelectPlugin({
                    shorthand: true, //defaults to false
                    dateFormat: "m.y", //defaults to "F Y"
                    altFormat: "F Y", //defaults to "F Y"
                    theme: "dark" // defaults to "light"
                })
            ]
        });
    </script>
```

But, **plugins is not supported by maryUI at this moment**, because plugins settings must be parsed as **plain JS**.

For future reference, here is a proposal for the API in some PR.


**This won't work right now.**

```blade
@php
    $config1 = [
        // Global settings
        'locale' => 'fr',
        ...

        // Must be extracted to top level
        'plugins' => [
                // This is a string and must be parsed as plain JS.
                '
                  new monthSelectPlugin({
                    shorthand: true, //defaults to false
                    dateFormat: "m.y", //defaults to "F Y"
                    altFormat: "F Y", //defaults to "F Y"
                    theme: "dark" // defaults to "light"
                })
               '
        ]
    ];
@endphp
 
<x-datepicker wire:model="myDate1" :config="$config1" /
```
