### ISSUE TITLE
QUESTION: how to make the alert component dismissable?

### ISSUE THREAD

**Issue by itsmenewbie03** [robsontenorio/mary#397]
How can i make the alert component dismissable? I read the [docs](https://mary-ui.com/docs/components/alert) but I don't see a way to make it disappear when clicked. 

## NOTE:
I initially wanted to use the toast however I can't seem to make it work as I want the toast to appear when session has message. But for some reason it doesn't work.

**Comment by robsontenorio** [comment]
Right now the `x-alert` is not dismissible. 

But you can try with Alpine, for now.

```blade
<x-alert ...  x-data="{ show: true }" @click="show = false">
 ....
</x-alert>
```

If someone is  able I will accept a PR to make it dismissible like this.

```
// It shows a `close` icon to dismiss hide it.
<x-alert dismissible> ... </x-alert>
```

**Comment by itsmenewbie03** [comment]
Love how fast this is implemented. I'd love to be able to contribute to this project in the future.

**Comment by robsontenorio** [comment]
Actually it is pretty simple. They are pure blade components. 

Take the example from Badges.php or Alert.php
