### ISSUE TITLE
QUESTION: Mary-Table how can i only show the icon to expand rows on mobile ?

### ISSUE THREAD

**Issue by DaniGuzman** [robsontenorio/mary#399]
Im debbuging the code and im not seeing nothing related with this.
I can hide headers and cells with css classes but mary adds the expandable icon under the hood, so i dont know how to do it. 

NOTE: i can hide the expandable component but not the icon. I want to be able to hide/show the icon too. :)

**Comment by robsontenorio** [comment]
You mean disable the expansion feature on mobile?

**Comment by DaniGuzman** [comment]
![image](https://github.com/robsontenorio/mary/assets/35112961/1b1e750e-8cfd-4154-86c8-ea7e3f0f8663)
![image](https://github.com/robsontenorio/mary/assets/35112961/1259ab89-1d04-4cf9-9b3e-5a854a53a981)


Desktop: i dont wanna show the expandable div and the icon
mobile: i wanna show the expandable div and the icon. (i hidded the columns that are inside the expandable component with css ).

Hope it helps !

**Comment by robsontenorio** [comment]
You can use basic CSS to hidden the first header/column.

```css
table tr th:first-child, table tr td:first-child {
    @apply lg:hidden
}
```
