### ISSUE TITLE
Choices : Unable to see selected items

### ISSUE THREAD

**Issue by groxw** [robsontenorio/mary#40]
Hello, I've updated mary ui with latest version, but when I updated it, Choices unable to see selected items, here's my code 

Blade : 

` <x-choices  wire:model="id_user" :options="$all_user"  searchable  />`

Livewire
```
    public function mount()
    {

        $this->search();
    }

    public function search(string $value = '') {

        // Also load selected users, besides result search
        $preUsers = User::whereIn('id', $this->id_user)->get();
        $this->all_user = User::search($value)
                          ->get()
                          ->merge($preUsers);
    }

```

**Comment by groxw** [comment]
Sometimes, it works and it doesnt

**Comment by robsontenorio** [comment]
@groxw I would need to know exactly steps it fails. 

I know there is a bug on “browser back button”. But is a current  Livewire bug itself. 

Is it ?

**Comment by groxw** [comment]
1. When I try to call an edit function, let's say that i have a model Class for school that belongsToMany with user (student) with name function class(), 
when i try to call an edit function $id_user has filled with user_id from users by function user_class(), it's selected but it wont appear on a list of choices, it's only selected.
2. I think it's 0.32 and now with a latest version
3. Wait, i'll make a video of my troubleshoot
4. Yes, Ive declared of $id_user as array in public property, but sometime it's working and it's not

**Comment by groxw** [comment]
Here's the video : https://www.youtube.com/watch?v=RPkp-1rg8GI
I upload it in youtube because the github said that the video is too big.

here's my function of editData($id)

    public function editData($id)
    {
        $data = Punish::findOrFail($id);
        $this->id_punish = $data->id;
        $this->id_siswa = $data->user_id;
        $this->search();
        $this->catSearch();
        $this->id_category = $data->cat_dev_id;
        $this->name_place = $data->place_dev;
        $this->date = $data->date_act;
        $this->description = $data->deskripsi_learning;
        $this->file_info = $data->medias;
        $this->status = 'edit';
    }


and search function for search
    public function search(string $value = '') {


        if ($this->id_siswa) {
            $preUsers = User::whereIn('id', [$this->id_siswa])->get();
            $this->siswa = User::query()
                    ->where('name', 'like', "%{$value}%")
                    ->where('isTeacher', null)
                    ->take(4)
                    ->get()
                    ->merge($preUsers);
                    # code...
            } else {
            $this->siswa = User::query()
                    ->where('name', 'like', "%{$value}%")
                    ->where('isTeacher', null)
                    ->take(4)
                    ->get();

        }

    }
    public function catSearch(string $value = '') {

        // Also load selected users, besides result search
        // $preUsers = User::whereIn('id', $this->id_siswa)->get();

        if ($this->id_category) {
            $preUsers = CatDev::whereIn('id', [$this->id_category])->get();
            $this->category = CatDev::query()
                            ->where('name', 'like', "%{$value}%")
                            ->where('type_cat', 'punish')
                            ->take(4)
                            ->get()
                            ->merge($preUsers);
                    # code...
            } else {

                $this->category = CatDev::query()
                            ->where('name', 'like', "%{$value}%")
                            ->where('type_cat', 'punish')
                            ->take(4)
                            ->get();
        }


    }

**Comment by ShikamaruNaraHachidaime** [comment]
@groxw hi. Try to use wire:model.live="id_siswa"

**Comment by groxw** [comment]
It's doesnt work ...

**Comment by robsontenorio** [comment]
@groxw the selection will proper display when you add pre select items on list through query. 

Are you absolutely sure those `if/else` work as expected ? Once it falls to `else` the choices won’t have any pre selected items.

**Comment by groxw** [comment]
Yes Absolutely, but Iam using else if to see a edit, is there any suggestions to fix that? Because it's selected but it's not appear on a list

**Comment by robsontenorio** [comment]
@groxw if you can provide a minimal reproduction setup it would be easier to investigate it. Because there are many pieces on your use case and it is hard to spot it.

**Comment by robsontenorio** [comment]
@groxw  Please, follow #107
