### ISSUE TITLE
input money with no decimal digits

### ISSUE THREAD

**Issue by enricv** [robsontenorio/mary#406]
I want to use input money as a mask for large integers, but I don't see how to change the number of decimal digits (I want them to 0).

Could a parameter be defined to indicate it?

**Comment by enricv** [comment]
In my case,  will be better x-number. I was not thinking in money. I use this component  to inform stadistical integer numbers for exemple: square feet, population...  That's why  I need the mask, but no decimals and my units don't correspond to currency.

Maybe two components or a more costumizable one.

PS: Thank you for your work, your library is very good and has helped me a lot

**Comment by robsontenorio** [comment]
If you want numbers just use “<x-input />” with alpine mask 

https://alpinejs.dev/plugins/mask

**Comment by s-kitade** [comment]
I am Japanese.
Japanese yen does not require a decimal point.
So I want to eliminate the numbers after the decimal point.

**Comment by enricv** [comment]
> If you want numbers just use `<x-input />` with alpine mask
> 
> https://alpinejs.dev/plugins/mask

It worked. Thanks for your help!
