### ISSUE TITLE
add an `optgroup` to the select component

### ISSUE THREAD

**Issue by s-kitade** [robsontenorio/mary#408]
https://developer.mozilla.org/ja/docs/Web/HTML/Element/optgroup

Is it possible to add an `optgroup` to the select component?

**Comment by theChaosCoder** [comment]
With the latest web updates more fun stuff is now possible with select.
For example < img> or < hr> tags inside option.

see
https://youtu.be/_-6LgEjEyzE?t=2195
https://youtu.be/_-6LgEjEyzE?t=2010

Maybe this helps to decide how to implement optgroup (and make it future proof)

**Comment by robsontenorio** [comment]
Released , thanks to @itsmenewbie03 

https://mary-ui.com/docs/components/select#group
