### ISSUE TITLE
Select Component: Is getting a click event when clicking on the dropdown arrow the expected behavior?

### ISSUE THREAD

**Issue by willcastillo** [robsontenorio/mary#410]
Hey,

When using the select component, I am receiving two click events per interaction: One when the user click on the arrow to display the options, and the second one when they actually change the selected item.

Is this the expected behavior? Is there any clean way to bypass the first event?

Thanks,
W

**Comment by robsontenorio** [comment]
What the minimal code to reproduce it ?

**Comment by willcastillo** [comment]
Just adding something like this to a template:
```Blade
    @php
        $data = [
            ['id' => 1, 'name' => 'One'],
            ['id' => 1, 'name' => 'Two']
        ];
    @endphp

    <x-select :options="$data" wire:click="clicked" />
```
And this to a controller should let you repro the issue:
```PHP
public function clicked()
    {
        Log::info('clicked!');
    }
```

**Comment by robsontenorio** [comment]
What do you intend to accomplish?

**Comment by willcastillo** [comment]
I need the clicked() method to be called only when the selected option actually changes, not just when the user click on the arrow to display the available options.

**Comment by robsontenorio** [comment]
I am afraid we can’t change this behavior, because this is a Livewire with for “wire:click”, that is triggered when you click any part of component. 

This also happens with native HTML “select”. Indeed “X-select” uses it.

**Comment by willcastillo** [comment]
Thank you.
