### ISSUE TITLE
w-full on Tabs container

### ISSUE THREAD

**Issue by wishborn** [robsontenorio/mary#411]
I think the Tabs component would work better if the Alpine container that holds all of the tabs had the w-full class on along with the "relative" class. Without it, the contents of the tabs are squished to the length of the Tabs row on the top.

**Comment by wishborn** [comment]
```
<div
    x-data="{
            tabs: [],
            selected:
                @if($selected)
                    '{{ $selected }}'
                @else
                    @entangle($attributes->wire('model'))
                @endif
                ,
                init() {
                    // Fix weird issue when navigating back
                    document.addEventListener('livewire:navigating', () => {
                        document.querySelectorAll('.tab').forEach(el =>  el.remove());
                    });
                }
    }"
    class="relative w-full"
>
```

**Comment by robsontenorio** [comment]
Could you send a print of current behavior and what do you intend to accomplish ?

**Comment by wishborn** [comment]
Here is what this screen looks like with the w-full added to the tab component. (copied your code with the modification into a component I created)
![image](https://github.com/robsontenorio/mary/assets/461446/fc3ccc7d-818a-4658-9d24-708c6d01ad61)
and here is what it looks like without it.
![image](https://github.com/robsontenorio/mary/assets/461446/c6de9877-4ba0-4e66-8b22-467f305f3e5b)

**Comment by robsontenorio** [comment]
Could send a PR for change it to w-full ?

**Comment by wishborn** [comment]
ok done, I think. I am new to contributing on git-hub so my apologies if I didn't do it correctly.
