### ISSUE TITLE
Error message for Signature component doesn't show error messages

### ISSUE THREAD

**Issue by Karadox** [robsontenorio/mary#412]
### maryUI version

1.30.0

### daisyUI version

4.10.2

### Livewire version

3.4.11

### What browsers are affected?

Chrome

### What happened?

The signature component doesn't seem to show error messages.

My validation rules are

```php
    #[Validate('required|string|between:6000,65535')]
    public string $signature;
```

and the blade code is
```blade
<x-mary-signature wire:model.change="signature" required hint="Please, put your authograph for legal purposes." />
```
And they show up in the full error bag display, but not below the signature field.

The code seems different from say the input component:

**Signature**
```blade
@error($modelName())
  <div class="{{ $errorClass }}" x-classes="text-red-500 label-text-alt p-1">{{ $message }}</div>
@enderror
```

**Input**
```blade
@if(!$omitError && $errors->has($errorFieldName()))
  @foreach($errors->get($errorFieldName()) as $message)
    @foreach(Arr::wrap($message) as $line)
       <div class="{{ $errorClass }}" x-classes="text-red-500 label-text-alt p-1">{{ $line }}</div>
       @break($firstErrorOnly)
    @endforeach
    @break($firstErrorOnly)
  @endforeach
@endif
```

Did I find a bug or should it work for the signature code as well?

**Comment by robsontenorio** [comment]
Could you send a screenshot about how it displays the validation message?

**Comment by Karadox** [comment]
**Required case**
![image](https://github.com/robsontenorio/mary/assets/8844859/17d1be62-92d0-4c0c-a2a4-e0ad234457cc)

**Between case**
![image](https://github.com/robsontenorio/mary/assets/8844859/42741cd5-7894-4ecd-b676-09e640d71111)

**Comment by robsontenorio** [comment]
You are right. We should add multiple validation messages like x-input. 

I didn’t realized people would use multiple validation rules in here.

**Comment by Karadox** [comment]
Just noticed it also doesn't show a label. Is it an idea to make this more similar to a regular input?

**Comment by robsontenorio** [comment]
It would be nice. If you are able , please send a PR to include label (regular) and multiple validation messages.

**Comment by Karadox** [comment]
I was busy creating the pull request, but unfortunatly the multiple validation messages isn't the problem, it's the wire:ignore that prevents updating the whole component from updating and showing the errors.
I'm not that capable to circumvent this other then moving the error part outside of the element with wire:ignore.

**Comment by robsontenorio** [comment]
Just create an outer wrapper div. So, it will be outside the wire:ignore part.
