### ISSUE TITLE
QUESTION: Customize MenuItem activation by route behavoir

### ISSUE THREAD

**Issue by itsmenewbie03** [robsontenorio/mary#416]
Is there a way to override how the menu item gets activated when `activate-by-route` is turned on?

Currently I'm facing in issue in this piece of code:
```blade
<x-mary-menu-sub title="Attendance" icon="o-clipboard-document-list">
    <x-mary-menu-item title="Start Attendance" icon="o-rocket-launch"
        link="{{ route('attendance.index') }}" />
    <x-mary-menu-item title="View Attendances" icon="o-document-text"
        link="{{ route('attendance.list') }}" />
</x-mary-menu-sub>
```

when im in the `attendance.index` route the menu makes sense
![image](https://github.com/robsontenorio/mary/assets/89230263/af50c5da-b886-42d9-977a-bef854c58b1b)
however when i'm in `attendance.list` both the sub items gets active
![image](https://github.com/robsontenorio/mary/assets/89230263/d6b244cf-ebc9-4e00-9928-61b08881771b)

**Comment by dgtvc** [comment]
Hi @itsmenewbie03 
Add another param with name route, for example: 
```html
<x-mary-menu-sub title="Attendance" icon="o-clipboard-document-list">
    <x-mary-menu-item 
        title="Start Attendance" 
        icon="o-rocket-launch"
        link="{{ route('attendance.index') }}" 
        route="attendance.index"
    />
    <x-mary-menu-item 
        title="View Attendances" 
        icon="o-document-text"
        link="{{ route('attendance.list') }}" 
        route="attendance.list"
    />
</x-mary-menu-sub>
```

Or it you want to catch more simple add * sign. `route="clients.*"`

**Comment by itsmenewbie03** [comment]
Thanks you, this solves the issue.
