### ISSUE TITLE
bind array to datpicker and money elements

### ISSUE THREAD

**Issue by behvandi11** [robsontenorio/mary#418]
### maryUI version

1.30.3

### daisyUI version

4.11.1

### Livewire version

3.4.12

### What browsers are affected?

Firefox, Chrome

### What happened?

Hello. Good time
In the Date Picker and Input(money type) components, when I use an array type for wire:model I face with error in console log. (Alpine Expression Error: missing } after property list)
since $wire.property could not access to array by dot(.) this error occurs, while in wire model needs to use dot(.) for example: 
```blade
wire:model="$wire.sale.0.start"
```
![mary-datpicker](https://github.com/robsontenorio/mary/assets/75178945/2eea1208-e009-4553-9b35-618169784872)

```php
public array $sale = [
     0 => ['price' => '', 'start' => ''],
];
```

```blade
<x-input
      label="Sale Price"
      wire:model="sale.0.price"
      money
 />
        
<x-datepicker
    label="Sale Date"
    wire:model="sale.0.start"
    icon="o-calendar"
/>
```
the problem arises because of $wire.modelName.
 in Date Picker at setup method.
```php
$config = str_replace('"#model#"', '$wire.' . $this->modelName(), $config);
```

and in money input problem created at 106 and 118 lines:
```php
106  x-data="{ amount: $wire.{{ $modelName() }} }"
118  @input="$nextTick(() => $wire.{{ $modelName() }} = Currency.getUnmasked())"
```
maybe $wire.entangle instead $wire.modelName will be solved this problem
thanks

**Comment by robsontenorio** [comment]
It works if you change to something like this.

```php
public array $sale = [
        'some' => ['price' => '12.2', 'start' => ''],
    ];
```
```html
<x-input
      label="Sale Price"
      wire:model="sale.some.price"
      money
 />
```

But need to investigate if this is Alpine restriction about indexed nested model `sale.0.price`

**Comment by robsontenorio** [comment]
Unfortunately it was reverted because of #431 

It breaks the number format.

**Comment by behvandi11** [comment]
ooops. You are right. I made changes that I think solved the problem and there should be no problem in the case of indexed nested array.
please check this: #434
