### ISSUE TITLE
Choices component duplicates count on selected choices on initial load and selection. 

### ISSUE THREAD

**Issue by kmaphane** [robsontenorio/mary#422]
### maryUI version

1.30.3

### daisyUI version

4.10.1

### Livewire version

3.4.12

### What browsers are affected?

Microsoft Edge

### What happened?

I have an array with 5 items hardcoded as below:

```php
    public array $statistics = [
        ['id' => 0, 'name' => 'weather'],
        ['id' => 1, 'name' => 'water'],
        ['id' => 2, 'name' => 'air_quality'],
        ['id' => 3, 'name' => 'energy'],
        ['id' => 4, 'name' => 'gas'],
    ];
```
On initial load all items are selected and passed into the property $selectedStatistics
```php
public array $selectedStatistics;

    public function mount()
    {
        $this->camps = Camp::all();
        $this->selectedCamp = Camp::first();
        $this->selectedStatistics = $this->statistics;
    }
```
The count is correct and reflect accordingly

![image](https://github.com/robsontenorio/mary/assets/80934965/a0eeef42-01de-46a8-96c6-5d08bea357ff)

When I select an item from the drop down my expectation would be that the count will reduce because you a deselecting it.

The count goes up instead:

![image](https://github.com/robsontenorio/mary/assets/80934965/281de261-226e-47f3-a2ce-54caa3dc0101)

when I dump the result in my updatedSelectedStatistics method i get the folwing:

array:7 [▼
  0 => array:2 [▼
    "id" => 0
    "name" => "weather"
  ]
  1 => array:2 [▼
    "id" => 1
    "name" => "water"
  ]
  2 => array:2 [▼
    "id" => 2
    "name" => "air_quality"
  ]
  3 => array:2 [▼
    "id" => 3
    "name" => "energy"
  ]
  4 => array:2 [▼
    "id" => 4
    "name" => "gas"
  ]
  5 => array:2 [▼
    "id" => 0
    "name" => "weather"
  ]
  6 => array:2 [▼
    "id" => 1
    "name" => "water"
  ]
]

When I select the values I selected again it removes them and the count goes back to the original count 

![image](https://github.com/robsontenorio/mary/assets/80934965/08e42d9e-0b54-42b4-aa11-ca2d8bdc3b1c)

The dump is below:

array:5 [▼
  0 => array:2 [▼
    "id" => 0
    "name" => "weather"
  ]
  1 => array:2 [▼
    "id" => 1
    "name" => "water"
  ]
  2 => array:2 [▼
    "id" => 2
    "name" => "air_quality"
  ]
  3 => array:2 [▼
    "id" => 3
    "name" => "energy"
  ]
  4 => array:2 [▼
    "id" => 4
    "name" => "gas"
  ]
]

When I reset the values or remove all selected everything works fine and the works as it should. I only have this issue on initial load. 

I have tried the following in my updated method:

```php

public function updateSelectedStatistics($selectedStatistics)
    {
        // Reset $this->selectedStatistics
        // $this->selectedStatistics = [];

        $this->selectedStatistics = collect($selectedStatistics)
            ->map(function ($statistic) {
                // If the statistic is not an array, look it up in the statistics array
                if (! is_array($statistic)) {
                    $statistic = collect($this->statistics)->firstWhere('id', $statistic);
                }

                return $statistic;
            })
            // ->unique('id')  // Remove duplicates
            ->values()  // Reset the array keys
            ->all();  // Convert the collection back to an array

        ds($this->selectedStatistics);
    }
```

Kindly advice, Thanks.

**Comment by robsontenorio** [comment]
The `x-choices` uses an array on IDs, to control what is selected. Take a deep look on docs samples.

```
$this->selectedStuff = [14, 28, 312];
```

**Comment by kmaphane** [comment]
Okay thanks much appreciated. Will change to that.
