### ISSUE TITLE
3rd party component for PDF.js

### ISSUE THREAD

**Issue by rabol** [robsontenorio/mary#423]
Hi

It would be cool to see a component for PDF.js -https://mozilla.github.io/pdf.js/

**Comment by robsontenorio** [comment]
It just shows a PDF preview inside a canvas? 

What part is relevant for you?

**Comment by rabol** [comment]
sure, it is 'just' a PDF viewer, but there is so many options and it would be nice to have 'simple' all included component with easy to set options so that one does not need to create a special js to get it working.

e.g. the calendar component is also 'just' a calendar :)

**Comment by robsontenorio** [comment]
I will give a try soon.

**Comment by robsontenorio** [comment]
After digging its docs a lot I could not figure out a way to make it generic for many uses cases, once it dependes of a heavy JS customization for each use case.

Closing this for now.

<img width="1203" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/e527f3b9-1003-4e3b-8c06-711cc1bda2d2">
