### ISSUE TITLE
Currency Input

### ISSUE THREAD

**Issue by e-smily** [robsontenorio/mary#425]
### maryUI version

website

### daisyUI version

website

### Livewire version

website

### What browsers are affected?

Firefox

### What happened?

I got problems with the currency-input displayed on your website.
The curser always jumps to the end of the input and i am not possible to make any inputs.
Maybe change this to the [alpine mask-plugin ](https://alpinejs.dev/plugins/mask) ?

**Comment by robsontenorio** [comment]
It works here on live docs sample 

https://mary-ui.com/docs/components/input#currency

**Comment by e-smily** [comment]
Unfortunately not for me, I have no idea why
If I place the cursor in the input or press keys, the cursor immediately jumps to the end of the input, no marking of text is possible
I can only move from the end of the input to a place in the input using the arrow key, but as soon as a key is pressed the cursor jumps straight back to the end. The number was inserted in the right place, but a sensible input is not possible ..

**Comment by robsontenorio** [comment]
It is not supposed to use with cursor. 

It always goes to the end. 

If you type “123” it becomes “1.23”
if you type “12300” it becomes “123.00”

As alternative , if don’t want this behavior, you can use a raw input with alpine mask.
