### ISSUE TITLE
Create a discord server or slack channel

### ISSUE THREAD

**Issue by rabol** [robsontenorio/mary#428]
Hi

I don't know how many that is using Mary UI so this suggestion might not be relevant

what about a discord server or a slack channel ?

**Comment by robsontenorio** [comment]
Well, I can create it but a I am not able to moderate it.

If you accept this role, let's do it !

**Comment by rabol** [comment]
Let's do it :)

I will chip in once the base is created - thanks

**Comment by robsontenorio** [comment]
@rabol 

https://discord.gg/YyFR8dnQ

say hello
