### ISSUE TITLE
QUESTION: how to support all daisyui's themes?

### ISSUE THREAD

**Issue by itsmenewbie03** [robsontenorio/mary#429]
I want to implement a theme switcher, the theme switching works perfectly fine. However the tailwind css `dark:` still applies despite selecting a light theme.
For context
```js
window.matchMedia('(prefers-color-scheme: dark)').matches
```
evaluates to true. So it's understandable that `dark:` would apply.
I tried to play around with `tailwind.config.js` but no luck.

**Comment by robsontenorio** [comment]
It is because “x-theme-toggle” is supposed to switch between light and dark variant themes. 

If you want to have a combo box with many themes to select, don’t use x-theme-toggle. 

Just refer to daisyUI docs to see how to perform it, without maryUI.

**Comment by itsmenewbie03** [comment]
I'm using [theme-change](https://github.com/saadeghi/theme-change) and this is my code
```blade
<x-mary-select data-choose-theme icon="o-sparkles" option-value="value" option-label="label" :options="$this->themes"
            inline
            hint="Explore more themes! Change your device's settings to unlock new options. Click refresh after changing." />
```
I somehow was able to make a workaround that works by making a preload page. the preload page checks if the users prefers dark or light mode using 
```blade
    @script
        <script>
            if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                console.log('dark mode');
                $wire.$set('prefersDarkMode', true);
                return;
            }
            $wire.$set('prefersDarkMode', !true);
        </script>
    @endscript
```

then it redirects to the actual theme switcher page
```php
    public function rendered()
    {
        if (is_null($this->prefersDarkMode)) {
            // NOTE: the `prefersDarkMode` is not set, so we need to set it
            // this means the script did not ran yet xD
            return;
        }
        sleep(1);
        return $this->redirectRoute('customizations.theme', ['prefersDarkMode' => $this->prefersDarkMode]);
    }
```

This works but a bit overkill for a simple feature.

**Comment by robsontenorio** [comment]
Daisy docs suggests do it like this. 

https://daisyui.com/docs/themes/
