### ISSUE TITLE
Question: Is it possible to insert a link in the label attribute of a checkbox component?

### ISSUE THREAD

**Issue by localdisk** [robsontenorio/mary#43]
Hi @robsontenorio 

Thank you for creating such a great package. I have a question.
Is it possible to insert a link in the label attribute of a checkbox component?

Ver: 0.38.1

```
<x-checkbox label="insert link" wire:model="form.remember" />
```

usecase

![image](https://github.com/robsontenorio/mary/assets/4827406/cbdceabf-e47d-4baf-9479-c31dc0593aad)

**Comment by robsontenorio** [comment]
Currently is not possible :(

I am curious why would you need a checkbox for a "forgot password". Why not just a link instead?

**Comment by localdisk** [comment]
thank you. That use case is certainly strange. 🤔 

Please close this issue.
