### ISSUE TITLE
Table: selectable with with-pagination not working on next page.

### ISSUE THREAD

**Issue by ANJANS** [robsontenorio/mary#430]
### maryUI version

1.30

### daisyUI version

4.7.3

### Livewire version

3.4

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

**Works only if refresh the page!**

https://github.com/robsontenorio/mary/assets/22216968/84be4393-7167-4448-a7de-0aef6a58a11b

**Comment by ANJANS** [comment]
Works only if refresh the page!

**Comment by robsontenorio** [comment]
Any errors on browser console ?

**Comment by robsontenorio** [comment]
Ok, got it. The issue is with "select all". Because, individual row selections works fine with pagination.
