### ISSUE TITLE
Currency input

### ISSUE THREAD

**Issue by lucas-davi** [robsontenorio/mary#431]
### maryUI version

1.30.5

### daisyUI version

4.11.1

### Livewire version

3.4.12

### What browsers are affected?

Chrome

### What happened?

Hello!!

I'm using the currency input but the locale not apply correctly

my code:

```php
<x-mary-input label="Custom money" money inline locale="pt-BR" />
```

result:

![image](https://github.com/robsontenorio/mary/assets/60628727/d9e03eef-9be3-4cfd-8950-453820182263)

after writing in the field:

![image](https://github.com/robsontenorio/mary/assets/60628727/829a3196-abc5-4524-ace9-73e1e92bd200)

the comma becomes a point

sorry my bad english.

thanks for the help 😊

**Comment by lucas-davi** [comment]
> Have you imported the Currency library ? Any errors on console ?
> 
> The live example on docs is working fine , right ?

I imported it and there are no errors in the console.

the example gives the same error.

**Comment by robsontenorio** [comment]
Fixed on latest release.
