### ISSUE TITLE
[Feature]: Use of a table prefix in database.php by DB::getTablePrefix()

### ISSUE THREAD

**Issue by DeRaja** [robsontenorio/mary#436]
Dear Mr. Robson!

Using DB prefix in the /config/database.php in themes by entering a value 'prefix' => 'xxx_', is not working. 

By the DB::getTablePrefix(), it will help everyone to use a prefix.

Thanks.

**Comment by robsontenorio** [comment]
Sorry, this repository is about maryUI components source code.
