### ISSUE TITLE
table.php

### ISSUE THREAD

**Issue by andrew-m-p** [robsontenorio/mary#438]
Hi, 
would you consider an option to make actions usable in the first column or last column of a table, maybe by using @actions_before and @actions_after

```php
<!-- ACTIONS -->
@if($actions_before)
    <td class="text-right py-0" @click="event.stopPropagation()">{{ $actions_before($row) }}</td>
@endif

 

<!-- ACTIONS -->
@if($actions_after)
    <td class="text-right py-0" @click="event.stopPropagation()">{{ $actions_after($row) }}</td>
@endif

```
Thanks

**Comment by robsontenorio** [comment]
Actually you can “override” any column content by using fake columns. 

See 

https://mary-ui.com/docs/components/table#cell-slot

Adding “actions” on first column would be “problematic” , because the very first column is dedicated to selectable/expandable features.

**Comment by andrew-m-p** [comment]
Sure but the reason I suggested it is that if you have many columns and you keep row ht fixed you end up with horiz. scroll bar and you need to scroll to the actions (hidden at the end of the columns).
Thanks anyway, you have a great package that can save time.
