### ISSUE TITLE
Image Library on mobile

### ISSUE THREAD

**Issue by ades4827** [robsontenorio/mary#439]
### maryUI version

1.30.6

### daisyUI version

4.11.1

### Livewire version

3.4.12

### What browsers are affected?

Chrome

### What happened?

I was using this wonderful package, but when I used the mobile version on my Samsung (with Chrome) I realized that I can no longer delete or crop images. as if with each click I was trying to use the sort of images even if I try to use precision with my finger. Does it only happen to me? I'd like to use this component but if it doesn't work on a smartphone I'm screwed. The official demo doesn't work either so I rule out it being a problem with my project

**Comment by itsmenewbie03** [comment]
are you using the `x-image-library` component? I tested the official demo on my phone and I can't replicate the issue. I can do crops and deletes with no issues.

**Comment by ades4827** [comment]
Yes, I'm testing the `x-image-library` via my Android phone (I've also tried on other phones) with Google Chrome


https://github.com/robsontenorio/mary/assets/27701869/5758d206-25f6-46f4-b461-2f20d2ba4e4c

**Comment by itsmenewbie03** [comment]
I tried repeating what you did on my Android Phone(currently on Android 11) using chrome but things are working fine.

**Comment by ades4827** [comment]
But it doesn't work for me as you saw from the video. The only difference perhaps is that I tried with the latest version of Android 14

**Comment by itsmenewbie03** [comment]
https://github.com/robsontenorio/mary/assets/89230263/34d151d6-cfb9-47c0-8d2f-0444043743ec

**Comment by itsmenewbie03** [comment]
> But it doesn't work for me as you saw from the video. The only difference perhaps is that I tried with the latest version of Android 14

That might be the case, could you try eruda and check for the console output? It might help.

**Comment by ades4827** [comment]
I just tried with eruda and there are no errors in the console. However, I noticed that when I add new media with my version of Andoid I can't even choose the camera (in your video you can choose to take photos)

**Comment by itsmenewbie03** [comment]
I sadly don't have any access to an mobile phone with Android Version 14. You could play around with the source by following the [Contribution Guide](https://mary-ui.com/docs/contributing#contributing) and this [relevant so question](https://stackoverflow.com/questions/77876374/html-input-type-file-not-working-to-pull-up-camera-for-pixel-android-14-comb).

**Comment by ades4827** [comment]
@itsmenewbie03 I created a [pull request](https://github.com/robsontenorio/mary/pull/440) that fixes the issue on my device. what do you think?

**Comment by itsmenewbie03** [comment]
> @itsmenewbie03 I created a [pull request](https://github.com/robsontenorio/mary/pull/440) that fixes the issue on my device. what do you think?

If it does work on you then all we have to do is wait for the owner to merge the PR 💜
