### ISSUE TITLE
Request: remove `input-primary` attribute

### ISSUE THREAD

**Issue by localdisk** [robsontenorio/mary#44]
hi @robsontenorio 

`<x-input>` element I would like to remove input-primary from the default attribute.

If you want to create a normal text input, you have to remove the input-primary attribute, but I don't think Blade Component has a way to do that.

Therefore, I would like to remove the input-primary attribute and do the following when using the component.

`<x-input label="Email" class="input-primary" />`

**Comment by robsontenorio** [comment]
@localdisk I just wanna keep it close to daisyUI design system standards. So, for now I will keep as it is.

But, you can overcome this in many ways. Here is one option.

**app.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.no-border {
    @apply border-base-300
}
```

**When you don't want primary style.**

```html
<x-input label="Email" class="no-border" />
```


**When you want default primary style.**

```html
<x-input label="Email" />
```

**Comment by localdisk** [comment]
@robsontenorio thanks! I will implement it this way

**Comment by localdisk** [comment]
thanks  close this issue.
