### ISSUE TITLE
Violating node issue with x-toggle component 

### ISSUE THREAD

**Issue by m-canton** [robsontenorio/mary#454]
### maryUI version

1.31.3

### daisyUI version

4.11.1

### Livewire version

3.5.0

### What browsers are affected?

Opera

### What happened?

x-toggle component needs `id` and `for` attributes to avoid **violating node** issue. I can see this in official doc examples.

On the other hand, it doesn't let me choose my browser here, which is Opera. I have edited it after.

**Comment by robsontenorio** [comment]
What is the code to reproduce this ?

**Comment by m-canton** [comment]
> What is the code to reproduce this ?

You can go to official docs and open dev tools. Your website has the code.

![image](https://github.com/robsontenorio/mary/assets/59761854/d104d4cd-b940-4835-bb51-c07dcf9195b8)
