### ISSUE TITLE
TTY Mode Not Supported on Windows Platform

### ISSUE THREAD

**Issue by BaranSaeed** [robsontenorio/mary#46]
I attempted to run php artisan mary:install on a Windows platform and encountered the following error:

```bash
Symfony\Component\Process\Exception\RuntimeException
TTY mode is not supported on Windows platform.
```

Steps to Reproduce:

Install a fresh Laravel application with Jetstream starter kit including teams using the Laravel installer version 5.0.0.
Run `php artisan mary:install`.

**Comment by robsontenorio** [comment]
Hey @BaranSaeed !

Under the hood it uses [Laravel Processs](https://laravel.com/docs/10.x/processes#main-content) to run terminal commands. Maybe you need to install some extra lib to you PHP/Laravel env. I don't use Windows 😢 


It is not related to above, but the command `mary:install` is supposed to be used on a fresh project, **without any starter kit**. I suggest you use Mary manual install. I haven't tested Mary + starter kits.

**Comment by BaranSaeed** [comment]
Okay got it thanks
