### ISSUE TITLE
Progress loading indicator is always running. 

### ISSUE THREAD

**Issue by sayasuhendra** [robsontenorio/mary#468]
### maryUI version

^1.30

### daisyUI version

^4.11.1

### Livewire version

^3.4

### What browsers are affected?

Chrome

### What happened?

<img width="1121" alt="image" src="https://github.com/robsontenorio/mary/assets/4870292/fc09cf07-d399-4375-9e99-d82157eba123">

**Comment by robsontenorio** [comment]
Is this a fresh project ?
Are there any erros on browser console ?

**Comment by sayasuhendra** [comment]
Yes this is a fresh project and there is no error message on console. 

I try to follow your bootcamp https://mary-ui.com/bootcamp

is there any state or data that used by this progress indicator?

**Comment by robsontenorio** [comment]
The progress bar is triggered only if there is a network call in progress. 

Make sure you didn’t miss some close html tags.

**Comment by sayasuhendra** [comment]
<img width="666" alt="image" src="https://github.com/robsontenorio/mary/assets/4870292/10c4ff12-25f2-4c57-af5b-f5d3fa9fb505">

fixed now. I'm sorry. I used manual livewire and alpinejs loading, I forgot to add @livewireStyles

**Comment by robsontenorio** [comment]
This approach is not intended be used on Bootcamp.  Because there is a way to install automatically. 

But , glad you solved.
