### ISSUE TITLE
Named route in table link property

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#471]
Hi @robsontenorio 

i have a table component where i would like to use a named route in the link property, but the {id} is not accessible

```
@php              
    $headers = [
        ['key' => 'id', 'label' => 'Doc. Id'],
        ['key' => 'user.name', 'label' => 'User'],
        ['key' => 'state', 'label' => 'State'],  
        ['key' => 'created_at', 'label' => 'Created at'] 
    ];
@endphp                
<x-mary-table :headers="$headers" :rows="$this->vpns()" :sort-by="$sortBy" 
    wire:model="selected" selectable with-pagination
    link="{{route('doc-review', ['docType' => 'vpn', 'id' => '{id}'])}}"    
>

</x-mary-table>

```

**Comment by robsontenorio** [comment]
What plain text url it outputs ? For  yours `{{ route(xxx) }}`

**Comment by bucari** [comment]
Url like this 
http://hostname/doc/vpn/review/1

**Comment by robsontenorio** [comment]
What final html/table/tr/td/a code it  renders for your link attribute?

![image](https://github.com/robsontenorio/mary/assets/118955/219b307f-7e62-4713-b528-09c0cb9025a2)

**Comment by robsontenorio** [comment]
But this error comes from Laravel itself if you try to print that route, not specifically for table component.

**Comment by bucari** [comment]
No this error occurs because {id} token is not evaluated inside this {{route(...)}}, it works olny if i use a string in link parameter

**Comment by robsontenorio** [comment]
There is no other way to handle this, as you are trying to use “route()” method. 

For now, please  use it as string.
