### ISSUE TITLE
HELP with <x-input />

### ISSUE THREAD

**Issue by LucasCavalheri** [robsontenorio/mary#472]
### maryUI version

1.32

### daisyUI version

4.12.2

### Livewire version

3.5

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

How i can change this "border, outline" (i dont know) color of the input?
![Captura de tela de 2024-06-07 19-10-26](https://github.com/robsontenorio/mary/assets/104279631/1a72af45-f90d-4686-947c-bbc6c606f863)

**Comment by robsontenorio** [comment]
All styles comes from daisyUI. See its docs to check how to change theme variables as "primary color", "rounded", "focus" ... 

https://daisyui.com/docs/themes/


![image](https://github.com/robsontenorio/mary/assets/118955/9b9dcf7c-14ad-46b5-ab4f-43a68c569a68)
