### ISSUE TITLE
Improve the select drop-down with an input field, for example, to search remote data.

### ISSUE THREAD

**Issue by gerardp** [robsontenorio/mary#474]
https://select2.org/searching
![Captura de pantalla 2024-06-09 a las 22 38 11](https://github.com/robsontenorio/mary/assets/168353/e1dc19fc-8fe5-4cfe-968d-4d1f8c60c217)

https://tom-select.js.org/examples/remote/
![Captura de pantalla 2024-06-09 a las 22 36 38](https://github.com/robsontenorio/mary/assets/168353/1fdb9667-4208-4742-9250-16fb63181f15)

**Comment by mustaqim224** [comment]
I think you can use the choices component (https://mary-ui.com/docs/components/choices), it has server side searching functionality.

**Comment by gerardp** [comment]
Thank you, I hadn't thoroughly reviewed the documentation; choices is perfect.
