### ISSUE TITLE
Automatic installation does not work

### ISSUE THREAD

**Issue by rabol** [robsontenorio/mary#48]
CSS is not build and the welcome page looks strange.

This is on a completely new laravel app

1) laravel new testapp
2) cd testapp
3) composer require robsontenorio/mary
4) php artisan mary:install
5) npm run dev / npm run build

the generated css looks like this:

```
@tailwind base;@tailwind components;@tailwind utilities;
```

It looks like the install command does not install tailwind etc

**Comment by robsontenorio** [comment]
@rabol 

1) Are you on windows?  (format issue)
2) For now automatic installer uses `yarn` ... Could you try `yarn dev` ?

**Comment by rabol** [comment]
I don't use yarn
