### ISSUE TITLE
When I use sidebar and use sub-menu , if I click on a sub menu item it closes the sub menu instead of the maintaining the state

### ISSUE THREAD

**Issue by shadmanshaikh** [robsontenorio/mary#481]
### maryUI version

1.26

### daisyUI version

4.10.1

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

In app.blade

I have sub-menu and its sub-menu-item , when I click on the sub-menu it closes instead of being in the same state

this is a standard code used by me from the MaryUI docs:
`
<x-menu-sub title="Settings" icon="o-cog-6-tooth"> 
    <x-menu-item title="Wifi" icon="o-wifi" link="####" />
    <x-menu-item title="Archives" icon="o-archive-box" link="####" />
</x-menu-sub>
`

**Comment by bestmomo** [comment]
Read [this doc item](https://mary-ui.com/docs/components/menu#active-state). There are two ways to activate menu:

1. use **active** attribute
2. use **activate-by-route** attribute (your routes must match in this case)

**Comment by shadmanshaikh** [comment]
active attribute does work for x-menu-sub , if i use for x-menu-item it show's the sub menu item by default its active , I just to open a dropdown and when clicked it should go to the link and **should not close the dropdown**

>

**Comment by robsontenorio** [comment]
If you are using it on Dropdowns see this

https://mary-ui.com/docs/components/dropdown#click-propagation

**Comment by shadmanshaikh** [comment]
no I'm not using dropdown im using <x-menu-sub>

**Comment by shadmanshaikh** [comment]
I'm using `<x-menu-sub>`

**Comment by shadmanshaikh** [comment]
this is my original code : 

`<x-menu activate-by-route><x-menu-sub  title="Tasks" icon="o-clipboard-document-list"  >
                        <x-menu-item title="Todo List" icon="o-document-text" href="todo-list" wire:navigate="todo-list" />
                        <x-menu-item title="Task Assigned" icon="o-clipboard-document-check" link="task-assigned" /> </x-menu-sub>    </x-menu>`

**Comment by robsontenorio** [comment]
Please, read carefully the Menu docs, about the correct usage of the `link="..."`. 

- You shouldn't  use `href` or `wire:navigate`
- Also, the routes must follow a pattern to make it auto activate. 

https://mary-ui.com/docs/components/menu
