### ISSUE TITLE
Masks in inputs

### ISSUE THREAD

**Issue by rwrodrigoa** [robsontenorio/mary#484]
Firstly congratulations @robsontenorio, it’s an incredible project!!!

Is there any way to create a mask for a input? For example to enter CPF/CNPJ or phone numbers?

**Comment by robsontenorio** [comment]
You can use alpine mask, it is built in. 
https://alpinejs.dev/plugins/mask

`<x-input x-mask=“99.999.999” …/>

**Comment by rwrodrigoa** [comment]
Perfect! I didn't know about this AlpineJs solution.

Thanks!
