### ISSUE TITLE
no-separator attribute not working

### ISSUE THREAD

**Issue by elnasnato** [robsontenorio/mary#504]
### maryUI version

1.32.0

### daisyUI version

4.11.1

### Livewire version

3.5.0

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

![image](https://github.com/robsontenorio/mary/assets/106455553/c5fdf0a1-971d-4274-b818-a41d900ab189)
Yes, the separator is still there. btw, i'm using breeze.

HTML/Blade

```blade
<x-mary-form no-separator>
	<x-mary-input label="Name"  />
	 
	<x-slot:actions>
		<x-mary-button label="Cancel" />
		<x-mary-button label="Click me!" class="btn-primary" type="submit" spinner="save" />
	</x-slot:actions>
</x-mary-form>
```

**Comment by robsontenorio** [comment]
Update maryUI to latest version.
