### ISSUE TITLE
The overlay backgroudn of a  drawer (rightside) which should be transparent is showing dark background

### ISSUE THREAD

**Issue by shadmanshaikh** [robsontenorio/mary#506]
### maryUI version

1.26

### daisyUI version

4.10.1

### Livewire version

3.4

### What browsers are affected?

Chrome

### What happened?

The background of the drawer is showing black background instead of transparent
![Screenshot 2024-06-24 113928](https://github.com/robsontenorio/mary/assets/51903579/6ef09356-ea0e-46cd-bdd1-5e8370d073ce)

**Comment by robsontenorio** [comment]
Does it works fine on docs site?

If so, you have some custom CSS that is causing the issue. 


https://mary-ui.com/docs/components/drawer
