### ISSUE TITLE
Style issue on date input

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#514]
### maryUI version

demo

### daisyUI version

demo

### Livewire version

demo

### What browsers are affected?

Chrome

### What happened?

Double calendar icon render issue on datepickers - seen in the fields > datepicker demo 

Spotted in the most recent Chrome on the latest mac os (desktop):

https://capture.dropbox.com/ApqjouNX6fs0PxaJ

I wasn't sure if I should flag it here or daisyUI 

Thanks :)

**Comment by flatcapco** [comment]
Also whilst here and to save opening another ticket, I think the icon decision on the "password" field is potentially a bad pattern. The eye usually indicates that you can click to reveal the passwords obfuscation, so people may try to click it

**Comment by robsontenorio** [comment]
The icons are optional. You can change or remove  them.
