### ISSUE TITLE
Add Toast primary background color

### ISSUE THREAD

**Issue by nerisonpitogo** [robsontenorio/mary#528]
Please add a global toast background color that follows the app theme - primary.
In this picture, we can see that the toast is not the same as the primary color. It can be done for each toast but could be better if I just call. `$this->success('User created successfully');` rather than adding class for each toast call.

 ![image](https://github.com/user-attachments/assets/6b536fac-5a37-4b88-907d-8147f1d1c4a3)
 
Something like this and each toast will have a bg-primary based on my theme.
 ` <x-mary-toast position="toast-top toast-center" class="bg-primary" />`

**Comment by nerisonpitogo** [comment]
I am planning to add switches to let user select theme they want so that toast background must be based on the primary color.

**Comment by robsontenorio** [comment]
The Toast component follows daisyUI`s design system. 

https://daisyui.com/components/toast/#toast-top-toast-start

**Comment by nerisonpitogo** [comment]
OMG. Been finding a solution for this since yesterday. Just to find out that the toast is on 'success' and my buttons are 'primary'. How to use the primary color as the background color instead of the success?

so instead of the 
`$this->success('Permissions saved successfully');`
just use
`$this->primary('Permissions saved successfully');`

**Comment by robsontenorio** [comment]
You need to have a coherent color schema where primary color must not be the same as success color.
