### ISSUE TITLE
Ability to check specific option in radio component

### ISSUE THREAD

**Issue by gdandersson** [robsontenorio/mary#529]
Either by adding the field "checked" => true to the options collection or by having a separate attribute.

**Comment by robsontenorio** [comment]
All kind of form component works with wire:model

I don’t get your point.

**Comment by gdandersson** [comment]
How do you pre-check a radio option?

**Comment by robsontenorio** [comment]
This is about Livewire

```php
public int $selectedUser =1;
```

```
<x-radio label="Select one" :options="$users" wire:model="selectedUser" />
```

**Comment by gdandersson** [comment]
Ah, my bad. I'm using it without Livewire, which in most cases work very well.

Thanks!
