### ISSUE TITLE
Choices multiple UX issues

### ISSUE THREAD

**Issue by arthurshlain** [robsontenorio/mary#54]
Hi. Just looking demos in docs and found this issues for Choices component:

1.
Cannot see initial options after choosing one. 
For example, type `Viol`, click `Violette`, 
Expected to see options `Alena`, `Alison` etc like on first focus.

2.
Cannot remove last option by pressing `backspace` when text cursor index is 0.

**Comment by robsontenorio** [comment]
@arthurshlain 

1. after you search and click an item actually I expect to keep list as it as , based on initial search , because you see anything has “Viol”. Try search “Ja”. (Jade, Jalen …)


2. Yeah, that’s a good one, will give a shot. For now you need to click to remove item.

**Comment by robsontenorio** [comment]
@arthurshlain Please, follow #107
