### ISSUE TITLE
How to initialize a base Input component without the default "input-primary"?

### ISSUE THREAD

**Issue by KozSuper** [robsontenorio/mary#541]
How to set up a base input when the default component input is "input-primary"?
Is there any way to initialize a base Input component?
I think it would be easier if it was not set to "primary" by default.

Example:
src\View\Components\Input.php
```blade
$attributes
  ->merge(['type' => 'text'])
  ->except($money ? 'wire:model' : '')
  ->class([
  'input input-primary w-full peer',
  'ps-10' => ($icon),
  'h-14' => ($inline),
  'pt-3' => ($inline && $label),
  'rounded-s-none' => $prefix || $prepend,
  'rounded-e-none' => $suffix || $append,
  'border border-dashed' => $attributes->has('readonly') && $attributes->get('readonly') == true,
  'input-error' => $errorFieldName() && $errors->has($errorFieldName()) && !$omitError
])
```

p/s: My English is quite poor, sorry.

**Comment by s-kitade** [comment]
I am resolving it this way. If there is a better solution, I would like to know.

`app.css`
```css
.border-primary {
    @apply border-gray-400;
}

.input-primary {
    @apply border-gray-400;
}

.select-primary {
    @apply border-gray-400;
}

.checkbox-primary {
    @apply border-gray-400;
}

.textarea-primary {
    @apply border-gray-400;
}

.file-input-primary {
    @apply border-gray-400;
}
```

**Comment by robsontenorio** [comment]
Thai’s the way. If you don’t want to follow de design system , just override the defaults.

**Comment by beholdr** [comment]
I think it's not very convenient to use `input-primary` class by default. It's so much easier to add this class when needed, but not so easy to remove it when you don't need it. I think neutral `input-bordered` class is much better default choice for the inputs. And you always can add `input-primary` or other classes like `input-secondary`.

I tried to override default colors of the inputs via `@apply`:

```css
.input-primary {
    @apply border-gray-400;
}
```

But in that case input has gray border even in error state. So it's really complicated to override this rules for all cases.

**Comment by beholdr** [comment]
It should be easy to make such change without breaking changes. For example, via config setting like `'primary_inputs' => true` so by default inputs will be primary, but with ability to turn it off.

If you want I can try to prepare a PR.

**Comment by flatcapco** [comment]
Agreed this should be a config option, thats a nice solution and preserves the correct styling for error states etc
