### ISSUE TITLE
Open DateTime input when clicking the input instead of only the right icon

### ISSUE THREAD

**Issue by ignaaaam** [robsontenorio/mary#545]
✅ For sure you can paste screenshots.
        
❌ Please, don't paste code as screenshot. Paste as formatted markdown code.    

Could be possible to open the DateTime when the input is clicked instead of only the right icon?    

![dateTime input](https://github.com/user-attachments/assets/fa552162-7cc1-4ab1-8305-1ddc6edc2a61)

**Comment by robsontenorio** [comment]
It already works if you click anywhere.

 https://mary-ui.com/docs/components/datetime

**Comment by ignaaaam** [comment]
Strange, it doesn't work for me. Whenever I try to click on the input to open it, it acts as if I'm trying to select text. 🙄😰

**Comment by ignaaaam** [comment]
Brave version
[Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (x86_64)](https://brave.com/latest/)

Tried on chrome too and nothing, disabled any extension that could cause any issue.

**Comment by s-kitade** [comment]
@robsontenorio 
In my environment, it does not work unless I click the icon. When I click the input field, it behaves strangely.

https://github.com/user-attachments/assets/3fac70da-385b-4395-9193-067d09db9a1e

**Comment by robsontenorio** [comment]
It works on Safari, but not on Chrome.

It seems a Chrome's  "feature" ... See a raw input date type. It has the same "issue".

MaryUI uses exactly this same input.

```html
<input type="date" class="input input-primary" />
```
