### ISSUE TITLE
Best way to extend / customise existing components

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#548]
I'd like to change the styling that is used within any component that supports hints.

Please can you share the best way to do this so I can overwrite the css class:

                @if($hint)
                    <div class="label-text-alt text-gray-400 p-1 pb-0">{{ $hint }}</div>
                @endif

**Comment by robsontenorio** [comment]
If you don’t want to follow the design system you can always override the CSS

**Comment by flatcapco** [comment]
Sorry I get that but is it best practise to do it on the class of the component to target the hint, or is it better to copy the component into my own directory and then modify it? like you would if you published a vendors views to modify? I'm just trying to be as clean as possible and not sure what the intended way would be sorry for the basic question.

**Comment by robsontenorio** [comment]
Actually , I think there is no right approach here... There is two options:

1. Just copy/paste  and modify.
2. Just override the CSS and keep the original component intact.

But I would go with (2).

**Comment by flatcapco** [comment]
Thanks @robsontenorio I just wanted to make sure I wasn't missing something. Would you consider supporting an extension of the components to replace or amend hint classes? Its just because the gray-400 is way below accessibility standards for readability on white

**Comment by robsontenorio** [comment]
@flatcapco 

I would accept a PR like this for error classes.

https://github.com/robsontenorio/mary/blob/main/src/View/Components/Input.php#L30
