### ISSUE TITLE
Prefixed daisyUI support

### ISSUE THREAD

**Issue by ahferriz** [robsontenorio/mary#561]
Add support for daisyUI prefix configuration option.
        
_Example tailwind.config.js config:_
```js
module.exports = {
  daisyui: {
    prefix: "daisy-", // prefix for daisyUI classnames (components, modifiers and responsive class names. Not colors)
  },
}
```

**Comment by robsontenorio** [comment]
I think it can't  be done for now. Because, maryUI components uses that classes from daisyUI, and we can't just prefix it internally.

If you can find any workaround let me know.

```
<input ="input input-primary" />
```

**Comment by ahferriz** [comment]
Oh, I don't mean prefix daisyUI from inside Mary. What I mean is to support daisyui's own prefix option.
I had to implement some form components in a site that already had daisyUI classes but they were prefixed using daisyUI tailwind config, so they all looked broken because MaryUI doesn't have an option to support prefixed daisyUI classes.

I was thinking something like adding a variable that takes the prefix from config and then adding it to the daisyui classes like this:

`public ?string $daisyPrefix = null;`
...
`$this->daisyPrefix = config('fa-reconciliation.daisyui.prefix');`
...
`$daisyPrefix . 'select',`
`$daisyPrefix . 'select-bordered',`
`$daisyPrefix . 'select-primary',`

I can create a PR for a couple of components next week and go from there.

**Comment by robsontenorio** [comment]
Unfortunately it brings two problems to internal components 
- readability 
-  tailwind classic dynamic class issue. 

DaisyUI must exist on your app and maryUI uses it directly. There is no an internal daisyUI for the internal components.

**Comment by miljan-aleksic** [comment]
What about keeping daisyui classes used on the component in a variable, then have a utility method that will prefix those when applied.
