### ISSUE TITLE
Server side Choices - Search text persistence 

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#563]
I don't think its currently a feature, 
but can we persist any searched text in a choices server side search (in the same way the offline choices search works)

ie on this element:

```php
            <x-choices
                label="Searchable + Single"
                wire:model="user_searchable_id"
                :options="$usersSearchable"
                option-label="full_name"
                debounce="300ms"
                min-chars="3"
                option-sub-label="email"
                single
                searchable/>
```

If I type "Bob" then the results display below but my text is wiped and i have to exit the component and then reclick it to research rather than just modifying text I've previously typed.

Thank you

**Comment by robsontenorio** [comment]
Fixed on latest version.
