### ISSUE TITLE
problem with Image Crop

### ISSUE THREAD

**Issue by artur-picoli** [robsontenorio/mary#568]
### maryUI version

1.35.4

### daisyUI version

4.4.2

### Livewire version

3.3.5

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

When I use the image without cropping with the crop, using the original, everything happens normally in the validation, but when cropping it with the crop, I get the following error message:

LeagueFlysystem UnableToRetrieveMetadata

Unable to retrieve the file_size for file at location: livewire-tmp/livewire-tmp.

I've tried changing it in livewire.php, filesystem, and I couldn't solve the problem.

Checking on my old branches, the problem started after I upgraded from version 1.33 to 1.35.

sorry my english :)

**Comment by artur-picoli** [comment]
I downgraded to version 3.5.1 of Livewire and everything works normally. In the latest version, the problem persists.

**Comment by akhmads** [comment]
Does this update (https://github.com/livewire/livewire/pull/8624) affected bug?

**Comment by artur-picoli** [comment]
@robsontenorio yes. I downgraded the livewire and it worked again.

From what I checked, the problem started after this Livewire release:

https://github.com/livewire/livewire/commit/70503b79f5db75a1eac9bf55826038a6ee5a16d5

**Comment by akhmads** [comment]
yes temporary solution by downgrading livewire to version 3.5.1
Thanks

**Comment by robsontenorio** [comment]
Yeah. I should take look it this week.

**Comment by robsontenorio** [comment]
@artur-picoli could you provide the _**minimal code**_ to reproduce it ?

**Comment by artur-picoli** [comment]
**BLADE**

<x-file class="flex flex-col justify-center mx-auto mt-10" wire:model="formCustomerEnv.logo"
    change-text="Carregar foto" crop-text="Cortar" crop-title-text="Cortar imagem"
    crop-cancel-text="Usar original" crop-save-text="Cortar"
    accept="image/png, image/jpg, image/jpeg" crop-after-change
    :crop-config="$this->config">
    <img src="{{ $url_logo != '' ? $url_logo : asset('img/default.jpg') }}"
     class="rounded-lg" style="width: 200px; height: 160px;" />
</x-file>

**PHP**

public function saveCustomerEnvironment()
    {
        $this->formCustomerEnv->validate();
        $this->formCustomerEnv->store();
        $this->js("success()");
        $this->js("modal_customer_environment.close();");
    }
    
      #[Validate(as: 'logo', onUpdate: false)]
    public $logo;

**Conditional Rule:**


    public function rules()
    {
        $tenant = Tenant::find(auth()->user()->tenant_id);

        if (!$this->logo && $tenant->logo) {
            return [];
        }
        return [
            'logo' => ['image', 'max:12288']
        ];
    }

**Comment by robsontenorio** [comment]
This is the cleanest example you can have using forms, and It works with **Livewire 3.5.4**.
Try exactly as described on this example, do not add anything. Then evolve it to see what affects in your case.

I use a clean installation, with no `livewire.php` tweaks. Try to delete it.

![image](https://github.com/user-attachments/assets/6469d6ce-7c7b-4e16-9ce8-b80f7a23c92a)


## Component

```php
<?php

use App\Livewire\Forms\MyForm;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;

new
class extends Component {
    use WithFileUploads;

    public MyForm $myForm;

    public function save()
    {
        $this->myForm->save();
    }
}; ?>
```

```blade
<div>
    <x-file wire:model="myForm.photo" accept="image/png" crop-after-change>
        <img src="/empty-user.jpg" class="h-40 rounded-lg" />
    </x-file>

    <x-button wire:click="save">Save</x-button>
</div>
```


## Form

```php
<?php

namespace App\Livewire\Forms;

use Livewire\Attributes\Validate;
use Livewire\Form;

class MyForm extends Form
{
    #[Validate(onUpdate: false)]
    public $photo;

    public function save()
    {
        $this->validate();
    }

    public function rules()
    {
        return [
            'photo' => ['image', 'max:300']
        ];
    }
}

```
