### ISSUE TITLE
Modal size issue with choices

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#571]
Sorry if I've missed it in the documentation but is there the ability to customise the modal size and/or set the z-index on choices so that it doesn't get trapped inside the modal?

https://capture.dropbox.com/Yn1Q4I0aJmo92FGJ

**Comment by robsontenorio** [comment]
Please, provide more details. I can't see what's the issue on that image.

**Comment by flatcapco** [comment]
Sorry I realised that and was just adding a video:
https://capture.dropbox.com/wKYY1jzcbNKkvYdQ

I think the expected behaviour would be for the modal to not block the overflow for the choices option ?

**Comment by flatcapco** [comment]
Just to add I know if I added class="h-96" to the container within the modal then it would force the modal to be taller but it's stylishly a bit weird having the extra white space if not needed:

https://capture.dropbox.com/wThKxOgHa4IYDfrF

Thanks

**Comment by flatcapco** [comment]
Yep its not respected sadly

**Comment by robsontenorio** [comment]
Agree with you. We should have a way to define the z-index with modals.

**Comment by flatcapco** [comment]
I'll try to take a look this week

**Comment by flatcapco** [comment]
@robsontenorio 

<x-modal boxClass="overflow-y-visible">

fixes this issue - maybe this could be the default overflow state for this class?

**Comment by robsontenorio** [comment]
Glade you got it!

I am not sure if it would break another use cases ... maryUI just uses the classes from daisyUI. So I don't know if there are another edges cases that would break.

**Comment by bucari** [comment]
Hi,
i think i have the same issue with choices in a modal

![Image](https://github.com/user-attachments/assets/70466f5d-9ed5-45cc-905f-3e71ccf32c52)

My modal is this:
```
    <x-mary-modal boxClass="overflow-y-visible" wire:model="decModal" title="Assegna DEC" persistent>
        <x-mary-form wire:submit="saveDec">
            <div>
                <livewire:docs.selects.online-select wire:model="dec_userid" label="DEC della fornitura" icon="o-user"  
                    hint="Digita almeno 3 caratteri del nome o cognome" single required  />                
            </div>  

            <x-slot:actions>
                <x-mary-button label="Annulla" @click="$wire.decModal = false" />
                <x-mary-button label="Conferma" class="btn-primary" type="submit" />
            </x-slot:actions>
        </x-mary-form>
    </x-mary-modal> 
```

using boxClass="overflow-y-visible" not fixes the issue

**Comment by bucari** [comment]
@robsontenorio it's what i did boxClass="overflow-y-visible" 
i don't see anything else, the links posted are not working anymore.

**Comment by robsontenorio** [comment]
@bucari Probably you missed adding those extra classes on safelist.


In Tailwind  v4 way looks like this

https://tailwindcss.com/docs/detecting-classes-in-source-files#safelisting-specific-utilities

**Comment by flatcapco** [comment]
@robsontenorio nope still on mary 1.4 and tailwind 3

@bucari 
```
<x-modal
    class="h-full"
    persistent
    boxClass="overflow-y-visible"
>
```

Is what I'm using also if that helps at all.

**Comment by bucari** [comment]
I'm still on mary 1.4 and tailwind 3 too, but not working using same classes

**Comment by flatcapco** [comment]
Not sure what to say sorry @bucari as it is working for me this is my full code..

```
<x-modal
    class="h-full"
    wire:model="linkCommissionJourneyModal"
    persistent
    boxClass="overflow-y-visible"
>
    {{--    <div class="h-96"> --}}
    <div>
        <x-form wire:submit.prevent="linkCommissionJourneys">
            @if (!$journeys->isEmpty())
                <x-choices
                    class="border-gray-400"
                    :label="__('Journeys')"
                    wire:model="journey_ids"
                    :options="$journeys"
                    option-label="reference"
                    option-sub-label="datetime"
                />
            @else
                <div class="font-semibold">{{ __('No journeys to add.') }}</div>
            @endif

            <x-slot:actions>
                <x-button
                    :label="__('Cancel')"
                    @click="$wire.linkCommissionJourneyModal = false"
                />
                @if (!$journeys->isEmpty())
                    <x-button
                        class="btn-primary"
                        type="submit"
                        label="Link"
                        icon="o-link"
                        spinner="save"
                    />
                @endif
            </x-slot:actions>
        </x-form>
    </div>
</x-modal>
```
