### ISSUE TITLE
Mary Ui in Production Vapor Laravel AWS Lambda

### ISSUE THREAD

**Issue by K2412** [robsontenorio/mary#573]
### maryUI version

"robsontenorio/mary": "^1.35"

### daisyUI version

"daisyui": "^4.12.10",

### Livewire version

"livewire/livewire": "^3.5",         "livewire/volt": "^1.6",

### What browsers are affected?

Chrome, Safari

### What happened?

I made a project that worked fine in local development but broke down in production. I made this site with a fresh Mary ui , Daisy ui and laravel Livewire breeze installation : https://fathomless-briars-mkkagafqjkg9.vapor-farm-b1.com 

As you can see the side bar and nav bar are not rendering correctly in addition to the buttons that create both a modal and a drawer components. All components used are direct copy and paste from the documentation no alterations. 

This is what it is meant to look like 
<img width="1435" alt="Screenshot 2024-08-13 at 8 12 09 PM" src="https://github.com/user-attachments/assets/ca7fe579-0f73-49d8-834f-fbb235b9271b">

I have already contacted Vapor support and they can't seem to figure out what is the issue. I followed standard deployment scripts and process ( here is the line that deals with npm in the build script, "npm ci && npm run build && rm -rf node_modules"). I have tried removing the tailwind form plugin. Any help in debugging would be helpful!

**Comment by robsontenorio** [comment]
I have no experience with Vapor / AWS.
But it looks like there are missing some CSS.

I advice you to try a pure maryUI app, without mixing it Breeze to test it.

On a fresh new Laravel App **(with no starter kits)**
```
composer require robsontenorio/mary
php artisan mary:install
```
... **And just deploy it**

On the other hand you can do the same for a Laravel app with Breeze, **but no maryUI.**
