### ISSUE TITLE
Choices css error

### ISSUE THREAD

**Issue by matesasesinos** [robsontenorio/mary#577]
### maryUI version

1.35

### daisyUI version

4.12.10

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

Hi, there is a css bug in the ‘choices’ component (multiple), in clear mode it shows the search box.

HTML/Blade

```blade
<div class="mb-3">
            <x-choices label="{{ __('Seleccione el / los Roles') }}" wire:model="roles_multi_ids" :options="$this->roles" />
        </div>
```

screenshot
![image](https://github.com/user-attachments/assets/a3aaa30e-6852-4b25-b0d4-7337792c7bbf)

in app.css
![image](https://github.com/user-attachments/assets/f6c013e4-c412-4175-8d9c-28a0fbb23fe4)

**Comment by robsontenorio** [comment]
I suspect you have some custom CSS. 

Just take a look on docs. It works fine in there. 
https://mary-ui.com/docs/components/choices#searchable-server

**Comment by matesasesinos** [comment]
> I suspect you have some custom CSS.
> 
> Just take a look on docs. It works fine in there. https://mary-ui.com/docs/components/choices#searchable-server

Hi Rob, I don't think I have, I fixed it with custom css but I'm pretty sure I don't have anything that interferes with Mary, here's my list of packages:

**Comment by matesasesinos** [comment]
Hi Rob, I don't think I have, I fixed it with custom css but I'm pretty sure I don't have anything that interferes with Mary, here's my list of packages:

JSON
`"require": {
        "php": "^8.2",
        "laravel/framework": "^11.9",
        "laravel/jetstream": "^5.1",
        "laravel/sanctum": "^4.0",
        "laravel/telescope": "^5.2",
        "laravel/tinker": "^2.9",
        "livewire/livewire": "^3.5",
        "robsontenorio/mary": "^1.35",
        "ryangjchandler/blade-tabler-icons": "^2.3",
        "spatie/laravel-permission": "^6.9",
        "wire-elements/modal": "^2.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "phpunit/phpunit": "^11.0.1"
    },`

**Comment by robsontenorio** [comment]
Some third party lib CSS or on your own `app.css`, can affect it.
Because the is not the default style you presented you your print. 

Thank a look on Choices presented on online docs , there is not any issue.

<img width="899" alt="image" src="https://github.com/user-attachments/assets/7df40df2-97a6-42e7-b29a-a4b4dae28f2f">
