### ISSUE TITLE
[RFC] Default style for all inputs

### ISSUE THREAD

**Issue by anfeichtinger** [robsontenorio/mary#585]
I have noticed that in some places classes like `text-gray-500` or `text-red-500` are used. To be fully compatible with (custom) daisy ui themes this should be avoided in my opinion. 

- Red classes should probably be changed to `text-error`.
- Gray classes should be replaced with either something like `text-base-content/50` or `text-neutral`.

I wanted to start a discussion if this is a welcome change. If it is I can create a pull request for it. 
Otherwise I have two approaches that could make up for it:

- Allow overriding all usages of those classes by providing classes yourself (like recently in #550).
- Use custom classes like for example `text-hint`.

Otherwise users need to globally overwrite those usages with an css selector which is not optimal as it leads to some annoying custom css styles

Please note that this could be a breaking change for some projects.

**Comment by robsontenorio** [comment]
I would like to hear people. 

But , you are right.  It is better to have compliant css class from daisy instead of “raw classes”

**Comment by flatcapco** [comment]
Yep I agree this would be a great improvement. Also for example I pretty much have a class="border-gray-400" on all inputs as the default using the primary color feels quite over opinionated. so if classes are changing I'd vote for that to be a more neutral default. The primary works very well when selected but its overpowering when there are a lot of form fields.

Screenshot to show what I'd consider a better default:
https://capture.dropbox.com/c6ucIhEdRMYzl94I

**Comment by anfeichtinger** [comment]
@flatcapco Thanks for your input on this issue.

Regarding the input style this has been discussed in #541 already. I'm not sure if that will be implemented as a default, though I would also be in favour of adding a config flag for this.

**Comment by beholdr** [comment]
Yeah, it would be great to have better support for a custom themes and ability to easy override styles. And I fully agree about more neutral colors for inputs by default. Primary colors are great to emphasize some elements, but currently it’s not so easy to do because they are hardcoded.

And for custom colors maybe it’s better to create a custom tailwind colors, like tokens in some design systems. E.g. `mary-text-primary`, `mary-text-secondary`, `mary-bg-primary`... And allow to override them with CSS vars.

**Comment by robsontenorio** [comment]
Let's try again about the default style for all inputs.

When you guys are building forms, **99% of time** you don't want to use the **primary style**?

![image](https://github.com/user-attachments/assets/eb263819-f973-4577-9dd9-0cbe00129333)


- At the **1%** you can just override it.
- Or just create a custom class for it.

```blade
<x-input label="Name" wire:model="name" class="border-gray-400 focus:border-gray-400 focus:outline-gray-400" />
```

![image](https://github.com/user-attachments/assets/57aa861c-9245-4117-a0ab-efe309cbf6b0)

**Comment by flatcapco** [comment]
99% of the time I would want to use a more neutral style. I dont ever even see a reason I'd use the primary colour unless I really wanted to draw attention to a specific field which I've never actually come across yet in many systems.

The active style with primary is great. As it draws attention to where you are inputting.

**Comment by robsontenorio** [comment]
```html
<x-input label="Name" wire:model="name" class="input-neutral" />
```

```css
.input-neutral {
    @apply border-gray-400 focus:border-gray-400 focus:outline-gray-400
}
```

**Comment by beholdr** [comment]
Same here. Almost always I want a default neutral style. Same as default `input-bordered` of daisy ui:

<img width="915" alt="SCR-20240828-ornf" src="https://github.com/user-attachments/assets/2bb91fd7-e740-4cb9-a644-9fec15b9d34e">

And in rare cases I want to highlight some inputs with `input-primary` class.

To always add an override classes is cumbersome. And overriding them via `@apply` in `app.css` as suggested in #541 overrides colors for error states too.

**Comment by flatcapco** [comment]
> ```
> <x-input label="Name" wire:model="name" class="input-neutral" />
> ```
> 
> ```css
> .input-neutral {
>     @apply border-gray-400 focus:border-gray-400 focus:outline-gray-400
> }
> ```

I get that but it seems like an anti pattern, which also becomes more of a pain on things like:

```php
<x-input label="Default money" wire:model="money1" prefix="USD" money inline />
```

**Comment by robsontenorio** [comment]
I am running out of options 😢 

Because the primary style for forms is the default and it would be huge breaking change I don't want to deal.

**Comment by flatcapco** [comment]
In this instance,  my vote is that I think its actually worth the breaking change, and I do realise the fallout that comes with that.

**Comment by beholdr** [comment]
Breaking changes could could be mitigated using a config option, like `'primary_theme' => true`.

**Comment by anfeichtinger** [comment]
I would also be in favour of making this breaking change (and adding the config option if necessary). It will not break functionality, only change the style a bit and from what I've seen most websites use neutral inputs anyways. When someone is updating their project with the new version it will be quick to also update their input styles if the don't want that.

**Comment by thiagoradice** [comment]
I've come across this exactly problem yesterday. Here is how I solved it:

`input[type=text], input[type=password], input[type=number], input[type=email], textarea{
    @apply input-secondary;
}`

Just add the input types selectors you want to change. I've gone with input-secondary styles, but you may change it for what suits you better.

**Comment by anfeichtinger** [comment]
> I've come across this exactly problem yesterday. Here is how I solved it:


This seems like a reasonable workaround. One issue, textarea alone doesn't work for me, I needed to use `textarea.textarea`.\
If this should be the official workaround as it would be a breaking change then it should be put into the docs.

What I get is that from this discussion most people would like to use the following:

```
input[type=text], input[type=password], input[type=number], input[type=email], input[type=search], textarea.textarea {
    @apply input-bordered;
}
```

This results in the following input styles (focused + default)

![image](https://github.com/user-attachments/assets/cc368475-60c6-4c22-8c4e-5a27e7a1e407)

@robsontenorio what do you think?

**Comment by flatcapco** [comment]
Is this still not an issue when it comes to a more complex styled field like currency?

**Comment by robsontenorio** [comment]
I think this will be addressed with maryUI v2 (upcoming daisyUI 5 + Tailwind 4), where I will introduce that breaking change. In a couple of days I will start the v2 branch and see how to goes. 

I see that was a mistake to make all the input field as primary.

**Comment by robsontenorio** [comment]
Please, follow 

https://github.com/robsontenorio/mary/pull/623/files
