### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by cskwrd** [robsontenorio/mary#590]
I am evaluating Laravel and Livewire for a project I'm starting and came across this project. I am under the impression the Laravel Livewire exists to encapsulate traditional frontend technologies in PHP. With that said I am trying to understand what purpose `npm run dev` plays in the development and deployment of a Laravel application. My biggest worry is that by using `maryUI` that will require me to run node (`npm run dev`) in addition to laravel (`php artisan serve`). How does running `npm run dev` interact with the Laravel application?

**Comment by robsontenorio** [comment]
This question is out of scope of this package. 

But , the “npm” part is mostly for  Tailwind build the  optimized bundle of css class. It is not for maryUI. 

For more in depth discussion I advice you to find answers in another forums like Reddit or social networks.

**Comment by cskwrd** [comment]
Ok, I think I understand. `npm run dev` would be used if I were to include other npm libraries. Thank you for your help! :smiley:
