### ISSUE TITLE
Choices in Forms

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#591]
When using a Livewire Form and the Choices field, it would be nice if we could place all the associated methods within the livewire form. 

The options field works as expected, but because the search-function expects a string it doesn't resolve to the correct method if "searchFromAddress" is within a form

```php
                <x-choices
                    :label="__('From Address')"
                    wire:model="form.from_address_id"
                    :options="$this->form->fromAddressSearchable"
                    search-function="searchFromAddress"
                    single
                    searchable/>
                    
```

This would allow the only part of the forms customisation to simply be the fields and keeps the parent component cleaner 

Thanks

**Comment by robsontenorio** [comment]
It tries to invoke a method that exists on your current component. I don't even know if Livewire allows you to invoke a function from another place.


Try this ... Livewire expects `myFuncion` be present on your current component . Am I wrong?
```
<buttton wire:click="myFuncion">
```
