### ISSUE TITLE
Rich Text Editor 

### ISSUE THREAD

**Issue by islamV** [robsontenorio/mary#593]
### maryUI version

1.35

### daisyUI version

4.12.10

### Livewire version

3.0

### What browsers are affected?

Microsoft Edge

### What happened?

 i get this  error when i use <x-editor/> 

Uncaught ReferenceError: uploadUrl is not defined
    at [Alpine] 
                tinymce.init({
                    'menubar':'file edit view format ','automatic_uploads':true,'quickbars_insert_toolbar':false,'branding':false,'relative_urls':false,'remove_script_host':false,'height':300,'toolbar':'undo redo | codesample| bold italic underline strikethrough| bullist numlist outdent indent| anchor quickimage  media   | alignleft aligncenter alignright alignjustify | preview','quickbars_selection_toolbar':'bold italic underline strikethrough | forecolor backcolor | link blockquote removeformat | blocks','browser_spellcheck':true,'plugins':'advlist autolink lists link image table quickbars  autoresize directionality codesample   image  preview media  link','file_picker_types':'file image media','license_key':'gpl',

**Comment by robsontenorio** [comment]
The docs site works fine. 

Probably you have something different on your setup.

**Comment by islamV** [comment]
Reason was i use apline js with livewire in same time
