### ISSUE TITLE
For the table component consider making an expandableCondition.

### ISSUE THREAD

**Issue by marcos-gonzales** [robsontenorio/mary#597]
For this example its based on if the follow_up_date is present in the model. Here is my table component

```
<x-table :headers="$headers"
             :rows="$prospects"
             :sort-by="$sortBy"
             expandable
             expandableCondition="follow_up_date"
             link="/prospects/{id}/edit"
             striped
             wire:key="prospect-table"
             wire:model="expanded"
             with-pagination>
```

![image](https://github.com/user-attachments/assets/c511db4c-baf0-4103-81c8-d88c86835c9f)

i just added a new public property in the constructer
```
public mixed $expandableCondition = null
```
And used it in the table loop
```
  @if($expandable)
    @if($row[$expandableCondition])
      <td class="w-1 pe-0">
        <x-mary-icon
          name="o-chevron-down"
          ::class="isExpanded({{ data_get($row, $expandableKey) }}) || '-rotate-90 !text-current !bg-base-200'"
          class="cursor-pointer p-2 w-8 h-8 bg-base-300 rounded-lg"
          @click="toggleExpand({{ data_get($row, $expandableKey) }});" />
       </td>
    @endif
@endif
```

**Comment by robsontenorio** [comment]
And how do you parse de `expandableCondition`.  I can't see it.

**Comment by marcos-gonzales** [comment]
isn't it on this line

```
@if($row[$expandableCondition])
```
so if this property exists on the model it gets rendered

**Comment by marcos-gonzales** [comment]
it would evaluate on a per row basis. so in this screenshot the first few rows don't have the column ```follow_up_date``` so they don't get the expandable icon.

and the latter do

![image](https://github.com/user-attachments/assets/eda6e08c-33c2-42ac-87ba-3254b244de83)

maybe i am missing something??

**Comment by robsontenorio** [comment]
Could please a PR?

The only change would be

FROM
```blade
@if($row[$expandableCondition])
```

TO
```blade
// works for objects and array
@if(data_get($row, $expandableCondition))
```
