### ISSUE TITLE
Animation problem and component class issue mary.

### ISSUE THREAD

**Issue by kaue-f** [robsontenorio/mary#598]
### maryUI version

1.35.6

### daisyUI version

4.12.10

### Livewire version

3.5.6

### What browsers are affected?

Chrome

### What happened?

I am having issues with input icons; the component's style only applies when I declare it using the DaisyUI format, for example: ```class="input border border-secondary"```. However, if I use it without the input class, like this: ```class="border border-secondary"```, or in any other way, the style is not applied. I am also experiencing problems with animations defined in MaryUI components; no animations occur, not even the spinner in the button component or in any other component. There are no errors displayed in the console.

![image](https://github.com/user-attachments/assets/7db70a76-405a-4371-821e-e2c0bb66ed26)
![image](https://github.com/user-attachments/assets/415b4de4-0649-4815-85f2-cb3d6a996983)
![image](https://github.com/user-attachments/assets/625df401-2acf-47f0-9526-3f7c69adb5ef)

**Comment by robsontenorio** [comment]
I suppose you have some third party CSS from other libraries, or custom `app.css`, that is interfering.

**Comment by kaue-f** [comment]
I managed to fix the error; I just needed to declare the correct folder in the tailwind.config.js file.
![image](https://github.com/user-attachments/assets/8a42e8d7-4aa1-4096-91b4-0143653c5f40)
