### ISSUE TITLE
Choices component keyboard up/down selection support

### ISSUE THREAD

**Issue by quileab** [robsontenorio/mary#599]
![image](https://github.com/user-attachments/assets/5017538e-9226-4233-a274-248d9d0ad59b)        
Just like in Spotlight
![image](https://github.com/user-attachments/assets/a6409b05-40dd-469e-b53b-7641cec6bfec)

**Comment by anfeichtinger** [comment]
#647 would fix this issue, let's see if it will be merged.

**Comment by robsontenorio** [comment]
Merged
