### ISSUE TITLE
Choices

### ISSUE THREAD

**Issue by groxw** [robsontenorio/mary#6]
Hello, I've implemented choices but there's no scroll down to select the other option, it only shows item in the page view

**Comment by robsontenorio** [comment]
@groxw  Please, share your code and more context.

**Comment by groxw** [comment]
![Screenshot_731](https://github.com/robsontenorio/mary/assets/65380713/dd9a7d06-7bf8-49b5-84d6-09843f28333c)
It has more than 50 option but it only shows 2 option,

**Comment by robsontenorio** [comment]
@groxw 

1) Could you send again first image with more height? It seems to be overflowed by the next element on screen.  

2) When you use `searchable` it is supposed to be used as async search on large lists, where user will type something to quick search an option. Personally I would limit the `search()` method to a few records like 5 to 10.

But, in any case a scroll would be useful if you would like do display dozen items.

**Comment by groxw** [comment]
![Screenshot_733](https://github.com/robsontenorio/mary/assets/65380713/c78c9811-5b74-4513-a921-bdc5f7110e01)
the function of searchable is working but, when i try to scroll down for a option, it only shows, is it possible to add scrolldown without using searchable?

**Comment by robsontenorio** [comment]
@groxw Yes, definitively I will add a scroll.

For now, just add extra height at end of this page, to make more room to display more items.

Here

<img width="799" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/ef6580bf-4040-43a7-93c4-e2972077a4dc">

**Comment by groxw** [comment]
Thank you, it is amazing package i think,

**Comment by robsontenorio** [comment]
@groxw Jost released `0.33.2`. Please, update and let me know if everything is ok.

Note: In your case I will need extra room at end of page anyway. Because it is the last element of screen.

**Comment by groxw** [comment]
`  Problem 1
    - Root composer.json requires robsontenorio/mary ^0.32.2, found robsontenorio/mary[dev-choices-improvements, dev-fix-toast, dev-wip-calendar, dev-main, dev-toast, 0.22.0, ..., 0.33.2] but it does not match 
the constraint.
`

when i try to update i found

**Comment by robsontenorio** [comment]
@groxw  Do not try manually change `composer.json`. Update package means install it again with `composer require robsontenorio/mary`

**Comment by groxw** [comment]
I've installed and it works! thank you, but I've some bug when I try to load about 1000 option, it wont be able to search,
My Code :
User Search (Works)
![Screenshot_735](https://github.com/robsontenorio/mary/assets/65380713/596c7651-da47-430a-b682-58415d2dc15f)
Other Search(Doesnt Work)
![Screenshot_734](https://github.com/robsontenorio/mary/assets/65380713/1ea040b1-02ef-400f-b7fa-7ac953f7d89a)


`                                    <x-choices
                                    label="Data Hafalan"
                                    wire:model="data_hafalan"
                                    :options="$hafalan"
                                    hint="Data Hafalan"
                                    search-function="carihafalan"
                                    option-label="description"
                                    searchable>

                                    </x-choices>`

`    public function carihafalan(string $value = '')
    {
        $this->hafalan = Databasetahfidz::search($value)->get();
    }`
    
There's a 2 choices component; but it's only works for search a user, I try to dd in function it works but for the page view it doesnt take any effect

**Comment by groxw** [comment]
Thankyou! It works properyly, I wonder, is is possble to Computed Properties?

**Comment by robsontenorio** [comment]
@groxw i am afraid it is about Livewire. Not this package.

**Comment by groxw** [comment]
![Screenshot_472](https://github.com/robsontenorio/mary/assets/65380713/74b01db8-64eb-4ccb-a6a0-85b859520bac)
Hello, Is it possible that input for a choices is more elastic while i add, it is like
![Screenshot_473](https://github.com/robsontenorio/mary/assets/65380713/a168383c-5f91-48eb-a3ba-984ac861d1cd)

**Comment by robsontenorio** [comment]
@groxw I will address this on next release.

**Comment by groxw** [comment]
Thanks, this package is really helpful for me

**Comment by groxw** [comment]
Hello, I am sorry I've question about choices, how we can add select all option?

**Comment by groxw** [comment]
I've found some trouble in here, well I try to fill the id with mount function
`public function mount()
{
 $this->user_id = [22, 23]; //ID of user_id
}`

In my choices : 
                                        label="Siswa"
                                        wire:model="user_id"

                                        :options="$all_siswa"
                                        option-label="name"

                                        searchable

                                        >
It's selected but it doesnt display :
![Screenshot_474](https://github.com/robsontenorio/mary/assets/65380713/f87c390c-e6ce-4847-8eeb-e6a098c37857)

**Comment by robsontenorio** [comment]
@groxw are you sure that field `name` exists on your model ?

`option-label="name"`

**Comment by groxw** [comment]
Yes, The table users has a name column,

**Comment by robsontenorio** [comment]
Your collection  is ` :options="$all_siswa"` , so that column `name` must exist on that collection.

**Comment by groxw** [comment]
yes, it works properly when I select it, but when I try to fill an user_id by mount function, it's only selected and doesnt show any display,
![Screenshot_475](https://github.com/robsontenorio/mary/assets/65380713/944fc43e-a858-4ce5-8bc7-1b6b87a76589)

**Comment by robsontenorio** [comment]
@groxw It is supposed to work like that.

Once you have initial selection like `public $user_ids = [1, 2, 3]`;

You **MUST** to change your `search()` method to consider include all of them `pre selected users`, because it is responsible to fill the options list.


**Note :** 

single choice `public $user_id = 4`;
multiple choice `public $user_ids = [1, 2, 3];`

**Comment by groxw** [comment]
So it won't be able to show display option-label when I try to make initial value?

**Comment by robsontenorio** [comment]
You can.

You **MUST** to change your `search()` method to consider include all **pre selected users**, **besides** the search value itself, because it is **responsible** to fill the options list.



```php
public function search(string $value){
    
    // Load initial users from `public $users_id = [1,2,3];`
    $preUsers = User::whereIn('id', $this->users_id)->get();

   // search THEN append $preUsers
   // Because the search() is responsible for fill options list
    $this->users = User::where('name', 'like', "%{$value}%")->take(10)->get()->append($preUsers);

}
```php

**Comment by groxw** [comment]
public function mount()
    {
        $this->user_id = [23];
        $this->all_siswa = User::role('siswa')->where('group_id', $this->user->group_id)->get();
    }

    public function search(string $value = '') 
    {

        $preUsers = User::whereIn('id', $this->user_id)->get();
        $this->all_siswa = User::search($value)
                          ->get()
                          ->append($preUsers);
    }

and my blade : 

                                        <x-choices
                                        label="Siswa"
                                        wire:model="user_id"
                                        :options="$all_siswa"
                                        searchable

                                        >
                                        
It's still not showing any display in input, but it's selected when i try to open option of choices, what am i missing ? then when i try to search it return error because the function of 'append' it gives a collection not array_merge(): Argument #2 must be of type array, Illuminate\Database\Eloquent\Collection given

**Comment by robsontenorio** [comment]
@groxw It was a bug on choices int. Just released "0.33.3". Please, upgrade.

And change -`>append($preUsers)` to `->merge($preUsers)`. It is Laravel collection stuff, so you can include it wherever you want.

**Comment by groxw** [comment]
well thanks! its working

**Comment by robsontenorio** [comment]
@groxw  Just fixed on "0.33.4" multiple choices auto grow. Upgrade and try it.

<img width="849" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/ca0abd2b-9f28-4120-acc0-b68ac72876c5">

**Comment by groxw** [comment]
Sure! Thanks @robsontenorio, it's really great UI

**Comment by bucari** [comment]
Hi, i have the same problem using choices not displaying any result

my blade is 
```
                        <x-choices 
                            label="Autore"  
                            wire:model="user_id"  
                            :options="$users"       
                            search-function="searchAutore"
                            no-result-text="Nessun risultato trovato..."
                            searchable />
```
and searchAutore function

```
    public function searchAutore(string $value = '') {

        $this->users = User::where('name', 'ilike', '%'. $value . '%')
                ->get();
    }
```
What's wrong?

Then, in my opinion, it shouldn't display the scroll bar when there's no result to display

**Comment by groxw** [comment]
Have you declare of variable $users in mount()?
$this->users = User::all();

**Comment by robsontenorio** [comment]
@bucari see this https://github.com/robsontenorio/mary/issues/6#issuecomment-1704318807

**Comment by robsontenorio** [comment]
@bucari Just improved Choices docs. See a more comprehensive example about multiple searchable  https://mary-ui.com/docs/components/choices#searchable

<img width="767" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/efd9c82b-832d-4725-adc4-330974bb7f3e">

**Comment by bucari** [comment]
Hi,
i think this is not a good solution, my users table has over 22.000 records, and i don't want to load all users in the mount function.
If x-choice i ssearchable, in my case, it should reamain empty until i write something to search.

**Comment by bucari** [comment]
Anyway, when i type something in the x-choice, options are not refreshed with new values

```
    public $user_id;
    public Collection $users;

    public function searchAutore(string $value = '')
    {
        $this->users = User::query()
            ->where('name', 'ilike', "%" . $value . "%")
            ->when($value == '', function($query) {  //no load all users on mount
                $query->take(10);
            })
            ->orderBy('cognome')
            ->get();

        $preUser = null;
        if ($this->user_id) {
            // Also load selected users, besides result search
            $preUser = User::find($this->user_id)->get();

            $this->users->merge($preUser); // <--- make it appear on list
        }
    }
```

```
    <x-choices 
    label="Autore"  
    wire:model="user_id"  
    :options="$users"  
    search-function="searchAutore"
    no-result-text="Nessun risultato trovato..."
    single 
    searchable />
```

**Comment by robsontenorio** [comment]
@bucari did you notice `->take(x)` ?

**Comment by bucari** [comment]
ok i use it in this way 

```
    public function searchAutore(string $value = '')
    {
        if (strlen($value)>=3) {
            $this->users = User::query()
                ->where('name', 'ilike', "%" . $value . "%")
                ->orderBy('cognome')
                ->get();

        }
        else
            $this->users = User::query()
            ->where('name', 'ilike', "%" . $value . "%")
            ->take(0)
            ->orderBy('cognome')
            ->get();

        $preUser = null;
        if ($this->user_id) {
            // Also load selected users, besides result search
            $preUser = User::find($this->user_id)->get();

            $this->users->merge($preUser); // <--- make it appear on list
        }

    }
```

but i think it shouldn't run a query at all
