### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by kirilldakhniuk** [robsontenorio/mary#600]
### maryUI version

1.35

### daisyUI version

4.12.10

### Livewire version

3.5

### What browsers are affected?

Firefox

### What happened?

Hey, I'm experiencing odd issue with File component. I checked #354 issue, but found no answer there.

I'll try explain my issue with the following code examples.

I have a list of posts and I want to edit a post inside a modal. 

```php
state(['title', 'photo', 'photoUpload');

$edit = function (Post $post) {
  $this->title = $post->title;
  $this->photo = $post->photo;
};

@foreach(auth()->user()->posts as $post)
  ...
  <button wire:click="edit({{ $post }})>Edit</button>
  ...
@endforeach
```

In this case I see the photo path, which was set in edit function.

```blade
 <x-mary-file
    wire:model="photoUpload"
     accept="image/png, image/jpeg"
 >
    {{ $photo }}
 </x-mary-file>
```

When I pass the path into src the path is always empty.

```blade
 <x-mary-file
    wire:model="photoUpload"
     accept="image/png, image/jpeg"
 >
     <img src="{{ $photo }}" alt="" />
 </x-mary-file>
```

P.S. I'm not a Livewire expert, maybe it's unrelated to Mary UI.

**Comment by kirilldakhniuk** [comment]
Thanks for the quick response. I did try a couple of options and it seem to be working with raw html. This is example from fresh component. As you can see inside file component `$avatar` but it has value in the `img` tag above. And here is where I get a bit confused.

<img width="683" alt="Screenshot 2024-08-31 at 22 53 31" src="https://github.com/user-attachments/assets/024a1388-ca95-4b76-a59d-bd72fbcfb3da">

<img width="802" alt="image" src="https://github.com/user-attachments/assets/251530f5-4073-47ca-b325-38325472f2cc">

<img width="1261" alt="Screenshot 2024-08-31 at 22 52 36" src="https://github.com/user-attachments/assets/26617584-331a-4693-ab0c-42f615e350fa">

**Comment by robsontenorio** [comment]
Please, edit the comment and paste the code itself , so I can copy it to test.

**Comment by EmanuelM** [comment]
I'm facing the same problem, the cause seems to be the "wire:ignore" in the input preview container, maybe?
I don't know is this the way it should work or is there any method to update without refreshing the page

```php
<!-- PREVIEW AREA -->
<div x-ref="preview" class="relative flex">
    <div
        wire:ignore
        @click="change()"
        :class="processing && 'opacity-50 pointer-events-none'"
        class="cursor-pointer hover:scale-105 transition-all tooltip"
        data-tip="{{ $changeText }}"
    >
        {{ $slot }}
    </div>
    <!-- PROGRESS -->
    <div
        x-cloak
        :style="`--value:${progress}; --size:1.5rem; --thickness: 4px;`"
        :class="!processing && 'hidden'"
        class="radial-progress text-success absolute top-5 start-5 bg-neutral"
        role="progressbar"
    ></div>
</div>
```

**Comment by robsontenorio** [comment]
Here is the complete example for future reference and copy/paste.

The trick is to define the correct url for preview. 
There are other approaches.



**TABLE**
```php
Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->string('avatar')->nullable();
            $table->timestamps();
        });
```

**ROUTES**

```php
Volt::route('/users/create', 'users.create');
Volt::route('/users/{user}', 'users.edit');
```

```php
**CREATE USER**

<?php

use App\Models\User;
use Livewire\Attributes\Rule;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;
use Mary\Traits\Toast;

new class extends Component {
    use Toast, WithFileUploads;

    #[Rule('required')]
    public string $name = '';

    #[Rule('required|email')]
    public string $email = '';

    #[Rule('nullable|image|max:1024')]
    public $photo;

    public function save(): void
    {
        $data = $this->validate();

        // Create
        $user = User::create($data);

        // Upload and update photo
        if ($this->photo) {
            $url = $this->photo->store('users', 'public');

            // Here is the trick (!)
            $user->update(['avatar' => "/storage/$url"]);
        }

        $this->success('User created with success.', redirectTo: "/users/{$user->id}");
    }

    public function with(): array
    {
        return [

        ];
    }
}; ?>

<div>
    <x-header title="Create User" separator />

    <x-form wire:submit="save">
        <x-file label="Avatar" wire:model="photo" accept="image/png, image/jpeg" hint="Click to change | Max 1MB" crop-after-change>
            <img src="{{ $user->avatar ?? '/empty-user.jpg' }}" class="h-40 rounded-lg mb-3" />
        </x-file>
        <x-input label="Name" wire:model="name" />
        <x-input label="Email" wire:model="email" />

        <x-slot:actions>
            <x-button label="Cancel" link="/users" />
            <x-button label="Create" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
        </x-slot:actions>
    </x-form>
</div>

```

**EDIT USER**

```php
<?php

use App\Models\User;
use Livewire\Attributes\Rule;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;
use Mary\Traits\Toast;

new class extends Component {
    use Toast, WithFileUploads;

    public User $user;

    #[Rule('required')]
    public string $name = '';

    #[Rule('required|email')]
    public string $email = '';

    #[Rule('nullable|image|max:1024')]
    public $photo;

    public function mount(): void
    {
        $this->fill($this->user);
    }

    public function save(): void
    {
        $data = $this->validate();

        $this->user->update($data);

        if ($this->photo) {
            $url = $this->photo->store('users', 'public');
            $this->user->update(['avatar' => "/storage/$url"]);
        }

        $this->success('User updated with success.');
    }

    public function with(): array
    {
        return [

        ];
    }
}; ?>

<div>
    <x-header title="Update {{ $user->name }}" separator />

    <x-form wire:submit="save">
        <x-file label="Avatar" wire:model="photo" accept="image/png, image/jpeg">
            <img src="{{ $user->avatar ?? '/empty-user.jpg' }}" class="h-40 rounded-lg" />
        </x-file>

        <x-input label="Name" wire:model="name" />
        <x-input label="Email" wire:model="email" />

        <x-slot:actions>
            <x-button label="Cancel" link="/users" />
            {{-- The important thing here is `type="submit"` --}}
            {{-- The spinner property is nice! --}}
            <x-button label="Save" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
        </x-slot:actions>
    </x-form>
</div>

```

**Comment by EmanuelM** [comment]
> Here is the full example for future reference and copy/paste.
> 
> The trick is to define the correct url for preview. There are other approaches.
> 
> **TABLE**
> 
> ```
> Schema::create('users', function (Blueprint $table) {
>             $table->id();
>             $table->string('name');
>             $table->string('email')->unique();
>             $table->string('avatar')->nullable();
>             $table->timestamps();
>         });
> ```
> 
> **ROUTES**
> 
> ```
> Volt::route('/users/create', 'users.create');
> Volt::route('/users/{user}', 'users.edit');
> ```
> 
> **CREATE USER**
> 
> ```
> <?php
> 
> use App\Models\User;
> use Livewire\Attributes\Rule;
> use Livewire\Volt\Component;
> use Livewire\WithFileUploads;
> use Mary\Traits\Toast;
> 
> new class extends Component {
>     use Toast, WithFileUploads;
> 
>     #[Rule('required')]
>     public string $name = '';
> 
>     #[Rule('required|email')]
>     public string $email = '';
> 
>     #[Rule('nullable|image|max:1024')]
>     public $photo;
> 
>     public function save(): void
>     {
>         $data = $this->validate();
> 
>         // Create
>         $user = User::create($data);
> 
>         // Upload and update photo
>         if ($this->photo) {
>             $url = $this->photo->store('users', 'public');
> 
>             // Here is the trick (!)
>             $user->update(['avatar' => "/storage/$url"]);
>         }
> 
>         $this->success('User created with success.', redirectTo: "/users/{$user->id}");
>     }
> 
>     public function with(): array
>     {
>         return [
> 
>         ];
>     }
> }; ?>
> 
> <div>
>     <x-header title="Create User" separator />
> 
>     <x-form wire:submit="save">
>         <x-file label="Avatar" wire:model="photo" accept="image/png, image/jpeg" hint="Click to change | Max 1MB" crop-after-change>
>             <img src="{{ $user->avatar ?? '/empty-user.jpg' }}" class="h-40 rounded-lg mb-3" />
>         </x-file>
>         <x-input label="Name" wire:model="name" />
>         <x-input label="Email" wire:model="email" />
> 
>         <x-slot:actions>
>             <x-button label="Cancel" link="/users" />
>             <x-button label="Create" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
>         </x-slot:actions>
>     </x-form>
> </div>
> ```
> 
> **EDIT USER**
> 
> ```
> <?php
> 
> use App\Models\User;
> use Livewire\Attributes\Rule;
> use Livewire\Volt\Component;
> use Livewire\WithFileUploads;
> use Mary\Traits\Toast;
> 
> new class extends Component {
>     use Toast, WithFileUploads;
> 
>     public User $user;
> 
>     #[Rule('required')]
>     public string $name = '';
> 
>     #[Rule('required|email')]
>     public string $email = '';
> 
>     #[Rule('nullable|image|max:1024')]
>     public $photo;
> 
>     public function mount(): void
>     {
>         $this->fill($this->user);
>     }
> 
>     public function save(): void
>     {
>         $data = $this->validate();
> 
>         $this->user->update($data);
> 
>         if ($this->photo) {
>             $url = $this->photo->store('users', 'public');
>             $this->user->update(['avatar' => "/storage/$url"]);
>         }
> 
>         $this->success('User updated with success.');
>     }
> 
>     public function with(): array
>     {
>         return [
> 
>         ];
>     }
> }; ?>
> 
> <div>
>     <x-header title="Update {{ $user->name }}" separator />
> 
>     <x-form wire:submit="save">
>         <x-file label="Avatar" wire:model="photo" accept="image/png, image/jpeg">
>             <img src="{{ $user->avatar ?? '/empty-user.jpg' }}" class="h-40 rounded-lg" />
>         </x-file>
> 
>         <x-input label="Name" wire:model="name" />
>         <x-input label="Email" wire:model="email" />
> 
>         <x-slot:actions>
>             <x-button label="Cancel" link="/users" />
>             {{-- The important thing here is `type="submit"` --}}
>             {{-- The spinner property is nice! --}}
>             <x-button label="Save" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
>         </x-slot:actions>
>     </x-form>
> </div>
> ```

I understand than the OP case is with a form in a modal, and my case with a drawer.
So having two views/forms is impossible and the problem occurs when the preview URL is computed or reactive.

**Comment by robsontenorio** [comment]
This works the same way ... The form is inside the modal.


```html
    <x-header title="Update {{ $user->name }}" separator />

    // OPEN MODAL
    <x-button label="Open Modal" wire:click="$set('modal', true)" />

   // MODAL
    <x-modal wire:model="modal">
        <x-form wire:submit="save">
            <x-file label="Avatar" wire:model="photo" accept="image/png, image/jpeg">
                <img src="{{ $user->avatar ?? '/empty-user.jpg' }}" class="h-40 rounded-lg" />
            </x-file>

            <x-input label="Name" wire:model="name" />
            <x-input label="Email" wire:model="email" />

            <x-slot:actions>
                <x-button label="Cancel" link="/users" />
                {{-- The important thing here is `type="submit"` --}}
                {{-- The spinner property is nice! --}}
                <x-button label="Save" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
            </x-slot:actions>
        </x-form>
    </x-modal>
```

**Comment by robsontenorio** [comment]
The example above is the minimal code to run. If it still an issue, please, evolve that example above including your scenario. But keeping it minimal to reproduce the bug.

**Comment by EmanuelM** [comment]
https://github.com/user-attachments/assets/3e199e4e-9633-4c3b-a6d0-208d5a8079f6


The modal/drawer uses the same form to create/edit the model, not using two components for each action.

drawer.blade.php
```blade
<x-file
    label="Portada"
    wire:model="cover"
    change-text="Seleccionar imagen"
    accept="image/png, image/jpeg"
>
    <img src="{{ $this->getCoverThumbnail }}" alt="Portada" class="w-60 rounded-3xl">
</x-file>
```

Drawer.php
```php
#[Computed]
public function getCoverThumbnail()
{
    if (
        !is_null($this->form->service) &&
        !is_null($this->form->service->getFirstMedia('cover'))
    ) {
        return $this->form->service->getFirstMediaUrl('cover');
    }

    return asset('images/placeholder.webp');
}
```

**Comment by robsontenorio** [comment]
Could you dump like this just bellow the <img> ? And show de results?

```blade
<img src="{{ $this->getCoverThumbnail }}" alt="Portada" class="w-60 rounded-3xl">

@dump($this->getCoverThumbnail)
@dump($this->getCoverThumbnail())
```

**Comment by robsontenorio** [comment]
There is also annoying thing in Livewire about `wire:key`.
As you are changing things on the fly, on certain scenarios you need to handle it by yourself.

```blade
// Wrap it with a unique key
<div wire:key="user-{{ $user->id }}">
   <x-file ... />
</div>
```

**Comment by EmanuelM** [comment]
> There is also annoying thing in Livewire about `wire:key`.
> 
> As you are changing things on the fly, on certain scenarios you need to handle it by yourself. Ex: using same modal and dynamically changing the editing record.
> 
> ```
> // Wrap it with a unique key
> <div wire:key="user-{{ $user->id }}">
>    <x-file ... />
> </div>
> ```
> 
> cc @kirilldakhniuk

This solve the problem in my case.

I have experience with Livewire, I also tried changing keys before, but maybe I was to blind to try putting the key on a parent div. I remember trying to assign key to input and image on slot 😅

**Comment by robsontenorio** [comment]
When things get wired , wire:key may solve it 👍

**Comment by kirilldakhniuk** [comment]
Hey guys. Sorry for being quite for a while. I tried `wire:key` and it's working now.

Thank you so much.
