### ISSUE TITLE
livewire-powergrid support ? 

### ISSUE THREAD

**Issue by Arkhas** [robsontenorio/mary#602]
Do you have any plan to support livewire powergrid ? 

https://livewire-powergrid.com/

**Comment by robsontenorio** [comment]
Powergrid itself is a standalone library. What do you mean by integration ?

**Comment by Arkhas** [comment]
to be able to use component inside the theme : 

https://livewire-powergrid.com/expanding-powergrid/custom-theme.html#creating-your-custom-theme

**Comment by robsontenorio** [comment]
But the theme is thing about the powergrid itself, and does not have todo with maryUI.
