### ISSUE TITLE
Choices CSS bug

### ISSUE THREAD

**Issue by marcokoepfli** [robsontenorio/mary#605]
### maryUI version

1.35.6

### daisyUI version

4.12.101.35.6

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

As I have seen, many people are encountering the Choices CSS bug, where there is a shadow on focus. This would be a quick fix. Maybe a contribution worth or not? It would be in the CSS file.

```
[type='text']:focus, input:where(:not([type])):focus, [type='email']:focus, [type='url']:focus, [type='password']:focus, [type='number']:focus, [type='date']:focus, [type='datetime-local']:focus, [type='month']:focus, [type='search']:focus, [type='tel']:focus, [type='time']:focus, [type='week']:focus, [multiple]:focus, textarea:focus, select:focus {
    box-shadow: none !important;
}
```

**Comment by robsontenorio** [comment]
What shadow ? Can you please send a screenshot before and after ?

**Comment by marcokoepfli** [comment]
![Bildschirmfoto 2024-09-08 um 21 30 43](https://github.com/user-attachments/assets/ade890ad-4ece-422d-9e7f-8fb4aad51446)
![Bildschirmfoto 2024-09-08 um 21 31 11](https://github.com/user-attachments/assets/f2048eec-a883-45df-a052-919f17c7bb40)

**Comment by robsontenorio** [comment]
This bug happens if you have some custom changes on “app.css” or use any other CSS from third party libraries. It won’t happen on a fresh install only with maryUI. 

Just check the example on online docs , you won’t  see that border.

**Comment by evoart-studio** [comment]
This and several other bugs occur when @tailwindcss/forms is added to the project.
