### ISSUE TITLE
Using custom blade-icon sets in <x-menu-item>

### ISSUE THREAD

**Issue by aleex1848** [robsontenorio/mary#61]
i'm trying to use a custom icon set in `<x-menu-item>`. 

I'm able to use my custom icons doing:  
`<x-hwkicons-o-dsr></x-hwkicons-o-dsr>`  
as well as doing  
`{{ svg('hwkicons-o-dsr') }}`  
  
but putting it in the icon attribute like this:  
`<x-menu-item title="DSR" icon="hwkicons-o-dsr" link="/modules/dsr/" />`
gives error  
`Svg by name "hwkicons-o-dsr" from set "heroicons" not found`  
  
may it be possible to use icon from non-default-icon-set on x-menu-item ?
Thanks!

**Comment by Xety** [comment]
Same here, i wanted to use the font-awesome set, but got the same error `Svg by name "fas-right-to-bracket" from set "heroicons" not found.`
Maybe add a config where we can import the sets we want or something like that ?

**Comment by robsontenorio** [comment]
@aleex1848  @Xety 

Yes, I will add a option to configure preferred iconset.

**Comment by robsontenorio** [comment]
@aleex1848  @Xety Done! Upgrade to latest release.
