### ISSUE TITLE
Toggle: Add support for required marker and validation messages

### ISSUE THREAD

**Issue by anfeichtinger** [robsontenorio/mary#610]
Currently the toggle component does not support the required marker or validation messages. As I often use this component in forms it would be really helpful to also support this. I can create a pull request if necessary. 

Here is an example of what this could look like from a different project:
![image](https://github.com/user-attachments/assets/d37a468f-f834-4299-82c2-f4c1a2778d16)

**Comment by robsontenorio** [comment]
@anfeichtinger  Please, go ahead. You can see `<x-checkbox>` for reference.
