### ISSUE TITLE
It may be a bug that occurs when using sortablejs

### ISSUE THREAD

**Issue by nakayoshisandayo** [robsontenorio/mary#611]
### maryUI version

1.35.7

### daisyUI version

4.12.10

### Livewire version

3.5.6

### What browsers are affected?

Chrome

### What happened?

Spinner and progress-indicator do not work properly with sortablejs installed.
app.js and app.blade.php are as follows.
Is it because some settings are missing?

```js
app.js

import { Livewire, Alpine } from '../../vendor/livewire/livewire/dist/livewire.esm';
import sort from '@alpinejs/sort'

Alpine.plugin(sort)
Livewire.start()
```

```blade
layouts/app.blade.php

@livewireScriptConfig
```

**Comment by robsontenorio** [comment]
Unfortunately it seems a bit out of scope about this package.

But, loading indicator and progress bars animations are provided by CSS / daisyUI. For sure you have some extra third library that may causing this problem. I really don't know details about your setup and can't provide a clue for you

**Comment by EmanuelM** [comment]
In case you are still in trouble with this, Livewire needs to indicate the `@livewireStyles` on `<head></head>` layout.

It's indicated on the [docs](https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine) but same as me I didn't look great it all 😅
