### ISSUE TITLE
Show table row selected count

### ISSUE THREAD

**Issue by RMK147** [robsontenorio/mary#612]
When rows are bulk selected, is there an easy way to display how many are selected? I'd also like to hide/show my bulk actions menu based on whether any are selected or not. Thanks!

**Comment by Mani-Damirchilou** [comment]
i've been wondering the same thing, but it doesnt support wire:model.live

**Comment by anfeichtinger** [comment]
> i've been wondering the same thing, but it doesnt support wire:model.live

For your information: there was a new release yesterday that enables `wire:model.live` for tables. Pull request #608

**Comment by Mani-Damirchilou** [comment]
That is amazing ! Thanks for the info
