### ISSUE TITLE
Clicking Fake filler extension in the toolbar (Microsoft edge, Chrome and Firefox) toggle dark mode 

### ISSUE THREAD

**Issue by ndyabagye** [robsontenorio/mary#615]
https://github.com/user-attachments/assets/3162d437-9f37-43c6-91b3-92c45986f4a7

### maryUI version

^1.35

### daisyUI version

^4.12.10

### Livewire version

^3.5

### What browsers are affected?

Firefox, Chrome, Microsoft Edge

### What happened?

When developing a site using mary-ui, I toggled the [fake filler extension](https://chromewebstore.google.com/detail/fake-filler/bnjjngeaknajbdcgpfkgnonkmififhfo?hl=en) in the toolbar and dark mode was activated.

Microsoft edge, Chrome and Firefox. Windows 11.

The same bug happens on the official [Mary UI site](https://mary-ui.com/)

**Comment by robsontenorio** [comment]
What is the bug ? It goes dark when you toggle.

**Comment by ndyabagye** [comment]
No worries, thank you for your good work. Cheers.
