### ISSUE TITLE
A way to not display html comments in the source code

### ISSUE THREAD

**Issue by thiagoradice** [robsontenorio/mary#619]
I don't fully understand why this is relevant other than for debugging purposes. Maybe we should have a way to turn off these html comments in the source code. Another option would be to use blade comments `{{-- --}}` instead of html's `<!-- -->`.

![image](https://github.com/user-attachments/assets/f0e424d5-a2e6-48f6-a53e-51a7541eb4c2)

**Comment by robsontenorio** [comment]
Nice observation. It could be replaced by blade comment syntax. If you can, please send PR.

By the way, why yours does not show de if/block comments?

![image](https://github.com/user-attachments/assets/876cd885-84ef-4dde-bd01-c9e60dc64f5a)

**Comment by anfeichtinger** [comment]
> By the way, why yours does not show de if/block comments?

There is a livewire config for disabling this: 

![image](https://github.com/user-attachments/assets/c39b317f-5654-4a45-a29e-8ac01b18b3d3)

**Comment by thiagoradice** [comment]
> Nice observation. It could be replaced by blade comment syntax. If you can, please send PR.
> 
> By the way, why yours does not show de if/block comments?
> 
> ![image](https://private-user-images.githubusercontent.com/118955/367385495-876cd885-84ef-4dde-bd01-c9e60dc64f5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTQxNjMsIm5iZiI6MTcyNjQ5Mzg2MywicGF0aCI6Ii8xMTg5NTUvMzY3Mzg1NDk1LTg3NmNkODg1LTg0ZWYtNGRkZS1iZDAxLWM5ZTYwZGM2NGY1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxMzM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2IzNTVhZTc0MzMzNDFkOTZlZmYwNjczMWUxODlkYzliYjVjOTEwMTA5OTdiYzE5YWYyZGRmNTAxYzcyNjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UQawZ_u5cJn0e-GibPYj_lizq7kH3UDeBZmf8IV0u1Q)

Unfortunatly I'll not be able to do this anytime soon, and I will have to go with it in my current project due to deadline. As soon as possible I'll try to change these if it's not done yet.
