### ISSUE TITLE
Very clear table header text (in light themes)

### ISSUE THREAD

**Issue by weelrs8** [robsontenorio/mary#624]
My OS: Ubuntu 24.04.1 LTS

### maryUI version

1.35.9

### daisyUI version

4.12.10

### Livewire version

3.5.6

### What browsers are affected?

Firefox, Chrome

### What happened?

When using a light theme, the texts in the headers table are too light

Dark:
![Captura de tela de 2024-09-18 08-35-49](https://github.com/user-attachments/assets/791059f2-6809-4329-afd8-913c9dcea2e6)

Light:
![Captura de tela de 2024-09-18 08-35-57](https://github.com/user-attachments/assets/8384ef2b-ea5d-4c42-9982-fe810b7931fa)

To reproduce the problem, just go to https://mary-ui.com/docs/components/table and change the theme to light.

**Comment by robsontenorio** [comment]
Maybe some browser plugin or tweak on your OS?

Here I can’t reproduce it. Anyone ?

**Comment by anfeichtinger** [comment]
For me it is the same on the docs page.

![image](https://github.com/user-attachments/assets/d575cc3c-8ade-42a9-9c0a-398ae19c2ba8)

From left to right: Chrome (No plugins), Brave (Ad-Blocking), Firefox (Ad-Blocking)

Versions:

- Windows 11 Pro 23H2 Build 22631.4169
- Google Chrome 128.0.6613.138 (Official Build) (64-bit)
- Brave 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
- Firefox 128.0.3 (64-bit)

On my page for testing mary-ui I get full black on the header without setting any color.

```
@php
        $users = Illuminate\Support\Collection::make([
            0 => ['id' => 1, 'name' => 'Andreas Feichtinger', 'city' => ['name' => 'Kalsdorf bei Graz']],
            1 => ['id' => 2, 'name' => 'Jon Doe', 'city' => ['name' => 'Graz']],
            2 => ['id' => 3, 'name' => 'Jane Doe', 'city' => ['name' => 'Wien']],
        ]);

        $headers = [
            ['key' => 'id', 'label' => '#'],
            ['key' => 'name', 'label' => 'Nice Name'],
            ['key' => 'city.name', 'label' => 'City'],
        ];
    @endphp
    <div class="container-card col-span-full min-w-full">
        <x-header title="Table" class="col-span-full" />
        <div class="col-span-full -mt-10 space-y-6">
            <x-table :headers="$headers" :rows="$users" striped selectable wire:model.live="tableSelection" />
        </div>
    </div>
```
![image](https://github.com/user-attachments/assets/609bf9c6-b5f6-4e09-9701-21a3b2ed3389)

Maybe this helps to reproduce.

**Comment by donnyxray** [comment]
In my case the light version works fine, but the dark one has a black-on-black header in the docs sample.

I should add that my browser operates in light mode. This seems to matter as there are apparently not 2, but 4 effective themes. Depending on your browser's dark/light setting, the website's dark/light setting has different results.

**Comment by weelrs8** [comment]
> Maybe some browser plugin or tweak on your OS?
> 
> Here I can’t reproduce it. Anyone ?

My environment:
Ubuntu 24.04.1 LTS

I did a test on Windows and it looks like this:
![Captura de tela de 2024-09-19 10-08-49](https://github.com/user-attachments/assets/c69beeeb-d8c9-4653-bb0d-5df3ce2a9081)

![Captura de tela de 2024-09-19 10-08-21](https://github.com/user-attachments/assets/c7812257-c469-42f9-be8f-c7ad3727424c)

**Comment by robsontenorio** [comment]
Are you guys able to send a PR?

The tweet is about this line

https://github.com/robsontenorio/mary/blob/f10d5dc459d68d938d3c1952d18c34751a7df8c4/src/View/Components/Table.php#L246

**Comment by anfeichtinger** [comment]
I guess the easiest fix would be to change it to `text-base-content` but I'm not sure if this would break some pages that are not using daisyui themes properly.

**Comment by weelrs8** [comment]
apparently removing `text-black` solves the problem.

**Comment by weelrs8** [comment]
> Are you guys able to send a PR?
> 
> The tweak is about this line
> 
> https://github.com/robsontenorio/mary/blob/f10d5dc459d68d938d3c1952d18c34751a7df8c4/src/View/Components/Table.php#L246
> 
> This is odd because it seems fine ... In someway the OS itself is interfering on that.

I don't know if this will make sense to you, but, strangely, after modifying the file, removing "text-black", saving, adding "text-black" again, the problem disappeared.

I deleted the "vendor" and "node_modules" folder and installed again, and the problem disappeared.

**Comment by robsontenorio** [comment]
The maryUI docs was missing this config on `tailwind.config.js`

https://mary-ui.com/docs/components/theme-toggle#setup

<img width="985" alt="image" src="https://github.com/user-attachments/assets/7852eae1-4a78-4621-983a-c4ffd32aeeb8">
