### ISSUE TITLE
Please support an $allowUnsafeHtml (allow-unsafe-html) attribute

### ISSUE THREAD

**Issue by cooffeeRequired** [robsontenorio/mary#625]
my point is that, for example, span, table, tag and so on do not support the possibility of inserting custom html element instead of using classic text

practically I mean to be able to choose whether we want to insert plain text or html

for example the stats class

```diff
    public function __construct(
        public ?string $value = null,
        public ?string $icon = null,
        public ?string $color = 'text-primary',
        public ?string $title = null,
        public ?string $description = null,
        public ?string $tooltip = null,
        public ?string $tooltipLeft = null,
        public ?string $tooltipRight = null,
        public ?string $tooltipBottom = null,
+        public ?bool $allowUnsafeHtml = false,
    ) {
        $this->uuid = "mary" . md5(serialize($this));
        $this->tooltip = $this->tooltip ?? $this->tooltipLeft ?? $this->tooltipRight ?? $this->tooltipBottom;
        $this->tooltipPosition = $this->tooltipLeft ? 'lg:tooltip-left' : ($this->tooltipRight ? 'lg:tooltip-right' : ($this->tooltipBottom ? 'lg:tooltip-bottom' : 'lg:tooltip-top'));
    }
```

there is $description and $title, wouldn't it be great to add something like allow-unsafe-html for each of your components

and if $allowUnsafeHtml is true, then instead of `{{ $var }}` it will be `{!! $var !!}``

so it might look like this

```blade
@if($allowUnsafeHtml) {!! .... !!} @else {{ ... }} @endif
```

**Comment by anfeichtinger** [comment]
Where do you need this specifically? In a lot of places you can manually overwrite the slot of the component like this:

```blade
<x-checkbox wire:model='someModel'>
    <x-slot:label>
        <label wire:click.stop="$toggle('someModel')">
            {!! $this->someHtmlContent !!}
        </label>
    </x-slot:label>
</x-checkbox>
```

If you provide a few more details and specific use-cases where this is not possible we can discuss how to support it.
