### ISSUE TITLE
Whats wrong with that dark mode?

### ISSUE THREAD

**Issue by cooffeeRequired** [robsontenorio/mary#633]
### maryUI version

White mode works properly but dark mode no.

1.35.9

### daisyUI version

4.12.10

### Livewire version

3.5.6

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

![image](https://github.com/user-attachments/assets/c6eca41d-17a1-44be-a672-3ba00d090c00)

![image](https://github.com/user-attachments/assets/4e0e832a-ecfd-4b80-966c-9ac909318307)

**Comment by anfeichtinger** [comment]
What exactly does not work here? It seems fine to me. Is this related to #624?

**Comment by robsontenorio** [comment]
@cooffeeRequired 

Please , avoid flooding with issues without proper context. 

Make it easy for maintainers.

**Comment by cooffeeRequired** [comment]
Well do you see the white spacers?
