### ISSUE TITLE
Radio component is not displayed correctly,

### ISSUE THREAD

**Issue by GabrielCrespoBrito** [robsontenorio/mary#638]
### maryUI version

^1.34

### daisyUI version

^4.12.10"

### Livewire version

^3.5"

### What browsers are affected?

Chrome

### What happened?

Hi, I'm trying to use the Radio component, but unfortunately it doesn't display the right way, I'm literally inspecting the css to see that it matches the example on the page and everything seems to be exactly the same, I have no idea it actually can be happening.

```

HTML/Blade

```blade

<div>
    
![Captura de pantalla 2024-09-23 093036](https://github.com/user-attachments/assets/171655cc-96e8-40ac-96ed-92c33e4d66d6)

        @php
            $users = [
                ['id' => 1, 'name' => 'John'],
                ['id' => 2, 'name' => 'Doe'],
                ['id' => 3, 'name' => 'Mary', 'disabled' => true],
                ['id' => 4, 'name' => 'Kate'],
            ];

        @endphp


    <x-mary-form wire:submit="save">

        {{--  Basic section  --}}
        <div class="grid gap-3">
            <x-mary-radio label="Select one" :options="$users" wire:model="selectedUser3" />
        </div>

        <x-slot:actions>
            <x-mary-button label="Cancelar" link="/admin/racecourses" />
            {{-- The important thing here is `type="submit"` --}}
            {{-- The spinner property is nice! --}}
            <x-mary-button label="Save" icon="o-paper-airplane" spinner="save" type="submit" class="btn-primary" />
        </x-slot:actions>
    </x-mary-form>

    {{-- Success is as dangerous as failure. --}}
</div>
```

**Comment by robsontenorio** [comment]
How about a screen shot ? What does not display correctly?

**Comment by anfeichtinger** [comment]
The screenshot is in the code that's why it is not showing.
![Captura de pantalla 2024-09-23 093036](https://github.com/user-attachments/assets/171655cc-96e8-40ac-96ed-92c33e4d66d6)

It does not look like this by default. Make sure you don't have any other css interfering and you are not limiting the maximum width.

**Comment by robsontenorio** [comment]
Thanks @anfeichtinger
