### ISSUE TITLE
UUIDs are not unique if the label parameters are the same

### ISSUE THREAD

**Issue by ImCitizen** [robsontenorio/mary#643]
### maryUI version

1.35.9

### daisyUI version

4.6.1

### Livewire version

3.5.6

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

Let's imagine we want 2 checkboxes on your page. If your checkboxes has the same label and if you click on the label to enable the 2nd checkbox, it will check the first checkbox.

You create the following code, and you click on the label of the second one:
```blade
<x-mary-checkbox label="My checkbox"></x-mary-checkbox>

<x-mary-checkbox label="My checkbox"></x-mary-checkbox>
```
This will enable the first input instead of the 2nd input.

Since the uuid is based on the class instance properties, the uuid's will be the same for both checkboxes:
[src/View/Components/Checkbox.php#L13-L27](https://github.com/robsontenorio/mary/blob/f10d5dc459d68d938d3c1952d18c34751a7df8c4/src/View/Components/Checkbox.php#L13-L27)
```php
public function __construct(
        public ?string $label = null,
        public ?string $hint = null,
        public ?string $hintClass = 'label-text-alt text-gray-400 py-1 pb-0',

        public ?bool $right = false,
        public ?bool $tight = false,
        // Validations
        public ?string $errorField = null,
        public ?string $errorClass = 'text-red-500 label-text-alt p-1',
        public ?bool $omitError = false,
        public ?bool $firstErrorOnly = false,
    ) {
        $this->uuid = "mary" . md5(serialize($this));
    }
```

One idea to solve this problem would be to give the possibility to set a customId.

It does the same if you use a slot label :
```blade
<x-mary-checkbox>
    <x-slot name="label">
        First checkbox
    </x-slot>
</x-mary-checkbox>

<x-mary-checkbox>
    <x-slot name="label">
        My incredible checkbox
    </x-slot>
</x-mary-checkbox>
```

**Comment by anfeichtinger** [comment]
We can discuss how this should be addressed. This will be an issue for other components as well as the id is generated the same way everywhere.

- Use the id from `$attributes` if provided. This way we could at least overwrite it if needed.
- Use a randomly generated string as the uuid ([Some possible approaches](https://medium.com/@randomstr/random-string-generation-in-php-and-its-frameworks-bb4b2f1bbce6)). With this we should take care that generating the same id in one render should be impossible.

Of course both approaches can be used together. One idea I have is making a trait `WithUuid` that provides a generateUuid() function or something similar that will always provide a unique string. Used uuids could be stored in the Cache with the array driver so it only persists for the duration of the request. 

```php
public function __construct(
    public ?string $id = null,
    ...
) {
    $this->uuid = $this->id ?? $this->generateUuid();
}
```

We should definitely consider the performance as well when generating the uuid as it can get costly depending on the algorithm. 
@robsontenorio What's your opinion on this? Any upsides of the current approach?

**Comment by robsontenorio** [comment]
@ImCitizen 

This is a known pitfall, uuid are based on parameters. But, in what real scenario you will have checkbox with same labels?

@anfeichtinger 
Livewire does not like random uuid, when you are using `wire.model.live`, for example. The uuid must be the same for that component.

**Comment by anfeichtinger** [comment]
I have actually had a scenario where this is an issue. I have two checkboxes that have a custom html label that can be configured with rich-text someplace else. My workaround is setting them up like this: (as mentioned [here](https://github.com/robsontenorio/mary/issues/625#issuecomment-2361351649))

```blade
<x-checkbox wire:model='someModel'>
    <x-slot:label>
        <label wire:click.stop="$toggle('someModel')">
            {!! $this->someHtmlContent !!}
        </label>
    </x-slot:label>
</x-checkbox>
```

Because the checkboxes have essentially the same parameters (`wire:model` and the label slot don't count as they are not in constructor) they got the same uuid which lead to the label of the second one toggling the first one.

Of course the code above does work so it's not a big issue, though having more unique ids would still be nice.

Also I'm not sure what you mean by this:

> Livewire does not like random uuid, when you are using wire:model.live, for example. The uuid must be the same for that component.

When the uuid is set in the constructor of the component it will be used throughout it anyways right? And being able to set a custom id would be nice in any case.

**Comment by robsontenorio** [comment]
I think we can go like this :

```
$this->uuid = "mary" . md5(serialize($this)). $this->id;
```

So, won’t be conflict if others components has the same id.
