### ISSUE TITLE
Vite not compile all styles?

### ISSUE THREAD

**Issue by Krendzel** [robsontenorio/mary#646]
### maryUI version

^1.35

### daisyUI version

^4.12.10

### Livewire version

^3.5

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

After installing TailwindCSS and DaisyUI on fresh Laravel 11 installation, styles are not fully compiled

Result: 
![image](https://github.com/user-attachments/assets/91627be9-e115-464e-bd9c-c1b0e5894f75)

But when i use CDN links for DaisyUI and TailwindCSS instead Vite, everything looks fine. 

```blade 
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
```
Expected result:
![image](https://github.com/user-attachments/assets/717f478f-582c-4873-bc45-b381070cbc5c)

Steps to reproduce:
- Install fresh Laravel by command `laravel new example`
- Install Livewire `composer require livewire/livewire`
- Install TailwindCSS [Install Tailwind CSS with Laravel](https://tailwindcss.com/docs/guides/laravel#vite)
- Install DaisyUI [Install daisyUI as a Tailwind CSS plugin](https://daisyui.com/docs/install/)
- Install MaryUI by command `composer require robsontenorio/mary`
- Create blade file with code from [Layout](https://mary-ui.com/docs/layout#only-sidebar)
- Run `npm run dev`
- Refresh page

index.blade.php (copy/paste from docs - [Layout](https://mary-ui.com/docs/layout#only-sidebar)): 
```blade
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen font-sans antialiased bg-base-200/50 dark:bg-base-200">

{{-- NAVBAR mobile only --}}
<x-nav sticky class="lg:hidden">
    <x-slot:brand>
        <div class="ml-5 pt-5">App</div>
    </x-slot:brand>
    <x-slot:actions>
        <label for="main-drawer" class="lg:hidden mr-3">
            <x-icon name="o-bars-3" class="cursor-pointer" />
        </label>
    </x-slot:actions>
</x-nav>

{{-- MAIN --}}
<x-main full-width>
    {{-- SIDEBAR --}}
    <x-slot:sidebar drawer="main-drawer" collapsible class="bg-base-100 lg:bg-inherit">

        {{-- BRAND --}}
        <div class="ml-5 pt-5">App</div>

        {{-- MENU --}}
        <x-menu activate-by-route>
            <x-menu-item title="Hello" icon="o-sparkles" link="/" />
            <x-menu-sub title="Settings" icon="o-cog-6-tooth">
                <x-menu-item title="Wifi" icon="o-wifi" link="####" />
                <x-menu-item title="Archives" icon="o-archive-box" link="####" />
            </x-menu-sub>
        </x-menu>
    </x-slot:sidebar>

    {{-- The `$slot` goes here --}}
    <x-slot:content>
        Content goes here
    </x-slot:content>
</x-main>

{{-- Toast --}}
<x-toast />
</body>
</html>
```
tailwind.config.js: 
```js
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
  theme: {
    extend: {},
  },
  plugins: [
      require('daisyui'),
  ],
}
```

package.json
```json
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "autoprefixer": "^10.4.20",
        "axios": "^1.7.4",
        "daisyui": "^4.12.10",
        "laravel-vite-plugin": "^1.0",
        "postcss": "^8.4.47",
        "tailwindcss": "^3.4.13",
        "vite": "^5.0"
    }
}
````

composer.json
```json
[...]
"require": {
        "php": "^8.2",
        "laravel/framework": "^11.9",
        "laravel/tinker": "^2.9",
        "livewire/livewire": "^3.5",
        "robsontenorio/mary": "^1.35"
    },
```

**Comment by robsontenorio** [comment]
You did a manual install and forgot to declare mary components path inside tailwind.config.js

We recommend an automatic install as described on maryUI docs.

**Comment by Krendzel** [comment]
> You did a manual install and forgot to declare mary components path inside tailwind.config.js
> 
> We recommend an automatic install as described on maryUI docs.

Just 1 minute before you reply i added that line tailwindcss config and now everything works fine. 

Maybe will be good idea to add information about that in docs?

**Comment by robsontenorio** [comment]
The docs says to use automatically installer, so people don't need to get bored about all these details.
