### ISSUE TITLE
How to create a context menu of any  row in table data ?

### ISSUE THREAD

**Issue by PetroGromovo** [robsontenorio/mary#656]
Reading how menu works at https://mary-ui.com/docs/components/menu I did not  find if there is a way  (https://mary-ui.com/docs/components/table) or in any other livewire component ?

        "laravel/framework": "^11.9",
        "livewire/livewire": "^3.5",
        "livewire/volt": "^1.0",
        "robsontenorio/mary": "^1.35",

Thanks in advance!

**Comment by robsontenorio** [comment]
Currently there is no "right click" context menu component. But, there is a Dropdown component .

https://mary-ui.com/docs/components/dropdown
