### ISSUE TITLE
File Upload (multiple) with preset files

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#657]
Hey there!

We are trying to have preset files on e.g.

```html
<x-file wire:model="photos" label="Photos" multiple />
```

Tried making the files from storage `Illuminate\Http\UploadedFile` and setting them as an array on the model variable but this way leads to an error:

<img width="1086" alt="Screenshot 2024-09-30 at 15 43 06" src="https://github.com/user-attachments/assets/607b5387-264a-45dc-8c37-2fa8d3a7b7e9">

The idea behind it is that we want the files to appear on the edit screen and have the input alread say "2 files" so the user sees there are already files and have validation pass... if possible.

Any help would be much appreciated :-) Thanks!

**Comment by robsontenorio** [comment]
Take a look at docs for multiple files. What is wrong ?

https://mary-ui.com/docs/components/file#multiple-files

**Comment by pboese** [comment]
@robsontenorio I don't know how to attach existing files to it, e.g.

```html
<x-file wire:model="photos" label="Photos" multiple />
```

neither 

```php
$this->photos = [
    '/path/to/image1.png',
    '/path/to/image2.png',
];
```

nor 

```php
$this->photos = [
    new UploadedFile('/path/to/image1.png', 'image1.png'),
    new UploadedFile('/path/to/image2.png', 'image2.png'),
];
```

seem to work. What am I doing wrong? Thanks!

**Comment by robsontenorio** [comment]
It does not work like this away. Think about how raw HTML  file input works, it works like the same. 

It will send new files , but has nothing to do with existing ones.

**Comment by pboese** [comment]
Alright, thanks. So I'm not crazy :-D
