### ISSUE TITLE
Potential Missing Prefix in x-button and x-icon Components in Password.php component

### ISSUE THREAD

**Issue by Altair484** [robsontenorio/mary#660]
### maryUI version

1.40.1

### daisyUI version

^4.12.10

### Livewire version

^3.5

### What browsers are affected?

Chrome

### Component: 
HTML/Blade

```blade
<x-mary-password>
```

### Description:
After updating the mary ui package, a new component called <x-mary-password> was introduced. While implementing this component, there appears to be an issue related to component prefixes. As per the package guidelines, components should adopt the defined prefix (e.g., x-mary-), especially when a prefix is set in the mary.php config file.

However, certain components within <x-mary-password>, such as x-button and some instances of x-icon, do not seem to use the prefix. This could potentially cause errors, particularly when installing the package with a custom prefix.

For example, when using the following code:

HTML/Blade

```blade
<x-mary-password label="Right toggle" label="Mot de passe" wire:model="password" right icon="o-key" />
```

This component references x-button and x-icon but does not always apply the mary prefix, which may lead to the following error:

Unable to locate a class or view for component [button]. 
(View: /var/www/html/web/app/cache/acorn/framework/views/7b19390308762a276f7a013c9604f937.blade.php)

### Affected Code:

HTML/Blade

```blade
@if($icon)
    <x-mary-icon :name="$icon" class="absolute top-1/2 -translate-y-1/2 start-3 text-gray-400 pointer-events-none" />
@elseif($placeToggleLeft())
    <x-button x-on:click="hidden = !hidden" class="btn-ghost btn-sm btn-circle p-0 absolute top-1/2 -translate-y-1/2 start-1.5 text-gray-400 no-animation active:focus:-translate-y-1/2">
        <x-icon name="{{ $passwordIcon }}" x-show="hidden" /> 
        <x-icon name="{{ $passwordVisibleIcon }}" x-show="!hidden" x-cloak class="text-primary" /> 
    </x-button>
@endif

@if($clearable)
    <x-mary-icon @click="$wire.set('{{ $modelName() }}', '', {{ json_encode($attributes->wire('model')->hasModifier('live')) }})" name="o-x-mark" class="absolute top-1/2 end-3 -translate-y-1/2 cursor-pointer text-gray-400 hover:text-gray-600" />
@endif

@if($iconRight)
    <x-mary-icon :name="$iconRight" @class(["absolute top-1/2 end-3 -translate-y-1/2 text-gray-400 pointer-events-none", "!end-10" => $clearable]) />
@elseif($placeToggleRight())
    <x-button x-on:click="hidden = !hidden" @class(["btn-ghost btn-sm btn-circle p-0 absolute top-1/2 -translate-y-1/2 end-1.5 text-gray-400 no-animation active:focus:-translate-y-1/2", "!end-9" => $clearable])>
        <x-icon name="{{ $passwordIcon }}" x-show="hidden" /> 
        <x-icon name="{{ $passwordVisibleIcon }}" x-show="!hidden" x-cloak class="text-primary" /> 
    </x-button>
@endif
```

### Expected Behavior:
Components like x-button and x-icon may need to have the same prefix (x-mary-), similar to how x-mary-icon is used elsewhere in the code. This ensures consistency and prevents potential errors related to missing components.

### Actual Behavior:
The lack of prefixes for x-button and some instances of x-icon appears to trigger an error in certain contexts, particularly when the custom prefix is enabled.

### Possible Solution (Suggestion):
It might be worth considering whether the missing prefixes should be added to these components. For example, changing <x-button> to <x-mary-button> and reviewing the use of x-icon could resolve the issue.

**Comment by anfeichtinger** [comment]
Sorry this is my mistake, I didn't use the buttons and icons in the correct way. Will create a pull request asap.
