### ISSUE TITLE
Unable to render child component view after refresh parent component

### ISSUE THREAD

**Issue by mustaqim224** [robsontenorio/mary#663]
### maryUI version

^1.24

### daisyUI version

^4.7.2

### Livewire version

^3.4

### What browsers are affected?

Microsoft Edge

### What happened?

getting uncaught Snapshot missing on Livewire component with id: c3SUqFeKFQCsxXcn9irz

i already put wire:key to my livewire component, and the inner div, but the buttons not rendered after page reload

Parent Component HTML/Blade
```
<x-card>
        <x-table :headers="$headers" :rows="$products" :sort-by="$sortBy" with-pagination>
            @scope('cell_preview', $product)
                <x-avatar :image="$product->cover" class="!w-10 !rounded-lg" />
            @endscope
            @scope('cell_actions', $product)
                    <livewire:products.actions :product="$product" :key="$product->id"  />
            @endscope
        </x-table>
    </x-card>
``` 

Child Component HTML/Blade

```
 @php
    $key = md5($product->id);
@endphp
<div>
    <div wire:key="child-div-{{ $key }}" class="flex gap-2">
        <x-button icon="o-trash" class=" btn-error btn-xs" wire:click="delete" spinner="delete" />
        <x-button icon="o-pencil" spinner="myModal1" class=" btn-primary btn-xs" @click="$wire.myModal1 = true" />
    </div>
    <x-modal wire:model="myModal1" class="backdrop-blur">
        <div class="mb-5">Press `ESC`, click outside or click `CANCEL` to close.</div>
        <x-button label="Cancel" @click="$wire.myModal1 = false" />
    </x-modal>
</div>

``` 
Action column before
![image](https://github.com/user-attachments/assets/5aabb37c-ade8-4c9a-a48b-a676f2e7e63e)

Action column after (the actions-buttons.blade not rendering)
![image](https://github.com/user-attachments/assets/7be5394b-ec77-4846-a759-4171cdcc23f5)

**Comment by mustaqim224** [comment]
Parent Component HTML/Blade
    <x-card>
        <x-table :headers="$headers" :rows="$products" :sort-by="$sortBy" with-pagination>
            @scope('cell_preview', $product)
                <x-avatar :image="$product->cover" class="!w-10 !rounded-lg" />
            @endscope
            @scope('cell_actions', $product)
                    <livewire:products.actions :product="$product" :key="$product->id"  />
            @endscope
        </x-table>
    </x-card>
    
Child Component HTML/Blade
<div>
    <div wire:key="child-div-{{ $key }}" class="flex gap-2">
        <x-button icon="o-trash" class=" btn-error btn-xs" wire:click="delete" spinner="delete" />
        <x-button icon="o-pencil" spinner="myModal1" class=" btn-primary btn-xs" @click="$wire.myModal1 = true" />
    </div>
    <x-modal wire:model="myModal1" class="backdrop-blur">
        <div class="mb-5">Press `ESC`, click outside or click `CANCEL` to close.</div>
        <x-button label="Cancel" @click="$wire.myModal1 = false" />
    </x-modal>
</div>

**Comment by robsontenorio** [comment]
Have you tried to put a wire:key here ?

```
<div wire:key=“…”>
  <livewire:products
</div>
```

**Comment by mustaqim224** [comment]
yes, 
```
                   <div wire:key="parent-div-{{ $product->id }}">
                        <livewire:products.actions :product="$product" :key="$product->id"  />
                    </div>
``` 

already add the key to the parent div, still the same. BTW, im using your https://flow.mary-ui.com/ template.

**Comment by sohrab-az** [comment]
i have this problem too. if you could fix it tell me. thanks.

**Comment by robsontenorio** [comment]
This should do the trick . Also make sure to remove `wire:key` from child component above.

```blade
@scope('actions', $product)
      <livewire:products.actions :product="$product" wire:key="product-{{ $product->id}}"  />
@endscope
```

Although this work, and has nothing to do with maryUI, that approach will dump a lot of html. Because, for each row  it will dump the html from your child component.

An alternative approach would be to have a single  `<livewire:product-edit />` on page and make it appear when your click on some row `<x-button wire:click=preview({{ $product->id }})`
