### ISSUE TITLE
Using Daisy UI Components with Mary UI in Laravel Projects

### ISSUE THREAD

**Issue by snarexx** [robsontenorio/mary#666]
Since Mary UI is built on top of Daisy UI, can we use Daisy UI components directly in our Laravel projects alongside Mary UI components, for example, a bottom navigation not provided by Mary UI, without re-installing Daisy UI? If not, should we install Daisy UI separately? In both cases, I understand that we would need to convert them into Livewire components. @robsontenorio

**Comment by robsontenorio** [comment]
Thanks @itsmenewbie03
