### ISSUE TITLE
Button state when loaded in iframe

### ISSUE THREAD

**Issue by flatcapco** [robsontenorio/mary#668]
### maryUI version

latest

### daisyUI version

latest

### Livewire version

latest

### What browsers are affected?

Chrome

### What happened?

When embedding a livewire component into another site via an iframe the x-button seems to have an issue with the loading state staying active. https://capture.dropbox.com/symxF7HdGt9lgi1n

```php
                        <x-button
                            class="btn-primary"
                            type="submit"
                            label="Get Quote"
                            icon="o-sparkles"
                            spinner="save"
                        />
```

If spinner="save" is removed then all works as expected but it'd be nice to retain that feature if possible 

I'm guessing it's missing something to tell it loading is complete but 
<span wire:loading="" wire:target="save" class="loading loading-spinner w-5 h-5"></span>

**Comment by robsontenorio** [comment]
I am afraid we can't  support it, once wire-extender is entirely a new thing.

**Comment by flatcapco** [comment]
@robsontenorio I haven't I've just removed the loading class for now as everything else worked as expected, I can return to it to try but melting behind a go live date for a client at the moment
