### ISSUE TITLE
How can I use all icons from https://blade-ui-kit.com/blade-icons ?

### ISSUE THREAD

**Issue by sergeynilov** [robsontenorio/mary#670]
### maryUI version

^1.40.3 

### daisyUI version

^4.12.10

### Livewire version

 3.5

### What browsers are affected?

Chrome

### What happened?

In laravel 11 / livewire 3.5 I use mary-ui ^1.40.3 app
At manuals https://mary-ui.com/docs/components/icon there is a link at icons page
https://blade-ui-kit.com/blade-icons?set=1#search.

But on this page there are only 80 icons.

I tried to use icons from other page of this site , like

tabler-forbid-2 from https://blade-ui-kit.com/blade-icons#search link

```
<x-mary-icon name="tabler-forbid-2" class="w-6 -mb-1 text-purple-500" />


<x-mary-icon name="tabler-forbid-2" class="w-6 -mb-1 text-purple-500" />


<x-mary-icon name="o-tabler-forbid-2" class="w-6 -mb-1 text-purple-500" />
```

But in all cases I got error like :

`    from set "heroicons" not found`

If there is a way to use all/more icons fron https://blade-ui-kit.com/blade-icons#search link ?

**Comment by robsontenorio** [comment]
MaryUI comes with HeroIcons set. If you need to install an extra icon set take a look at
https://mary-ui.com/docs/components/icon#alternative-iconset
and 
https://github.com/blade-ui-kit/blade-icons

**Comment by sergeynilov** [comment]
I installed by command :

`composer require owenvoke/blade-fontawesome
`
and gave a package in composer :

`    "owenvoke/blade-fontawesome": "^2.6",
`
If I set in the blade file example from github manuals :
```

<x-icon name="fas.cloud" />
<x-icon name="far.circle-play" />
<x-icon name="fab.facebook" />

```
Any of them raise an error like :

Svg by name "fab.facebook" from set "default" not found.


I try to use it in mary components :

`<x-mary-button icon="fab.facebook"
`

It is rendered ok


When I use :

`<x-mary-button icon="fa.right-from-bracket"
`
from                https://fontawesome.com/icons/right-from-bracket?f=classic&s=regular

Svg by name "fa-right-from-bracket" from set "default" not found.


I use invalid syntax or only sum subset from https://fontawesome.com/icons works ?

**Comment by robsontenorio** [comment]
@sergeynilov 

All examples from docs consider you components does not have prefix: 
x-button , x-icon, x-card ...

1. If you set a prefix on `config/mary.php` , so you have to proper change the code:
x-mary-button, x-mary-icon, x-mary-card ....

2. Of course, the available icons provided by community packages are from free tier. This one is pro
<img width="483" alt="image" src="https://github.com/user-attachments/assets/1997f521-6d03-403b-9bba-8201807c9f8d">

**Comment by sergeynilov** [comment]
Thanks!
