### ISSUE TITLE
Hello! Is it possible to create an infinite scrolling pagination component?

### ISSUE THREAD

**Issue by nfhh** [robsontenorio/mary#676]
`<?php

use Livewire\Attributes\Layout;
use Livewire\Volt\Component;
use Livewire\Attributes\Computed;
use Illuminate\Support\Collection;
use Livewire\WithPagination;

new
#[Layout('components.layouts.app')]
class extends Component {

    use WithPagination;

    public int $page = 1;

    public Collection $rows;

    public function mount()
    {
        $this->rows = collect();
        $this->loadMore();
    }

    public function loadMore()
    {
        $this->rows->push(
            ...$this->paginator->getCollection()
        );

        $this->page = $this->page + 1;
    }

    #[Computed()]
    public function paginator()
    {
        return ImageLog::paginate(10, ['*'], 'page', $this->page);
    }
}; ?>

<x-card>
    @php
        $headers = [
            ['key' => 'id', 'label' => '#'],
            ['key' => 'path', 'label' => __('Image')],
        ];
    @endphp

    <x-table :headers="$headers" :rows="$rows"/>

    @if ($this->paginator->hasMorePages())
        <div x-data x-intersect="$wire.loadMore">
            <x-loading class="text-gray-400 dark:text-gray-500"/>
        </div>
    @endif
</x-card>
`
<img width="891" alt="image" src="https://github.com/user-attachments/assets/e82f8c66-1d14-4e8e-bbae-88f2631b31ce">
This Infinite scrolling pagination has N+1 problem, Can you create an infinite scrolling pagination component?

**Comment by robsontenorio** [comment]
This is a topic about Livewire usage, not maryUI components itself.
