### ISSUE TITLE
Choices Component Not Rendering with Multiple Selection

### ISSUE THREAD

**Issue by kai0310** [robsontenorio/mary#679]
### maryUI version

1.41.1

### daisyUI version

4.12.13

### Livewire version

3.5.12

### What browsers are affected?

Chrome

## Summary

Hey, @robsontenorio :) 

Thank you for creating such a wonderful package.

I wanted to create a UI component based on the choices component that allows multiple selections of the Category model. I wrote the code based on the documentation, but it doesn’t seem to display properly in the view.

However, when selecting a single Category, the component worked correctly.

Below, I have included an example of the minimal component to reproduce the issue.

Is there any problem with my code?
Or could it be an issue with library dependencies?

I set up everything according to the installation method of daisyUI, and while I considered that some application settings might be missing, I have thoroughly checked the documentation.

I would appreciate it if you could let me know any specific solutions.
Thank you.

## Minimal code example

Here is the minimal code example to reproduce the issue.

PHP
```php
<?php

namespace App\Livewire\Questions;

use App\Models\Category;
use Illuminate\Support\Collection;
use Illuminate\View\View;
use Livewire\Component;

class CategorySelect extends Component
{
    public $categories;

    public ?int $category_searchable_id = null;

    public array $categories_multi_searchable_ids = [];


    public Collection $categoriesSearchable;

    public function mount(): void
    {
        $this->categories = Category::query()->get();
        $this->searchMulti();
    }

    public function searchMulti(string $value = ''): void
    {
        $selectedOption = Category::query()
            ->whereIn('id', $this->categories_multi_searchable_ids)
            ->orderBy('name')->get();

        $this->categoriesSearchable = Category::query()
            ->where('name', 'like', "%$value%")
            ->take(5)
            ->orderBy('name')
            ->get()
            ->merge($selectedOption); // <-- Adds selected option
    }

    public function render(): View
    {
        return view('livewire.questions.category-select');
    }
}

```

HTML/Blade

```blade
<x-mary-choices
    label="Searchable + Multiple"
    wire:model="categories_multi_searchable_ids"
    :options="$categoriesSearchable"
    placeholder="Search ..."
    search-function="searchMulti"
    no-result-text="Ops! Nothing here ..."
    searchable
/>
```
## Screen capture
[![Image from Gyazo](https://i.gyazo.com/657dd7b7cd1e0ff176014b913908b3f0.gif)](https://gyazo.com/657dd7b7cd1e0ff176014b913908b3f0)

**Comment by robsontenorio** [comment]
And about errors on browser console ?

**Comment by kai0310** [comment]
@robsontenorio 
Thank you for your prompt reply!
It seems that the following error appears in the browser console when clicking on the component’s select:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.toggle (eval at safeAsyncFunction (livewire.js?id=38dc8241:1171:21), <anonymous>:78:40)
    at [Alpine] toggle(1, true) (eval at safeAsyncFunction (http://localhost:8080/livewire/livewire.js?id=38dc8241:1171:21), <anonymous>:3:32)
    at livewire.js?id=38dc8241:1193:23
    at tryCatch (livewire.js?id=38dc8241:1113:14)
    at livewire.js?id=38dc8241:3871:7
    at handler4 (livewire.js?id=38dc8241:3173:27)
    at livewire.js?id=38dc8241:3237:9
    at HTMLDivElement.<anonymous> (livewire.js?id=38dc8241:3175:54)
```

**Comment by ozerozay** [comment]
If you are using this as a child component, you should check the value coming from the parent. I encountered a similar problem. $categories_multi_searchable_ids should be [] in parent
