### ISSUE TITLE
Unable to locate a class or view for component [mary-slot:content]. GET 127.0.0.1:8000

### ISSUE THREAD

**Issue by bibovaldez** [robsontenorio/mary#680]
### maryUI version

1.41.1

### daisyUI version

4.12.13

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

<x-mary-main full-width>

        {{-- BRAND --}}
        <div class="ml-5 pt-5">App</div>

        <x-mary-slot:content>
            {{ $slot }}
        </x-mary-slot:content>
    </x-mary-main>
    
    cant render the component please help
    
    i am using jetstream

**Comment by anfeichtinger** [comment]
Slot is not a mary specific component, it's normal blade syntax. You should use it like this:

```blade
<x-slot:content>
    {{ $slot }}
</x-slot:content>
```
or
```blade
<x-slot name="content">
    {{ $slot }}
</x-slot>
```

**Comment by bibovaldez** [comment]
Thanks @anfeichtinger
