### ISSUE TITLE
Unable to find component: []

### ISSUE THREAD

**Issue by bibovaldez** [robsontenorio/mary#684]
### maryUI version

latest

### daisyUI version

latest

### Livewire version

latest

### What browsers are affected?

Chrome

### What happened?

it works on local but when in production it cant find the component it tried updating and installing dependencies still cant find the component

PHP

```php
    Volt::route('/dashboard/poultry/building', 'Building_Management')->name('building-management');
```

HTML/Blade

```blade
<?php

use Livewire\Attributes\Layout;
use Livewire\Attributes\Rule;
use Livewire\Attributes\Title;
use Livewire\Volt\Component;

new 
#[Layout('layouts.app')] 
#[Title('Building Management')] 
class extends Component {
```

on local env
<img width="963" alt="image" src="https://github.com/user-attachments/assets/35d5a465-b1aa-4e46-8a31-f0ef1729409d">

on production env
<img width="959" alt="image" src="https://github.com/user-attachments/assets/b74128c6-8e8a-4dd3-8a5e-bad7dd9f0b3d">

**Comment by robsontenorio** [comment]
Sorry, but this “Buliding_Managment” is not about any maryUI component.
