### ISSUE TITLE
Feedback on the Mary Project

### ISSUE THREAD

**Issue by cooffeeRequired** [robsontenorio/mary#687]
**Subject: Feedback on the Mary Project**

_Hi robsontenorio,_

Firstly, I want to express my appreciation for your work on the Mary project. It’s clear there’s been a lot of dedication and effort put into this, and your contribution to the Livewire ecosystem is greatly valued.

After reviewing the codebase, I noticed some areas that diverge from Livewire and Alpine.js best practices. Specifically, certain patterns could be adjusted to align with recommended Livewire and Alpine approaches. I’d like to share some observations to enhance the project’s maintainability and performance, though I’m not suggesting a full rewrite in Alpine.js and Livewire, especially given that it might not yield significant performance gains at this point. 

Here are a few areas of improvement that could help the Mary project adhere more closely to Livewire and Alpine.js best practices:

>[!Important]
>1. **Increased Use of Livewire’s `$wire` Directive**:
>   Livewire 3 has greatly optimized its `$wire` directive for interaction with Alpine.js, allowing for >streamlined communication between Livewire components and Alpine state without the need for additional >JavaScript or manual event handling. More consistent use of `$wire` could simplify the codebase, improve >maintainability, and potentially offer minor performance benefits by reducing direct JavaScript >interactivity.

>[!Important]
>2. **Minimizing Direct DOM Manipulation**:
>   Livewire encourages using its lifecycle hooks and built-in reactivity, rather than manual DOM >manipulation with JavaScript. Currently, the Mary project contains code that directly manages the UI, >which can sometimes override or conflict with Livewire’s state. Adopting more of Livewire’s reactivity >patterns could enhance the code’s readability and maintainability while leveraging Livewire’s updates more >effectively.

>[!Note]
>3. **Leveraging Alpine for Simpler Interactivity**:
>   Since Alpine.js is already a dependency, we could simplify the interactivity within components by using >Alpine’s reactive capabilities, following a more unified Alpine-Livewire approach. This would not only >improve the code’s readability but also reduce complexity in managing UI states.

>[!Note]
>4. **Performance Considerations**:
>   While rewriting entirely in Livewire and Alpine is not my recommendation, there are opportunities to >streamline performance by adopting newer Livewire 3 functionalities. These improvements could lead to >better user experience without needing to overhaul the project structure.

Thank you once again for all your hard work on this. I hope these suggestions are helpful and contribute positively to the Mary project.

Warm regards,  
**coffeerequired**

**Comment by robsontenorio** [comment]
Thanks.

**Comment by cooffeeRequired** [comment]
WTF... I wrote it myself, I only had the grammar edited because I'm not from England and I don't speak much English... anyway I've been testing your project for more than 2 months, but the performance for various elements is not good.
