### ISSUE TITLE
Choices offline component seems to round large numbers

### ISSUE THREAD

**Issue by pboese** [robsontenorio/mary#688]
### maryUI version

1.41.1

### daisyUI version

4.0

### Livewire version

3.2

### What browsers are affected?

Chrome

### What happened?

Heya, I found a weird issue in choices offline when using large numbers as `id`, here is an example:

```php
public array $options = [
    [
        'id' => 264454000038134081,
        'name' => 'Test 1',
    ],
    [
        'id' => 264454000038134082,
        'name' => 'Test 2',
    ],
    [
        'id' => 264454000038134587,
        'name' => 'Test 3',
    ],
];

public function updatedChoicesOption($value)
{
    dump($value, $this->options);
}
```

```html
<x-choices-offline label="Select" wire:model.live="choices_option" :options="$options" single searchable />
```

Now when I select e.g. the first option, I get `264454000038134080` for `$value` instead of `264454000038134081` and for the third option I get `264454000038134600` instead of `264454000038134587`. 

Is there any way to fix this issue? Thanks a lot!

**Comment by pboese** [comment]
It works when changing https://github.com/robsontenorio/mary/blob/main/src/View/Components/ChoicesOffline.php#L83 to

```php
return "'{$value}'";
```

**Comment by robsontenorio** [comment]
@pboese  The solution pointer by you only works if you define the  `id` as a string as well.

For this reason I will introduce a new parameter to handle this case.

![image](https://github.com/user-attachments/assets/d2dd94e2-f69f-45ff-9661-66049cc2ddfd)
