### ISSUE TITLE
@tailwindcss/forms problems

### ISSUE THREAD

**Issue by e-smily** [robsontenorio/mary#693]
### maryUI version

latest

### daisyUI version

latest

### Livewire version

latest

### What browsers are affected?

Firefox

### What happened?

Hello,
in dark mode I had a white background for the checkbox, at least together with the plugin "'@tailwindcss/forms".
In another project with DaisyUI the checkbox was visible in the theme controller.

An entry in the plugins of tailwind.config.js helped:

```
...
import forms from '@tailwindcss/forms';
...

plugins: [
forms({
// only generate classes
strategy: 'class',
}),
require("daisyui")
]
```

Maybe this will help someone if similar problems occur...

**Comment by robsontenorio** [comment]
Actually when using daisyUI you don’t need this plugin. But , thanks 👍

**Comment by qwasyx0** [comment]
@robsontenorio I am using another package that uses tailwindcss/forms and I cannot unistall it as it completely messes up all the styles (it is rappasoft/livewire-tables). So this setting messes up several components, notably x-toggle and x-choice. Is there a way to make these work with the forms package?

**Comment by robsontenorio** [comment]
@qwasyx0  If the solution above does not work for you, I honestly don’t know what can be done.

if you find a solution , let me know.  

It seems a daisyUI limitation. See https://github.com/saadeghi/daisyui/issues/2529

Maybe we have better luck with upcoming daisyUI v5 + Tailwind v4

**Comment by qwasyx0** [comment]
@robsontenorio my solution is to copy the components to App\View\Components and just change few classes. For example in Choices component on x-ref="searchInput" I added classes `focus:ring-0 ring-0 border-0` and then it looks almost like in the docs. Fortunately it is only few components.
