### ISSUE TITLE
Add support to change pagination label

### ISSUE THREAD

**Issue by JulitoM3** [robsontenorio/mary#694]
It would be great if pagination label ("_showing_ 1 _from_ 1000") could be editable.

Thanks!

**Comment by robsontenorio** [comment]
Under the hood it uses the Laravel pagination. 
So, you need to use the proper translations files for pagination. 

See the Laravel source code about pagination translation keys. 

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Pagination/resources/views/tailwind.blade.php
