### ISSUE TITLE
Duplicate id/uuid - missing id prop

### ISSUE THREAD

**Issue by misog** [robsontenorio/mary#698]
### maryUI version

1.41.2

### daisyUI version

4.12.10

### Livewire version

3.5

### What browsers are affected?

Firefox

### What happened?

Hi, I use multiple components of the same type on one page. The problem is they have the same id (internally uuid). This is problem because internally `<label>` does not work properly.

In `x-checkbox` I can pass `:id` prop https://github.com/robsontenorio/mary/blob/main/src/View/Components/Checkbox.php
However in other components I can not pass `:id` prop https://github.com/robsontenorio/mary/blob/main/src/View/Components/Toggle.php

**Comment by robsontenorio** [comment]
Hey @anfeichtinger , could you please take care of this?

**Comment by misog** [comment]
@anfeichtinger also other components, see https://github.com/robsontenorio/mary/tree/main/src/View/Components
