### ISSUE TITLE
event is not dispatch from the <x-nav> component.

### ISSUE THREAD

**Issue by farzadaqajani** [robsontenorio/mary#709]
### maryUI version

1.41

### daisyUI version

4.12.14

### Livewire version

3.5

### What browsers are affected?

Firefox, Chrome, Microsoft Edge

### What happened?

I want to dispatch an event from within the app.blade.php layout and <x-nav> component inside it and listen to it through one of the components that uses this layout. But it doesn't work. I can dispatch the same event from other parts of the app.blade.php layout, such as <x-main> component and its <x-slot:sidebar>.

Shop.php

```php
public $showShopFilterDrawer;

    public function mount()
    {
        $this->showShopFilterDrawer = false;
    }

    #[On('show-filter-product')]
    public function showFilterProduct()
    {
        $this->showShopFilterDrawer = true;
    }
```

app.blade.php

```blade
<x-nav sticky full-width>
        <x-slot:actions>
            <x-button label="" icon="hugeicons.filter"
                      @click="$dispatch('show-filter-product')">
                <div class="hidden md:block">
                    {{ __('Filter Products') }}
                </div>
            </x-button>
        </x-slot:actions>
</x-nav>
```

**Comment by robsontenorio** [comment]
This is a Livewire thing ,not maryUI. 

Event listeners works when components are in parent-child hierarchy. And is not your case. Take look how to use global/window level events in Livewire.
