### ISSUE TITLE
[Question] How to force cropping before accepting image?

### ISSUE THREAD

**Issue by styper** [robsontenorio/mary#714]
### maryUI version

1.41

### daisyUI version

0

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

I'm using the single file upload with preview and cropping, is there a way to only accept the image after it has been cropped?

Scenario is: I'm building a blog like page and the user has the option to upload a cover image.  
In the cropper config I'm using 'aspectRatio' => 16/9 since that's the aspect ratio of the cover div.  
Problem is, when I select an image it's already displayed in the preview, if I click "cancel" on the crop modal then the image persists in the preview without cropping.

**Comment by robsontenorio** [comment]
Actually it would be a new feature `force-crop`, and to be honest there are multiples conflicting scenarios to deal with.

**Comment by styper** [comment]
Understood. I thought maybe there was already a native way since I just started using Mary (great job btw). I may just add an event listener when the modal closes that trashes the image. Thank you for the response!
