### ISSUE TITLE
Uncaught Snapshot missing on Livewire component with id:

### ISSUE THREAD

**Issue by behvandi11** [robsontenorio/mary#720]
### maryUI version

1.41.4

### daisyUI version

4.12.14

### Livewire version

3.5.12

### What browsers are affected?

Firefox, Chrome

### What happened?

Hello, I hope you are well
By searching GitHub, I saw that the error I wrote in the title has been reported several times and cannot be solved using wire:key. The error occurs when a child component is called in each row of the table. It doesn't matter what the child component is, even an empty div! The error occurs. I placed wire in the livewire child tag or in the parent tag, but the problem was not solved.
The error occurs when sorting or filtering is used. With use wire:key, only the problem in pagination is solved. It is interesting that the sorting that is set by default works, but other columns give an error after sorting.

livewire component:
```

#[Title('Users')]
class Users extends Component
{
    use Toast;
    use WithPagination;
    use WithFilters;
    public array $sortBy = ['column' => 'id', 'direction' => 'asc'];

    #[Url]
    public array $filters = [
        'gender' => null,
        'is_admin' => null,
        'block' => null,
        'role' => null,
    ];


    public function render()
    {
        $headers = [
            ['key' => 'id', 'label' => '#'],
            ['key' => 'fullName', 'label' => 'Name', 'sortBy' => 'firstname'],
            ['key' => 'username', 'label' => 'Benutzername']
        ];

        return view('user::livewire.users', [
            'users' => $this->items,
            'headers' => $headers
        ]);
    }

    #[Computed]
    public function items()
    {
        return resolve(UserRepo::class)->getUsersWithFilterQuery($this->search, $this->filters)
            ->orderBy(...array_values($this->sortBy))
            ->simplePaginate();
    }
 }
```

and livewire blade:
```
<x-table :headers="$headers" :rows="$users" :sort-by="$sortBy" with-pagination>
    @scope('cell_fullName', $user)
    <x-avatar
        :image="$user->avatar ? asset('storage/'.$user->avatar['thumb']) : asset('theme/no-image.png')"
        :title="$user->firstname" :subtitle="$user->lastname"
        class="!w-10" />
    @endscope

    @scope('actions', $user)
    <div class="flex items-center">
        <livewire:user::user-view-modal wire:key="view-modal-{{$user->id}}" />
    </div>
    @endscope
</x-table>
```

I set even an empty child but error remain 
this is child component:
`<div>hi</div>`

just by remove child component every thing works fine.

**Comment by v-stamenova** [comment]
Hi @9christian9, I seem to struggle with the same issue. Here is a video reproducing the issue.

https://github.com/user-attachments/assets/178e4af1-6e80-4f7a-9f4b-f369cbba45d9

For some more context this is the code in the table component:
```html
        <x-mary-table :headers="$headers" :rows="$partners" :sort-by="$sortBy">
        
            @scope('cell_actions', $partner)
                    <livewire:pages.internal.partner.changeLogo :key="$partner->id" :partnerId="$partner->id"/>
            @endscope

            <x-slot:empty>
                <x-mary-icon class='text-primary-content' name="o-cube" label="It is empty." />
            </x-slot:empty>
        </x-mary-table>
```

And the code for the ChangeLogo component is the following:
```html
<div>
    <x-mary-modal box-class="gap-0 w-screen max-w-screen-lg" wire:model="createIsOpen"
                  title="Add a new partner {{$partnerId}}"
                  subtitle="Collaborating with a company or another association? Add them here."
    >

    </x-mary-modal>

    <x-mary-button class="btn-xs" icon="o-photo" @click="$wire.createIsOpen = true" />
</div>
```

I might be completely misusing the kit, so any info about this would be appreciated greatly :)

**Comment by bureauvk** [comment]
> ```
>         <x-mary-table :headers="$headers" :rows="$partners" :sort-by="$sortBy">
>         
>             @scope('cell_actions', $partner)
>                     <livewire:pages.internal.partner.changeLogo :key="$partner->id" :partnerId="$partner->id"/>
>             @endscope
> 
>             <x-slot:empty>
>                 <x-mary-icon class='text-primary-content' name="o-cube" label="It is empty." />
>             </x-slot:empty>
>         </x-mary-table>
> ```

In this component, is x-mary-table the root of the component?

Try wrap this in just a div and report back please.

**Comment by robsontenorio** [comment]
@behvandi11  @bureauvk  @9christian9  @v-stamenova 

The `wire:key` stuff is really annoying. Try this trick:

There is a builtin `uniqid()` that automatically handles it.

```php
@scope('ANYTHING', $anyvar)
      <livewire:details :user="$user" :key="uniqid()" />
@endscope
```

**Comment by v-stamenova** [comment]
@bureauvk I had it wrapped already so it wasn't the root (that's actually why there was some padding in the snippet haha)

@robsontenorio Found a workaround with the button just firing off an event to open a hidden modal somewhere down the page, but I'll keep it in mind for next time. Thanks!
