### ISSUE TITLE
[Question]  with Signature How to return null when empty picture

### ISSUE THREAD

**Issue by blari18570** [robsontenorio/mary#721]
Hello, I don't know if I'm in the right place for help!
With third-party signature
How to detect if the image is empty or if the delete button was clicked to validate my model.
Thanks!

**Comment by themegazord** [comment]
Maybe i not understand. You be having a problem with the signature component of MaryUi? If yes, i think this better way for check if image is empty is using `empty()` function, no? You tried this?

**Comment by robsontenorio** [comment]
The better approach here is if you have a image of the signature and don't want allow to sign again just make a `@if` logic to hide the component and show the image you have.
