### ISSUE TITLE
Request for Drag-and-Drop Implementation in Table Component

### ISSUE THREAD

**Issue by themegazord** [robsontenorio/mary#723]
I hope this message finds you well. I am writing to request the implementation of a drag-and-drop feature within our table component. This functionality is intended to allow users to reorder rows dynamically and intuitively, improving user experience and aligning with modern interface expectations.

1. Drag-and-Drop Reordering:

- Users should be able to drag table rows and drop them to reorder their position.

2. Persistent Order:

- The new order should be saved and persisted in the database once the user completes the reordering action.

3. Library Suggestion:

- Preferably use livewire/sortable for seamless integration with Livewire.
- Alternatively, other libraries like SortableJS can be considered if they provide better performance or features.

4. Feedback:

- Provide real-time visual feedback during the drag-and-drop process, such as highlighting the drop target.

5. Compatibility:

- Ensure compatibility with existing features and no significant impact on table rendering or performance.

**Comment by robsontenorio** [comment]
That is a good ideia, thanks! 

But it would be an entire new library! 
The current table components does a lot of things right now.
