### ISSUE TITLE
Demo Flow Version

### ISSUE THREAD

**Issue by Dalvani** [robsontenorio/mary#730]
I bought the Flow demo, but the version I'm downloading via the link is not the same version that is running on the demo site. Can you update please?

**Comment by Dalvani** [comment]
When confirming the deletion of a record, the system makes a post to livewire/update.
This route and page do not exist in the downloaded file.
![image](https://github.com/user-attachments/assets/5a7c1d4b-8611-4f3d-8df0-0dd8cc903d1c)

**Comment by robsontenorio** [comment]
@Dalvani  This is how Livewire works. It has nothing to do with maryUI. 

You need to have a proper local setup to run Livewire apps. There is a warning on very beginning on this page, talking about this.

https://livewire.laravel.com/docs/installation
