### ISSUE TITLE
I did not find some features in  tags component 

### ISSUE THREAD

**Issue by PetroGromovo** [robsontenorio/mary#731]
Looking at tags component with code :

`    <x-tags label="Tags" wire:model="tags" icon="o-home" hint="Hit enter to create a new tag" />`

And array defined :
`    public array $tags = ['tech', 'gaming', 'art'];`

I wonder are there ways:

a) to have 2 arrays of accessible/selected items ?
As among all accessible items only some can be selected.
And have possibility to show list of all accessible items(like clicking on icon). 

b) keep data of array in "id/name" format?

```

"laravel/framework": "^11.27.2",
"livewire/livewire": "^3.5.10",
"robsontenorio/mary": "^1.41.4",
```

Thanks in advance!

**Comment by robsontenorio** [comment]
The tag coment is intended  to be simple , like a simple raw string list.  Because it allows to any any text on the fly.

**Comment by PetroGromovo** [comment]
Have you any other similar component suitable for this case ?

**Comment by robsontenorio** [comment]
You can check choices or choices-offline, but it does not allow to enter arbitrary values.
