### ISSUE TITLE
Cropping the image issue with Image Library.

### ISSUE THREAD

**Issue by chrischase011** [robsontenorio/mary#732]
### maryUI version

1.41.4

### daisyUI version

4.12.14

### Livewire version

3.5.14

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

Laravel 11 / Livewire 3.5 / mary-ui 1.41.4 / Cropper JS 1.6.1

I am encountering this error when I tried to crop an image using the Image Library of Mary UI.
![image](https://github.com/user-attachments/assets/cd851528-bccb-4fcb-95e1-d5e5cd229dfb)

The file extension becomes "" (no file extension). I don't know if it lies to Mary UI or in Cropper JS or in Livewire itself.

I'll also provide a video showing the steps I followed when I encountered the issue.

https://github.com/user-attachments/assets/c24489ca-d6ba-4884-b9fe-07e1e5d66965

This is also my code:
```blade
<x-image-library
       wire:model="product_images_files"                 {{-- Temprary files --}}
       wire:library="product_images_library"             {{-- Library metadata property --}}
       :preview="$product_images_library"                {{-- Preview control --}}
       label="Product images"
       hint="Max 5MB" />
```

I don't know if anyone encounters the same or I have some misconfiguration. Hoping for your help. 

Thanks.

**Comment by robsontenorio** [comment]
This error comes from Livewire. It is trying to generate a temporary preview url, but that file extension is invalid. Make a test with png or jpeg to check it.

**Comment by chrischase011** [comment]
> This error comes from Livewire. It is trying to generate a temporary preview url, but that file extension is invalid. Make a test with png or jpeg to check it.

Alright. I'll try that. If not, maybe I'll bring this up to Livewire.

**Comment by chrischase011** [comment]
I tested it with PNG, JPEG, and other supported mime types, but every time I cropped and saved, the error persists.

**Comment by chrischase011** [comment]
I have checked the `$file` in `WithMediaSync.php` trait by logging it..

When I upload the image, this is what I got:

![image](https://github.com/user-attachments/assets/ac578cf0-afc5-48ea-85d5-e0946aa40ecd)

It has file type `(.jpg)`

However, when I cropped:

![image](https://github.com/user-attachments/assets/9174497c-d415-4cfe-996f-5cc2ceb8942b)

the filename becomes just a plain text 'livewire-tmp' without file extension.

I think that causes the error. Just my opinion.

**Comment by robsontenorio** [comment]
@chrischase011  This errors happens on live docs example? Try to upload it there.

**Comment by v-stamenova** [comment]
@chrischase011 I've seen something similar happen but I am not sure if this is the case with your files. Seems like the issue you are encountering is the livewire fallback scenario of not being able to process file with a long name.

My guess to what is going on is that once you upload your file the temp file puts a random name for it. In the screenshot you provided that name is quite long. Then when you crop it, I am not exactly sure the mechanism for it but maybe @robsontenorio can verify if I have the proper gist of the situation, but after completing the crop the temp file is updated the path/name might become even longer.

As I said that might be a bit of a stretch since I have no idea how you process your file since you haven't uploaded any snippets but I think that might be a good starting point. Personally to prevent this issue I've added a trait to my projects to check if the file name is above 200 chars to not be processed. I hope this can help you out a bit.

**Comment by robsontenorio** [comment]
For reference #567

**Comment by chrischase011** [comment]
> @chrischase011 I've seen something similar happen but I am not sure if this is the case with your files. Seems like the issue you are encountering is the livewire fallback scenario of not being able to process file with a long name.
> 
> My guess to what is going on is that once you upload your file the temp file puts a random name for it. In the screenshot you provided that name is quite long. Then when you crop it, I am not exactly sure the mechanism for it but maybe @robsontenorio can verify if I have the proper gist of the situation, but after completing the crop the temp file is updated the path/name might become even longer.
> 
> As I said that might be a bit of a stretch since I have no idea how you process your file since you haven't uploaded any snippets but I think that might be a good starting point. Personally to prevent this issue I've added a trait to my projects to check if the file name is above 200 chars to not be processed. I hope this can help you out a bit.

Hello @v-stamenova, 

This is my code snippets. I just followed what's on the documentation, but basically, this is for a new item.

**Blade**
```html
<x-image-library
    wire:model="files"                 
    wire:library="library"            
    :preview="$library"                
    label="Product images"
    hint="Max 100Kb" />
```

**Livewire PHP**
```php
use WithFileUploads, WithMediaSync;

// Image Library Snippets
 #[Rule(['files.*' => 'image|max:1024'])]
public array $files = [];

// Library metadata (optional validation)
#[Rule('required')]
public Collection $library;

 public function mount()
 {
     $this->library = new Collection();
 }
```

-----------------------

Hello @robsontenorio, might take a look at this. Thank you.

**Comment by robsontenorio** [comment]
Attach here the image you are trying to upload.

**Comment by chrischase011** [comment]
Hello @robsontenorio,

This is the sample image that I am using.

![github](https://github.com/user-attachments/assets/97d10bce-f49d-492b-be92-f28f42899f4b)

**Comment by robsontenorio** [comment]
@chrischase011 


Your snippet is fine. I have tried that image on maryUI live docs and locally and it works. 

Mostly it has to do with some local setup on Windows, as I can se you are using it. I am using Mac, maryUI docs uses Linux.

There is open PR on Livewire's repo https://github.com/livewire/livewire/pull/8690

So, unfortunately I can't see what do now on maryUI side.
