### ISSUE TITLE
File uploader exceeds screen on mobile

### ISSUE THREAD

**Issue by bureauvk** [robsontenorio/mary#735]
### maryUI version

1.41

### daisyUI version

4.12.14

### Livewire version

3.5.16

### What browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

The file uploader is exceeding the page width on mobile.
You can see it in the docs.
https://mary-ui.com/docs/components/file

With the Dutch language its a problem:
![IMG_0154](https://github.com/user-attachments/assets/a4347033-396e-4430-a440-ee1186fff74a)

**Comment by robsontenorio** [comment]
Unfortunately there is nothing we can do here, because it uses the native HTML file upload. You can try to hack it on your own `app.css`.

It is the same of `<input type="file">

**Comment by bureauvk** [comment]
We should add the possibility to add a CSS class to the <input>. Because with a w-full on it, it would be fixed. But when I pass the class now, it only gives it to the root element of the x-file component, not the <input> itself.

**Comment by robsontenorio** [comment]
Have you tried this?

It uses this under the hood `<input type="file">`

**Comment by bureauvk** [comment]
> Have you tried this?
> 
> It uses this under the hood `<input type="file">`

Yes, I understand. I tried it. Yes it fixes it.

**Comment by robsontenorio** [comment]
Just , for sake.  
It is a natural for  behavior `input file`. All approaches exceeds the screen.



<img width="1182" alt="image" src="https://github.com/user-attachments/assets/a08b0638-06a7-43a3-8855-dcd43e4ffde6" />

**Comment by bureauvk** [comment]
I understand. But we should add the option to add a css class to the <input> tag. Shouldn’t we?Op 15 dec 2024 om 14:28 heeft Robson Tenório ***@***.***> het volgende geschreven:﻿
Just for sake.
It is a natural  behavior of input file. All approaches exceeds the screen.
image.png (view on web)
