### ISSUE TITLE
Why in dark layout and some elements looks not good ?

### ISSUE THREAD

**Issue by sergeynilov** [robsontenorio/mary#737]
### maryUI version

 1.40.4

### daisyUI version

4.12.10

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

In laravel 11 / livewire 3.5 / mary-ui 1.40.4 app I use dark layout and some elements looks not good.

I mean rtf editor :

https://prnt.sc/LGRkmiiebkTI

witch I define with code :

```
        @php
            $config = [
                'plugins' => 'autoresize',
                'min_height' => 150,
                'max_height' => 250,
                'statusbar' => false,
                'toolbar' => 'undo redo | quickimage quicktable',
                'quickbars_selection_toolbar' => 'bold italic link',
                'theme_advanced_default_foreground_color' => '#FFFFFF',
                'body_class' =>  'mceBlackBody'
            ];
        @endphp

        <x-mary-editor wire:model="form.description" label="Description" hint="Max 10000 chars" :config="$config"/>

```

I tried to change color or body_class - but no effect at all...

and pagination element :

https://prnt.sc/nkOleeqzDazI

If there is a way to looks like all rest components depending on current color layout ?

**Comment by robsontenorio** [comment]
Have you added custom CSS pointed on Mary pagination docs?

<img width="930" alt="image" src="https://github.com/user-attachments/assets/ebc9ec4e-54b2-4d3e-80f0-d038ec271be8" />


The x-editor does not support theme toggle on the fly. This is a limitation from tinyMCE.
But once dark mode is set, if you hit ctrl+F5 it will work.

<img width="948" alt="image" src="https://github.com/user-attachments/assets/12429c36-a75c-4ef3-9383-c6621b56038a" />

**Comment by sergeynilov** [comment]
Thanks! It helped for pagination component. What about x-mary-editor component ? It is white in any style...

**Comment by robsontenorio** [comment]
Add the x-theme-toggle and it will work, after refreshing the page. 
But it won’t change on the fly because of tinyMCE   limitation. You need to refresh the page. 

If you know how to fix this let me know.

**Comment by sergeynilov** [comment]
Thanks for your job and for your support  ! 
component <x-theme-toggle class="btn" @theme-changed="console.log($event.detail)" /> helped and 
1) Yes, I need to restart page to change color of tinymce editor.
2) 2 colors are switched, but in tailwind.config.js there are 4 colors set :

```
    plugins: [require('daisyui')],
    daisyui: {
        themes: [ "aqua",  'light', 'dark', 'cupcake']
    },
    darkMode: 'class',

```
