### ISSUE TITLE
local currency.js install not working

### ISSUE THREAD

**Issue by ITO-lotto** [robsontenorio/mary#740]
### maryUI version

1.41

### daisyUI version

4.12.20

### Livewire version

3.5

### What browsers are affected?

Chrome

### What happened?

I try to use currency.js locally. I have installed currency.js via:
```bash
npm install currency.js
``` 

I then integrated it into my resources/js/app.js using 
```javascript
import './bootstrap';
import currency from 'currency.js';
```

Then I restarted ```npm run dev``` and it didn't work.

This is my current app.blade.php layout:

```blade
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ isset($title) ? $title.' - '.config('app.name') : config('app.name') }}</title>

    {{-- Cropper.js --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.css" />

    {{-- Chart.js  --}}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>

    {{--  Currency - CDN removed --}}

    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
```

This is the part where I use the x-input with the money attribute:

```blade
<x-input
    wire:model="answers.{{ $question->id }}"
    suffix="€"
    money
    inline
    class="w-full"
    locale="pt-BR"
/>
```

My vite.config.js:
```javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
});
```

I tried multiple app.js configurations, including:
```javascript
import './bootstrap';
import 'currency.js';
```
```javascript
import './bootstrap';
import Currency from 'currency.js';

window.Currency = Currency;
```

I also tried something easy:
```javascript
import './bootstrap';
import currency from 'currency.js';

// Test
const amount = currency(1234.56).format();
console.log(amount); // "$1,234.56"
```
The consol output worked, but not the x-input.

For me, the error seems to be related to MaryUI. I can deploy the currency.js in various forms and also use it in blade, just not with MaryUI components. Maybe I'm missing something, so I'm asking for help here.

**Comment by robsontenorio** [comment]
There is no npm package for it, it is a custom script.  Use CDN like docs example or copy its contents and host locally.

**Comment by ITO-lotto** [comment]
That's totally on me. I was really confident that the component was using the official currency.js and not your version.

I will try later to download it and use it instead of the Node package.

Thanks for the fast response!
