### ISSUE TITLE
Dynamic Rich Text Editor (TinyMCE) not working as expected

### ISSUE THREAD

**Issue by cherosoullis** [robsontenorio/mary#743]
### maryUI version

"robsontenorio/mary": "^1.34"

### daisyUI version

"daisyui": "^4.12.10",

### Livewire version

"livewire/livewire": "^3.5",

### What browsers are affected?

Chrome

### What happened?

I am trying to create dynamic TinyMCE editor on my project. Having only one editor is working just fine. 

I am trying to implement something similar to the following which is working just fine:
<code>
<x-mary-input label=" {{ __('test.name') }} {{ $properties['native'] }}"  wire:model="name.{{ $localeCode }}"  
</code>

where I collect the name as an array.

<code>
  public $name = []
</code>

With TinyMCE I use the following code:
<code>
<x-mary-editor wire:key="{{ $index }}.{{ $localeCode }}" wire:model="name.{{ $index }}.{{ $localeCode }}" label="Description" hint="Final Destination" />
</code>

I get consol error :
Livewire Entangle Error: Livewire property ['name.0.el'] cannot be found on component:

The Component is loaded twice as expected but I cannot collect the values like the above code
<code>
  public $name = []
</code>

Can you please help me on this issue? Thanks in advance

**Comment by robsontenorio** [comment]
Please , follow #742

**Comment by robsontenorio** [comment]
@cherosoullis 

Actually this is a Livewire thing.  And you will get same error if using html basic `input`.


When dealing with array of models you have in someway to preset that array keys .


**This works**

```php
// preset 3 keys here
public array $texts = [
        '',
        '',
        ''
    ];
```

```html
//  3 keys here

@for($i = 0; $i <= 2; $i++)
   <x-editor wire:model="texts.{{ $i  }}" />
@endfor
```


**Or this**

```php
// preset 2 keys here
public array $texts = [
        'en' => '',
        'fr' => '',
    ];
```

```html
 <x-editor wire:model="texts.en" />
 <x-editor wire:model="texts.fr" />
```

**Comment by cherosoullis** [comment]
This is not happenting when I use:
             <livewire:quill-text-editor wire:key="{{ $index }}.{{ $localeCode }}"
                                    wire:model="execution.{{ $index }}.{{ $localeCode }}" theme="snow" />

Because I collect all data with 
  public $execution = [];

and the results are:

  +execution: array:2 [▼
    0 => array:2 [▼
      "en" => "<p>sdfasdfsa</p>"
      "el" => "<p>sdfasfdασδφασδφασδ</p>"
    ]
    1 => array:2 [▼
      "en" => "<p>σδσδφασδφ</p>"
      "el" => "<p>asdasdf</p>"
    ]
  ]

**Comment by robsontenorio** [comment]
We don’t have Quill editor on maryUI.
