### ISSUE TITLE
I want to use /login but the sidebar appears in it app.blade.php 

### ISSUE THREAD

**Issue by shadmanshaikh** [robsontenorio/mary#747]
### maryUI version

1.26

### daisyUI version

4.10.1

### Livewire version

3.4

### What browsers are affected?

Chrome

## how to make login page in mary ui just like you have shown in the demo project like ping and flow

**Comment by shadmanshaikh** [comment]
I did use @extend() and @section() but its not working for me , I essentially had created another layout file called auth.blade.php , but not success.

``


<div>
    @extends('components.layouts.auth')
    
    @section('content')
        <form wire:submit.prevent="login" class="space-y-6">
            <div>
                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                <x-input id="email" type="email" wire:model="email" placeholder="you@example.com" class="mt-1 block w-full" />
                @error('email') <span class="text-red-500 text-sm">{{ $message }}</span> @enderror
            </div>
            <div>
                <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                <x-input id="password" type="password" wire:model="password" placeholder="Your strong(!) password" class="mt-1 block w-full" />
                @error('password') <span class="text-red-500 text-sm">{{ $message }}</span> @enderror
            </div>
            <div class="flex items-center justify-between">
                <label class="flex items-center">
                    <x-checkbox id="remember" wire:model="remember" class="mr-2" />
                    <span>Remember me</span>
                </label>
                <a href="#" class="text-sm text-indigo-600 hover:underline">Forgot your password?</a>
            </div>
            <div>
                <x-button type="submit" class="w-full">Log in</x-button>
            </div>
        </form>
    @endsection
</div>

``

**Comment by robsontenorio** [comment]
Unfortunately the "layout stuff" like templates/extends/section is out of scope. Because, it is not about maryUI components.

**Comment by shadmanshaikh** [comment]
so how make a login page similar to flow or ping demo projects shown in maryui.com
