### ISSUE TITLE
x-choices options 

### ISSUE THREAD

**Issue by lucas-davi** [robsontenorio/mary#86]
Hello guys

It's possible to define the position and max height of options in x-choices component? 

Example

![image](https://github.com/robsontenorio/mary/assets/60628727/3b9b285b-a42b-4224-b031-e200384f474a)

**Comment by robsontenorio** [comment]
@lucas-davi  What do you mean by `position` ?

**Comment by lucas-davi** [comment]
@robsontenorio open options up or down

**Comment by robsontenorio** [comment]
@lucas-davi you can hack this by using CSS/Tailwind. 

As soon as possible I will re-work Choices component. 

Will close for now.
