### ISSUE TITLE
Textarea value

### ISSUE THREAD

**Issue by Xety** [robsontenorio/mary#88]
Hello,

I wanted to pass value to the textarea without using `wire:model`, but it looks like it is not possible :
```html
<!-- INPUT -->
<textarea                
    placeholder = "{{ $attributes->whereStartsWith('placeholder')->first() }} "     
                                                        
    {{
        $attributes                            
        ->class([
            'textarea textarea-primary w-full peer',                                 
            'pt-5' => ($inline && $label),                                     
            'border border-dashed' => $attributes->has('readonly'),
            'textarea-error' => $errors->has($modelName())
        ]) 
    }}                                    
></textarea>
```
since textarea does not accept `value`, you must wrap your content between `<textarea></textarea>` tags.
I think you should add `{{ $slot }}` between those tags to make it possible.

**Comment by robsontenorio** [comment]
You are right , we need to allow default slot. Once there is no “value” attribute for textarea html specification. 

![image](https://github.com/robsontenorio/mary/assets/118955/600fb5a3-4ad6-4bc5-b3c8-69a6ef1b4ae4)

**Comment by robsontenorio** [comment]
@Xety Upgrade to latest version.
