### ISSUE TITLE
Two Issues with Choices

### ISSUE THREAD

**Issue by pastorryanhayden** [robsontenorio/mary#89]
I'm running into two visual issues with the choices component:

First, the searchable input is outlined in the text box.  I can't figure out how to make that go away.
![CleanShot 2023-10-21 at 07 56 08@2x](https://github.com/robsontenorio/mary/assets/4194905/fd727b6d-a081-4740-bcf4-53435cdb0aba)

The second issue is that when I search for something, the returned list is cut off.
![CleanShot 2023-10-21 at 07 56 16@2x](https://github.com/robsontenorio/mary/assets/4194905/7333127f-9b62-4d99-ae87-4f4391413959)

I'm using Breeze and also have some Filament tables elsewhere on the site, but I've followed your installation instructions and haven't run into any issues with any other components.

Any ideas?

**Comment by robsontenorio** [comment]
I suspect Breeze or Filament CSS is leaking. So affects Mary components. 

There is no easy solution for this and you need to hack their existing css definitions. Because Mary was designed to be the main component library.

**Comment by robsontenorio** [comment]
By the way, if you use Filament it has their own “choices” component. Right ?

**Comment by l3aro** [comment]
ah I ran into this problem in day one as well, but I manage to solved it. You need to remove the preset defined by filament and setup all variables by your owns.

**Comment by robsontenorio** [comment]
@l3aro I am afraid there is nothing I can do about it, once Filament and Breeze place all those settings that overrides default css stuff.

**Comment by pastorryanhayden** [comment]
Thanks for the info.  I appreciate it. And thanks for the great library.

**Comment by pastorryanhayden** [comment]
For anyone finding this in the future, I actually had misdiagnosed the problem(s).
There were two things going on:  
1. I was importing two other Tailwind Component libraries that may have been causing the issue (and Filament wasn't one of them.)  I was importing Tailwind Forms and Flowbite in my Tailwind Config file, even though I wasn't using either of them.  That was what was causing the weird search box issue.
2. I had "overflow hidden" set on the containing div which was cutting off the choices search results.  
After fixing those two things, the component is once again acting as expected.

**Comment by thinkingcap** [comment]
The tailwind forms plugin seems to cause this for me, removing it fixes the mary-ui side but then filament tables renders weird checkboxes.
