### ISSUE TITLE
Navigate Livewire

### ISSUE THREAD

**Issue by alexnogueirasilva** [robsontenorio/mary#94]
I have an issue using the 'navigate' with Mary. Every time I use it, some clicks stop working. Is there a solution?

[Screencast from 23-10-2023 17:59:51.webm](https://github.com/robsontenorio/mary/assets/29835529/0aaa8460-1246-4a0c-beaa-f7e3b9991beb)

**Comment by robsontenorio** [comment]
@alexnogueirasilva I can't where you mouse is clicking or what click is missing. Please, could you be more precise?

**Comment by alexnogueirasilva** [comment]
@robsontenorio 
I am clicking on the logoff and Collapse buttons, but nothing happens. It's worth noting that this only occurs when using the navigate feature.

[Screencast from 23-10-2023 20:57:17.webm](https://github.com/robsontenorio/mary/assets/29835529/cb533f45-51b5-44c1-ab4b-da54bc1e5c18)

**Comment by alexnogueirasilva** [comment]
![Screenshot from 2023-10-23 22-44-20](https://github.com/robsontenorio/mary/assets/29835529/938d0ad8-cd1b-4a2c-81f7-29aed1cdfa46)


These are the errors that appear in the console; they are the same without the 'navigate'.

**Comment by robsontenorio** [comment]
@alexnogueirasilva Mary does not have that “share-modal.js”. 

I am afraid you have installed other tools and its config is leaking across app.

**Comment by alexnogueirasilva** [comment]
I've tested it in other browsers and the same error occurs. The “share-modal.js” is not present. Upon further analysis, it seems to be an issue with Chrome. However, the same behavior occurs after logging in using `$this->redirect(route('dashboard')`, navigate: true); in other browsers as well.
![Screenshot from 2023-10-24 07-48-16](https://github.com/robsontenorio/mary/assets/29835529/2bed32ef-dd3b-436b-916d-1d40f4d8ca59)

**Comment by alexnogueirasilva** [comment]
I had a similar issue with Flowbit and resolved it this way. I'm not sure if it's the best approach, but it's how I managed:

<script data-navigate-once>
         document.addEventListener('livewire:navigated', () => {
             initFlowbite();
         });
</script>
```"

**Comment by alexnogueirasilva** [comment]
I have the following perspective: my login screen uses a guest template without the `<x-slot:sidebar>`. When I log in, it doesn't reload, and as a result, the necessary files or those contained within `<x-slot:sidebar>` are not loaded. That's why the logout button click doesn't work, as well as the Collapse function. When I do a reload, these files are reloaded.

**Comment by alexnogueirasilva** [comment]
After analysis concluded that the issue is with Livewire, I am investigating to understand the root cause of the problem. There is no issue with Mary.
