### ISSUE TITLE
Placeholder x-select

### ISSUE THREAD

**Issue by lucas-davi** [robsontenorio/mary#95]
Hello!

in the x-select component, the placeholder has the value 0.

https://github.com/robsontenorio/mary/assets/60628727/f2836f09-872a-443a-a87d-9ea38fb84520

add value="" to the placeholder option in the component, wouldn't that be interesting?

sorry my bad english.

thanks for the help 😊

**Comment by robsontenorio** [comment]
`public int $status_id = 0;`

**Comment by lucas-davi** [comment]
my property accept null value, but the placeholder pass 0 automatic.

**Comment by robsontenorio** [comment]
@lucas-davi Nice catch. I will add a “placeholder-value” attribute , to allow you pass whatever you want.

**Comment by robsontenorio** [comment]
@lucas-davi  Upgrade to latest version. If your default value is NULL, just omit `placeholder-value`.


```php
public ?int $selectedUser2 = null;
```

<img width="874" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/6dcd3dfe-476e-4d65-945e-195c1d8aeaab">
