### ISSUE TITLE
x-choices required and validation

### ISSUE THREAD

**Issue by bucari** [robsontenorio/mary#99]
Hi @robsontenorio,

I have a x-choices inside a x-form like this.

```
<x-form wire:submit="save">
    <x-choices label="Dirigente a cui inviare la richiesta" wire:model="dirigente_id" :options="$dirigenti"
        search-function="searchDirigente" no-result-text="Nessun risultato trovato..." single searchable
        disabled='!$is_create_or_edit' required />
    
    <x-slot:actions>
        <x-button label="Save" class="btn-primary" type="submit" spinner="save" />
    </x-slot:actions>
</x-form>
```
The required attribute doesn't work when the form is submitted and x-choices is empty.
And if i remove the required attribute and validate rquired server side the border is not red and only validation message is displayed

![image](https://github.com/robsontenorio/mary/assets/97893337/be043b84-bf13-4bc4-8a5b-00532746b6ed)

**Comment by robsontenorio** [comment]
@bucari  

For sure I need to rework Choices. I was first made for first Livewire betas. 

I am waiting some PR got merged at Livewire repo.

**Comment by bucari** [comment]
ok, thanks.
It would be nice if it were possible to customize the selected items as well as the list of options.

And it would be very nice if search-function could accept an API entry or a api route name like this

```
    Route::get('/cities/search/{search}', function ($search) {
        return City::where('name', 'ilike', '%' . $search . '%')->get();
    })->name('api-city-search');
```

**Comment by robsontenorio** [comment]
@bucari  Please, follow #107
